supabase/cli

src/commands/eject.ts
src/commands/supabase.ts

Feature.
Add back `supabase eject`.

feat: add back `eject`

---

src/commands/stop.ts

OS: Ubuntu 20.04 LTS
**Issue**: Calling `supabase stop` doesn't affect on running containers. 
*supabase start*: docker-compose --file .supabase/docker/docker-compose.yml --project-name supabase up -d
> Creating network "supabase_default" with the default driver
Creating supabase-db   ... done
Creating supabase-kong ... done
Creating supabase-auth     ... done
Creating supabase-realtime ... done
Creating supabase-rest     ... done
*supabase down* with current command:  docker-compose --file .supabase/docker/docker-compose.yml  down
> Removing network docker_default
WARNING: Network docker_default not found.
*supabase down* fix:  docker-compose --file .supabase/docker/docker-compose.yml **--project-name supabase** down
> Stopping supabase-realtime ... done
Stopping supabase-rest     ... …

Calling `supabase stop` doesn't affect on running containers

---

.github/workflows/ci.yml
src/cli.ts
src/commands/eject.ts
src/commands/init.ts
src/commands/start.ts
src/commands/stop.ts
src/templates/init/README.md
src/templates/init/docker/postgres/auth-schema.sql

Bug fix.
The `auth` schema isn't included in the `postgres` role's `search_path`.
Include it in the `search_path`. Also:
- update `.supabase/README.md`,
- improve error handling.
Closes #9.

fix: add `auth` to postgres's search_path

---

src/commands/eject.ts
src/commands/init.ts
src/commands/start.ts

Bug fix.
- fix: wrong printed apikey for service_role
- fix: build & create container on init
- fix: match `eject`'s apikeys with `init`
Fixes https://github.com/supabase/supabase/discussions/1029.

Fix `eject` apikeys

---

src/templates/init/docker/docker-compose.yml

Bug fix.
Closes #14.
Add the suggested Kong config.

fix: kong DNS delay on Docker on WSL2

---

src/commands/init.ts

Bug fix.
On `supabase init`, when encountering any error (except when `.supabase` already exists) or receiving Ctrl+C, do cleanup (remove invalid `.supabase`).
Also, print helpful error messages on errors.
Closes #17.

fix: cleanup on aborted init

---

src/commands/init.ts
src/templates/init/docker/kong/kong.yml

bugfix
Only client key is available to use
service key is also available
https://github.com/supabase/supabase/discussions/1253
Not sure if this is the right kind of fix.

add serviceRoleApiKey to kong

---

src/commands/eject.ts
src/commands/init.ts
src/templates/init/docker/docker-compose.yml
src/templates/init/docker/kong/kong.yml

Feature.
No SMTP server, so no way to check sent emails.
Fixes #22.
Adds an email testing server (inbucket). Can't do things like password reset yet, but at least we can now see sent emails for email confirmation, invitation, password reset, and magic link.

Add email testing SMTP server

---

src/commands/start.ts

Bug fix or enhancement depending on your point of view
Currently the cli assumes the containers have already been created (via `supabase init`) so running `start` works but if you haven't run `supabase init` and have instead commited the `.supabase` directory, it doesn't work. Using `up` allows you to run it in this case. I can't run `supabase init` because I'm trying to run it in GitHub Actions and it has prompts that I don't see a way of bypassing, but that's a separate issue.
Using `up` instead of `start` is essentially the same thing as the existing functionality since if the containers have already been created it just runs `start`.

Replace docker-compose start with docker-compose up in start command

---

package-lock.json
src/commands/eject.ts
src/commands/init.ts
src/templates/init/docker/docker-compose.yml
src/templates/init/docker/kong/kong.yml
src/templates/init/docker/postgres/Dockerfile
src/templates/init/docker/postgres/storage-schema.sql

similar to https://github.com/supabase/supabase/pull/1007

add storage to cli

---

src/commands/start.ts

I was using the CLI to start the local env, but the `start` was failing, I had no idea why cause the error message was not very informative.
The error was because the port was already in use.
So, I added a more descriptive message to know about the error.
A simple error message:
`Error running docker-compose.`
It now displays the error message entirely.

Add more error informations for start command when docker-compose fail

---

internal/init/init.go
internal/link/link.go
internal/utils/utils.go

fix: GetGitRoot stuck

---

internal/utils/utils.go

Upgrades realtime image tag to v0.19.0.
It is currently on v0.18.0, which gives a socket connection error.
The v0.19.0 resolves the socket connection error.

Upgrade realtime image to v0.19.0

---

internal/utils/utils.go

Bug fix
Add supabase/postgres:14.1.0 to dbVersion on config.json
https://github.com/supabase/cli/issues/90

Add supabase/postgres:14.1.0 for config.json

---

internal/utils/utils.go
internal/utils/utils_unix.go
internal/utils/utils_windows.go

Bug fix.
The `supabase init` command hangs within projects missing a .git folder on Windows devices due to a directory traversal loop. Root on Windows starts with an uppercase letter, followed by a colon and backslash instead of just a forward slash on Unix. The program was unable to determine root on Windows.
Fixes #89.
Build tags have been utilized to create platform independent functions to test whether a directory is root.
Tested on Ubuntu 16.04 and Windows 11.
N/A

fix: supabase init hang on windows

---

internal/start/start.go

Bug fix/feature addition: SELinux compatible volume mounts, useful ie. when the host OS is Fedora. Fixes #106.
Mounts the `pgbouncer.ini`, `userlist.txt`, and `kong.yml` files with the read only (`:ro`) flag.
Mounts the `pgbouncer.ini`, `userlist.txt`, and `kong.yml` files with the SELinux compatible flag. I have chosen the lowercase z variant (indicating that the bind mount content is shared among multiple containers) just in case the user also uses their own docker containers alongside Supabase's (ie. VSCode devcontainer). This does mean the files are no longer mounted in a read-only way, unfortunately you can't use both flags at the same time. 
I had originally submitted the feature request as I am not familiar with Go development and wasn't sure if I could figure out how to locally …

Update docker volume mount flags for SELinux compatibility.

---

internal/db/remote/set/set.go

Fixes https://github.com/supabase/cli/issues/95.
The URL passed to `supabase db remote set` now has to be percent-encoded.

fix(db remote set): validate url

---

internal/start/start.go

Changes the permissions of the `supabase/.temp/kong.yml` file after creating it to make sure it is readable from the Kong container.
Fixes #129 
`os.WriteFile` is used but as the doc states, the permissions mask that is given as an argument is applied *before* umask. If someone uses an umask where the `others` permission is more restrictive, the container won't start.
The start script manually calls `os.Chmod` after writing the file to ensure the right permission mask. The container successfully starts

fix: Ensure kong config is readable from the container after umask

---

cmd/root.go

Bug fix
When calling `supabase --version` no newline is inserted  (zsh fixes for that by adding a `%` sign but bash/sh do not). 
<p align="center"><img width="705" alt="Screen Shot 2022-01-31 at 9 44 15 PM" src="https://user-images.githubusercontent.com/46427323/151853893-3d44e811-4726-4997-a83a-28670120f168.png"></p>
Adding a newline so the version is printed on its own line.

add new line in version template

---

internal/db/changes/changes.go
internal/db/commit/commit.go
internal/db/remote/changes/changes.go
internal/db/remote/commit/commit.go
internal/db/reset/reset.go
internal/start/start.go
internal/utils/textTea.go
internal/utils/utils.go

Fixes supabase/cli#152.
Currently, if you run `supabase start` in a GitHub Action, or locally, piping output e.g. to a file, you get the following error:
```
Error: inappropriate ioctl for device
```
With this PR, if both stdin and stdout are not a terminal, the CLI bypasses BubbleTea's UI drawing methods and just logs status and progress messages to stdout.
```bash
supabase start | cat
Pulling images...
Starting database...
Restoring branches...
Setting up initial schema...
Applying supabase/extensions.sql...
Applying migration 20220201010915_add_shared_configs.sql...
Applying supabase/seed.sql...
Starting containers...
Started local development setup.
API URL: http://localhost:54321
DB URL: postgresql://postgres:postgres@localhost:54322/postgres
Studio URL: http://localhost:54323
anon …
```

Use simple text output if a tty is not available

---

internal/utils/utils.go

Bug fix
The current go true version (`2.3.8`) has a bug where refresh_token requests returns a `null` response -- see:
- https://github.com/supabase/gotrue/issues/348
The bug was fixed in version `2.3.9` -- see:
- https://github.com/supabase/gotrue/pull/349
This PR updates to the latest image (`2.5.0`)

Update GotrueImage to latest 

---

internal/db/push/push.go

Fix an issue where `supabase db push` would fail if there were files in `supabase/migrations` that don't aren't migrations.  e.g. MacOS might create `.DS_Store` files in the `supabase/migrations` filter.
```
❯ supabase db push      
Applying unapplied migrations...
panic: runtime error: index out of range [1] with length 0
goroutine 1 [running]:
github.com/supabase/cli/internal/db/push.Run()
/home/runner/work/cli/cli/internal/db/push/push.go:60 +0x953
github.com/supabase/cli/cmd.glob..func6(0x1d201a0, {0x1763b66, 0x0, 0x0})
/home/runner/work/cli/cli/cmd/db.go:75 +0x17
github.com/spf13/cobra.(*Command).execute(0x1d201a0, {0x1d5ce80, 0x0, 0x0})
/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x1d1eda0) …
```

Handle error for unknown migration files in supabase/migrations

---

internal/functions/new/new.go

Periods aren't usually a word break character in most terminals, so if
you double-click the name to copy it, the period will be selected as
well. The user would then need to erase the period quite
unnecessarily.
Additionally, impose further restrictions on what a valid function name can be.

fix: don't include a period next to the generated fn filename

---

cmd/db.go
internal/db/push/push.go

Adds a new flag `--dry-run` on the `supabase db push` command. If enabled this will print out the migrations that would be applied **without** executing anything on the database. 
No support for this flag, AFAIK no way to view which migrations will be applied by `supabase db push`
Flag is added with the behaviour described above.
Updated help:
```
go run . db push --help                          
Push new migrations to the remote database.
Usage:
supabase db push [flags]
Flags:
-d, --dry-run   Print the migrations that would be applied, but don't actually apply them.
-h, --help      help for push
```
Example with dry-run enabled:
```
go run . db push --dry-run
DRY RUN: migrations will *not* be pushed to the database.
Would apply migration 20220202121715_m1.sql:
CREATE TABLE films (
code …
```

feat: Add dry-run flag to db push command

---

internal/utils/config.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

I think for local development we should default to `enable_confirmations = false` to make it easier for folks to get started testing with auth. Wdyt? cc @kangmingtay

fix: auth default disable email confirmations

---

cmd/link.go

changes 
`link --ref`
to 
`link --project-ref`

chore: changes ref to project ref on link

---

internal/utils/config.go

In order to enable `pg_graphql`, the major version 14 should be set to the most recent major version including `pg_graphql`.
Fixes: #231 
Updates to the latest minor version [`14.1.0.19`](https://hub.docker.com/layers/postgres/supabase/postgres/14.1.0.19/images/sha256-85077f51095ca3372fa6b20fe8739b5cc72ac5240f2b6a25fb2a8ebd77a085fd?context=explore) for Major Version 14
Currently the local postgres that is installed is [`14.1.0`](https://hub.docker.com/layers/postgres/supabase/postgres/14.1.0/images/sha256-22d7f41a55cb7410d156ae357ce36d8f17d9b62d919e6ab479db9ba2a291c60c?context=explore)
Which does not contain graphql. The issue in #231 is caused by the local instance not having the graphql extension installed.
- 14.1.0.19 is now installed by `supabase start`
- graphql extensions (and other …

Add up-to-date minor version to supabase config for Major version 14

---

internal/db/push/push.go

Feature - more detailed error messages for `db push`
It's difficult to tell which migration is causing a problem because the migration logs are overwritten each time.
Includes the actual error that happened and which migration timestamp it happened on.

add more descriptive error messages for db push

---

internal/utils/docker.go

Bug fix: removes second call to start exec
Currently exec start is called twice in docker utils: once in `ExecAttach` and another one in `ExecStart`
`ExecStart` call is removed

fix: remove unnecessary exec start call

---

internal/db/reset/reset.go
internal/start/start.go
internal/utils/docker.go

Bug fix
For seed.sql files that exceed the maximum argument length of the Linux distribution used to run the Postgres container the `postgres -c` command will fail. Supabase CLI will then silently fail to apply the seed file.
See related [StackOverflow Max size of string CMD that can be passed to Docker](https://stackoverflow.com/a/70738704) answer about command argument sizes. 
https://github.com/supabase/cli/issues/277 (See related comment)
https://github.com/supabase/cli/issues/274 (I think this might be related, but not sure)
A new Docker utility function DockerAddFile can be used to write a byte buffer to a container, in this case the seed.sql file. Then migrating the seed file is just a matter of using the file option of the `pgsql` command rather than the command option.
Let me …

Support bigger seed.sql files using docker copy

---

internal/db/branch/delete/delete.go
internal/db/changes/changes.go
internal/db/commit/commit.go
internal/start/start.go
internal/utils/docker.go

We use Gitpod internally and therefore we were eagerly searching for a solution of https://github.com/supabase/cli/issues/268. Due to the fact that we were able to run `supabase` in a Gitpod environment by using the official `docker-compose` [setup](https://github.com/supabase/supabase/tree/bc9992ff15a833b5bb0d9714f876eed668bf2757/docker), we had our Proof of Concept that running supabase within Gitpod is doable. Next, we thought it might be a good idea to look into the `cli` and see if we can make it work there too 🙂 
So, although Gitpod is a containerized environment, it turned out that the culprit is something else. Instead, it looks like the CLI is behaving differently when the environment is using Docker in [Rootless mode](https://docs.docker.com/engine/security/rootless/).
Using the …

Gitpod Support

---

internal/utils/docker.go

Bug fix
Supabase CLI creates a Docker client without reading environment variable configuration such as `DOCKER_HOST`.
Fixes #275. 
Reads Docker client configuration from environment variables.
Cherrypick/patch client configuration code from  83b133e as suggested by @soedirgo.

fix: Create docker client from env config

---

internal/utils/config.go

Updates the image version used for Postgres v14 to use the [latest published tag](https://hub.docker.com/r/supabase/postgres/tags).
During local development I encountered a bug with the `pg_graphql` plugin that has already been [fixed upstream](https://github.com/supabase/pg_graphql/pull/154).
I imagine there are other fixes that would be nice to have during local development too.
Thanks, and let me know if this isn't the proper way to update image versions.

Update Postgres14 image version

---

internal/init/init.go
internal/init/init_test.go
internal/utils/config.go

unit tests
51.4% coverage
- 77.1% coverage
- use `fs.Stat` instead of `fs.ReadFile`

Improve init test coverage

---

cmd/login.go
internal/functions/delete/delete.go
internal/functions/deploy/deploy.go
internal/init/init.go
internal/init/init_test.go
internal/login/login.go
internal/login/login_test.go
internal/utils/misc.go

unit tests
login reads from `os.Stdin` and writes to `~/.supabase/access_token`
- dependency inject `io.Reader` and `afero.Fs` for unit testing
- refactor regex compilation to a global variable
- generate random token in test cases
- 94.7% coverage

test: add unit tests for login command

---

.github/CODEOWNERS
.github/workflows/ci.yml
internal/functions/delete/delete.go
internal/functions/deploy/deploy.go
internal/link/link.go
internal/login/login.go
internal/secrets/list/list.go
internal/secrets/set/set.go
internal/secrets/unset/unset.go
internal/utils/api.go

e.g.
```
❯ SUPABASE_INTERNAL_API_HOST=https://api.supabase.green supabase functions deploy hello
Bundling hello
Deployed Function hello on project [ref]
You can inspect your deployment in the Dashboard: https://api.supabase.green/project/[ref]/functions/[function-id]/details
```
Dashboard URL should be `app.supabase.green` instead of `api.supabase.green`, and `app.supabase.com` instead of `api.supabase.io`.
The API helpers refactor should've been in another PR, but can't resist

fix: use dashboard URL instead of API URL

---

cmd/projects.go
internal/projects/create/create.go
internal/projects/create/create_test.go
internal/projects/list/list.go
internal/projects/list/list_test.go

unit test
not tested
- 86.2% for create
- 84.8% for list
Might want to try codegen the supabase api client from openapi specs to reduce code and schema duplication.

test: create and list project commands

---

cmd/secrets.go
internal/db/remote/set/set.go
internal/functions/delete/delete.go
internal/functions/deploy/deploy.go
internal/gen/types/typescript/typescript.go
internal/init/init.go
internal/init/init_test.go
internal/link/link.go
internal/link/link_test.go
internal/secrets/list/list.go
internal/secrets/list/list_test.go
internal/secrets/set/set.go
internal/secrets/unset/unset.go
internal/utils/config.go
internal/utils/misc.go
test/init_test.go
test/link_test.go
test/secrets_test.go

unit test, refactor
- starts moving static file paths to `utils` package
- secret list: 85.7% coverage

test: secret list command

---

.github/workflows/ci.yml

- ci workflow to run on main
ci workflow should run on push to main branch as well in order to get coverage badge

fix ci workflow run on main

---

go.mod
go.sum
internal/db/remote/set/set.go
internal/db/remote/set/set_test.go
internal/testing/pgtest/mock.go

unit test, mocks were setup using actual pg requests / responses captured via a [MITM proxy](https://github.com/jackc/pgmock/blob/master/pgmockproxy/main.go)
- mocks postgres using `pgmock`
- refactors sql statements to const
- switch pgx to simple text protocol: [reasons](https://github.com/supabase/cli/pull/317/files#diff-6b4053a9760d66e9434239790cc06f9c93317040cf101c963d572df25c257a7bR50)
- eliminates [version check query](https://github.com/supabase/cli/pull/317/files#diff-6b4053a9760d66e9434239790cc06f9c93317040cf101c963d572df25c257a7bL39) by reading from pg startup message
-  fixes an [index out of bounds](https://github.com/supabase/cli/pull/317/files#diff-6b4053a9760d66e9434239790cc06f9c93317040cf101c963d572df25c257a7bL97) issue with regex …

test: db remote set command

---

cmd/db.go
cmd/root.go
go.mod
internal/db/commit/migra.go
internal/debug/postgres.go
internal/debug/postgres_test.go

a global debug flag
no debug logging
- adds `SUPABASE_DEBUG=1` env var and `--debug` flag
- prints postgres messages to stderr when debugging
Example
```bash
$ supabase --debug db remote set "postgresql://postgres:password@localhost:5432/postgres"
...
2022/08/01 13:21:14 PG Recv: {"Type":"DataRow","Values":[{"text":"20220729102259"}]}
2022/08/01 13:21:14 PG Recv: {"Type":"CommandComplete","CommandTag":"SELECT 1"}
2022/08/01 13:21:14 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
Error: The remote database was set up with a different Supabase CLI project.
```

chore: adds debug flag for printing postgres messages

---

internal/functions/deploy/deploy.go
internal/utils/misc.go

Fixes: https://github.com/supabase/supabase/issues/7878
Latest Deno version's bundling is having some issues - downgrade to 1.20.3 for now, and later we can switch back to `latest` and use ESZip

fix(functions/deploy): pin deno version for now

---

internal/db/remote/set/set_test.go
internal/start/start.go
internal/utils/config.go
internal/utils/config_test.go

fix(config): interpolate env on load always

---

cmd/db.go
internal/db/commit/migra.go
internal/db/commit/templates/migra.sh

feature
only `public` schema is diffed by migra
exposes a `-s` or `--schema` flag
```bash
$ supabase db commit --migra --schema extensions my_ext
```
Generates `20220804072957_my_ext.sql`
```sql
create extension if not exists "pgtap" with schema "extensions" version '1.1.0';
create type "extensions"."_time_trial_type" as ("a_time" numeric);
```

feat: allow configuring migra schema diff

---

cmd/db.go
internal/db/branch/create/create.go
internal/db/branch/create/create_test.go
internal/db/branch/create/templates/clone.sh
internal/utils/misc.go
test/branch_test.go
test/mocks/docker/server.go

part 1 for fixing https://github.com/supabase/cli/issues/321
branch create fails if `supabase start` is not run.
- allow `supabase db branch create` to succeed by using `MkdirAll`.

fix: branch creation failure after init

---

cmd/db.go
internal/db/branch/list/list.go
internal/db/branch/list/list_test.go

bug fix, unit test
error if current branch is not found
lists all branches

test: db branch list command

---

internal/db/remote/commit/commit.go
internal/init/init.go
internal/start/start.go
internal/utils/config.go
internal/utils/container_output.go
internal/utils/misc.go
internal/utils/templates/globals.sql
internal/utils/templates/initial_schemas/13.sql
internal/utils/templates/initial_schemas/14.sql
internal/utils/templates/initial_schemas/README.md

Use pg_dump instead of schema diff for `db remote commit` if it's the first migration.
This is to handle the common case of users wanting to use the CLI midway after developing their schemas using the dashboard. At that point the schema diff is likely very large and prone to errors.

feat(db remote commit): pg_dump special case

---

cmd/gen.go
internal/gen/types/typescript/typescript.go
internal/utils/misc.go

Previously it included unintended schemas (e.g. `net` from the `pg_net` extension). Since the typegen is only used for supabase/postgrest-js, only include schemas according to the PostgREST config `DB_SCHEMAS`, reflected on `api.schemas` in `config.toml`.
Also remove support for generating types from linked project, since we removed `db_pass` from API.

fix(typegen): only include specified schemas

---

internal/db/reset/reset.go
internal/db/switch_/switch_.go

fixes https://github.com/supabase/cli/issues/321
unable to switch branch if current branch is unset
assume we are switching from `main` branch if unset
caveat: if `main` database already exists, `switch` will write to `_current_branch` file but fail to rename db. User will have to manually edit `_current_branch` or drop `main` database to fix.

fix: assume source branch is main when not set

---

.gitignore
internal/init/init.go
internal/init/init_test.go
internal/init/templates/init_gitignore
internal/utils/config.go
internal/utils/misc.go

feature
Root level gitignore is modified by `supabase init`. The CLI should be agnostic to what users store outside of the generated `supabase` directory.
- creates `supabase/.gitignore`
- do not remove `supabase` directory on failure as it may contain migration files
- use `afero.FileContainsBytes` instead of reading the entire gitignore file

feat: move gitignore to supabase directory

---

cmd/migration.go
internal/db/commit/migra.go
internal/db/commit/migra_test.go
internal/migration/new/new.go
internal/migration/new/new_test.go
internal/utils/misc.go

feature
`supabase migration new <name>` only creates a new file
supports reading from stdin so pipe works, for eg.
```bash
echo "create table pet;" | supabase migration new create_pet_table
supabase db changes | supabase migration new my_diff
```

feat: support stdin when creating new migration

---

cmd/db.go
cmd/link.go
cmd/root.go
cmd/secrets.go

bug
ctrl+c is intercepted at root command, causing stdin to not abort (have to use ctrl+d)
proper way seems to be scanning stdin in a goroutine that also selects on the cancel context.
since we don't have many commands which use signal yet, decided move the signal part instead.

fix: move signal handling to specific commands

---

cmd/migration.go
internal/migration/list/list.go

feature
no visibility on migration history table
```bash
$ supabase migration list
LOCAL      │     REMOTE     │     TIME (UTC)
─────────────────┼────────────────┼──────────────────────
20220809084034 │                │ 2022-08-09 08:40:34
│ 20220810154537 │ 2022-08-10 15:45:37
```

feat: add command to list migrations

---

internal/db/remote/changes/changes.go
internal/db/remote/commit/commit.go
internal/gen/types/typescript/typescript.go
internal/start/start.go
internal/utils/api.go
internal/utils/container_output.go
internal/utils/docker.go
test/main_test.go

Bug fix
`supabase start` was extremely slow due to image pulling
- used mirrored images from ecr (x86 only)
- takes 2 mins to pull everything

fix: switch to ecr for faster image pull

---

internal/db/diff/migra.go

Bug fix
splits migration script into batched statements
sends the whole script as a string

fix: batched query with variable fails

---

internal/utils/docker.go
internal/utils/docker_test.go

Bug fix
fails to pull docker hub image
pulls locally

fix: remove registry prefix from docker hub image

---

internal/db/diff/diff.go
internal/utils/misc.go

Bug fix https://github.com/supabase/cli/issues/369
unable to diff with pgadmin
updated pgadmin image to 0.0.5

fix: bump pgadmin schema diff to 0.0.5

---

.github/workflows/mirror.yml

not needed to access public images

chore: remove docker hub login

---

.github/workflows/release.yml
internal/utils/config.go
internal/utils/misc.go
tools/listdep/main.go

Bug fix
some images are not version pinned
pin all images to latest https://github.com/supabase/kps/blob/master/ansible/arm64_vars.yml

fix: pin dependency images to hosted version

---

internal/init/init.go

With current error it may seems like the supabase cli needs to be reinstalled intead of the directory removed
Current:
`Error: Project already initialized. Remove supabase to reinitialize.`
New:
`Error: Project already initialized. To allow reinitialization remove the directory ./supabase`

chore: clearer error message when project already initialized

---

go.mod
internal/db/diff/diff.go
internal/db/diff/migra.go
internal/db/diff/migra_test.go
internal/utils/parser/state.go
internal/utils/parser/state_test.go
internal/utils/parser/testdata/all.sql
internal/utils/parser/testdata/split_00.sql
internal/utils/parser/testdata/split_01.sql
internal/utils/parser/testdata/split_02.sql
internal/utils/parser/testdata/split_03.sql
internal/utils/parser/testdata/split_04.sql
internal/utils/parser/testdata/split_05.sql
internal/utils/parser/testdata/split_06.sql
internal/utils/parser/testdata/split_07.sql
internal/utils/parser/testdata/split_08.sql
internal/utils/parser/testdata/split_09.sql
internal/utils/parser/testdata/split_10.sql
internal/utils/parser/testdata/split_11.sql
internal/utils/parser/testdata/split_12.sql
internal/utils/parser/testdata/split_13.sql
internal/utils/parser/testdata/split_14.sql
internal/utils/parser/testdata/split_15.sql
internal/utils/parser/testdata/split_16.sql
internal/utils/parser/testdata/split_17.sql
internal/utils/parser/token.go
internal/utils/parser/token_test.go

Splitting long sql string into multiple statements provides clearer debug logs when applying migration.
Current splitter fails to ignore `;` when it's inside a dollar quote. 
The core problem is to figure out whether the current `;` separator is inside an escaped string literal. PostgreSQL has multiple ways of opening a string literal, `$$`, `'`, `--`, `/*`, etc. We use a FSM to guarantee these states are entered exclusively. If not in one of the above escape states, the next `;` can be parsed as statement separator. 
Each statement is split as it is, without removing comments or white spaces. 

chore: implement token based statement splitter

---

internal/utils/misc.go

This adds support for linux/arm64 to the Supabase functions CLI by utilizing the unofficial arm64 builds of Deno from https://github.com/LukeChannings/deno-arm64

feat(functions): add support for deno on arm64 Linux

---

internal/utils/parser/state.go

Bug fix
Byte slices are not copied by value. As a result, buffered reader could overwrite delimiter when scanning more tokens.
Make a copy of the delimiter byte slice.

fix: delimiter slice may be overwritten

---

internal/db/diff/migra.go
internal/db/diff/migra_test.go
internal/db/reset/reset.go

Bug fix #404 
pgx forces batched query to use statement cache even with `config.BuildStatementCache = nil` (possible bug?)
statement cache errors out if the batch contains both a schema change and a row update for new schema
uses vanilla batched query without statement cache

fix: batched migration cannot use statement cache

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/release.yml
.gitignore
.releaserc.json
package.json
scripts/preinstall.js

release go binary to npm
outdated npm
- adds `scripts/preinstall.js` which downloads go binary from github release
- replaces `.releaserc.json` with `package.json`
- tested on node 16 with `npm pack && npm install`

fix: add npm release script

---

cmd/db.go
internal/db/diff/migra.go
internal/db/diff/migra_test.go
internal/db/lint/lint.go
internal/db/lint/lint_test.go
internal/db/lint/templates/check.sql
internal/db/remote/commit/commit.go
internal/db/remote/set/set_test.go
internal/db/reset/reset.go
internal/testing/pgtest/mock.go
internal/testing/pgtest/step.go

feature #298 
no linting
- adds `supabase db lint` with `--schema` flag
- uses [plpgsql_check](https://github.com/okbob/plpgsql_check)  extension
- uses prepared statement to support multiple schema
TODO:
use case
- run check on anything that touches supabase schema
- useful to have the line of code where error occurs (body of function)
- want to check columns are created, ie. created_by, modified_by, etc
Add `f1()` example as a migration script, then run
```
$ supabase db lint -s public,private
Linting schema: public
Linting schema: private
[
{
"function": "public.f1",
"issues": [
{
"level": "error",
"message": "relation \"t1\" does not exist",
"statement": {
"lineNumber": "4",
"text": "FOR over SELECT rows"
},
"query": {
"position": "15",
"text": "SELECT * FROM t1"
},
"sqlState": …
```

feat: add db lint command

---

internal/start/start.go

Supersedes https://github.com/supabase/cli/pull/245
Postgres logs grow indefinitely 
Keeps last 24 hours of logs, one log file per hour
total size ~4GB at `log_statement='all'` level
Ref: https://www.postgresql.org/docs/current/runtime-config-logging.html
```bash
root@202b693ee8da:/# ls -la /var/log/postgresql/
total 23112
drwxrwxr-t 1 root     postgres     4096 Aug 30 17:00 .
drwxr-xr-x 1 root     root         4096 Jan 27  2022 ..
-rw-r----- 1 postgres postgres 23455571 Aug 30 17:00 server_1600_UTC.csv
-rw-r----- 1 postgres postgres      406 Aug 30 16:52 server_1600_UTC.log
-rw-r----- 1 postgres postgres   190377 Aug 30 17:00 server_1700_UTC.csv
-rw-r----- 1 postgres postgres        0 Aug 30 17:00 server_1700_UTC.log
```

fix: add log rotation to postgres

---

internal/db/remote/changes/changes.go
internal/db/remote/commit/commit.go
internal/start/start.go
internal/utils/docker.go

Studying the codebase I've noticed the function `DockerRemoveAll` used as a cleanup function always paired with another function to remove the docker network.
I've refactored the function having a misleading name `DockerRemoveAll` to `DockerRemoveContainers` as `DockerRemoveAll` only removes containers I renamed it to `DockerRemoveContainers` and replaces the usage of the old functions (always used together) to the new version of `DockerRemoveAll` which now calls both.
A spot where the old `DockerRemoveAll` were used lacked the removal of network, is was a bug and is not handler properly.
fixes #425

fix: remove docker network when supabase start is interrupted

---

.goreleaser.yml
cmd/root.go
internal/utils/api.go
internal/utils/api_test.go

Bug fix
netgo dns resolver is bugged on macOS
https://go.dev/src/net/net.go?s=16228:16259
https://github.com/golang/go/issues/12524
Adds cloudflare dns as a fallback. This avoids compiling with cgo enabled.
```bash
$ GODEBUG=netdns=go+2 go run main.go projects list
go package net: GODEBUG setting forcing use of Go's resolver
go package net: hostLookupOrder(api.supabase.io) = files,dns
```

fix: use dns over https as fallback resolver

---

README.md
scripts/preinstall.js

Bug fix #441 
npm could not find `bin/supabase` specified in package.json because windows binary has `.exe` extension.
windows only:
- creates a [hard link](https://docs.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions) in the download directory
- symlink results in permission denied

fix: hard link to binary on windows

---

.github/workflows/automerge.yml
internal/start/start.go

Bug fix #446 
containers uses `unless-stopped` policy which doesn't restart after docker upgrade.
containers can still be stopped via docker cli but are always restarted after docker upgrade.

fix: change restart policy to always

---

internal/db/remote/commit/commit.go

Bug fix #440 
- runs pg_dump from db container
- always use pg14 container for creating dump

fix: support remote commit of pg13 database

---

internal/start/start.go

Bug fix #453 
search_path intentionally not included in pg_dump to prevent abuse https://postgrespro.com/list/thread-id/2448092
sets the default search_path for postgres user via config flag
although it is possible to include alter

fix: set search_path from postgres config

---

internal/login/login.go

Bug fix #457
`supabase login` redirects to `https://app.supabase.com/account/tokens.` on control clicking the link. 
The link has "." at the end.
`supabase login` redirects to `https://app.supabase.com/account/tokens`
Some terminal applications like konsole allows control clicking on the link to open it on the browser and it considers everything as part of url if there is no gap between the characters. In this case it was the period / dot.

fix: supabase login redirects to wrong link

---

cmd/db.go
internal/db/branch/list/list.go
internal/db/branch/switch_/switch_.go
internal/db/branch/switch_/switch__test.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/start/start.go

Bug fix
pg_terminate_backend induces pg_cron scheduler to shutdown
- restart postgres as recommended https://github.com/citusdata/pg_cron/issues/99 
- refactors branch switch to use pgx
- add unit tests
- adds health probe 

fix: restart database after issuing pg_terminate_backend

---

.github/workflows/ci.yml
cmd/status.go
internal/start/start.go
internal/status/status.go
internal/status/status_test.go
internal/utils/misc.go
test/link_test.go
test/main_test.go
test/mocks/supabase/server.go
test/secrets_test.go
test/status_test.go

Bug fix #468 
JWT secret is hard coded
```bash
$ supabase status
supabase local development setup is running.
API URL: http://localhost:54321
DB URL: postgresql://postgres:postgres@localhost:54322/postgres
Studio URL: http://localhost:54323
Inbucket URL: http://localhost:54324
JWT secret: <redacted>
anon key: <redacted>
service_role key: <redacted>
```
Also fixes:
- misspelt health check flag
- status checks all service containers are running
- add unit tests

fix: expose jwt signing secret in status message

---

internal/db/diff/migra.go
internal/db/reset/reset.go
internal/utils/parser/state_test.go
internal/utils/parser/token.go
internal/utils/parser/token_test.go

Bug fix
When lines that are too long are encountered, the scanner in `internal/utils/parser/token.go#Split` fails, but the `.Err()` is not checked, causing the error to be suppressed and the `internal/utils/parser/token.go#Split` func to return partial data.
See #470 
* Errors produced by the scanner used in `internal/utils/parser/token.go#Split` are propagated to the caller.
* Lines up to 256K can now be read by `internal/utils/parser/token.go#Split`.

fix: allow for long lines in SQL migrations

---

internal/db/remote/commit/commit.go
internal/utils/api.go

improves availability
cannot link project if pgbouncer is down
- retries on postgres port if pgbouncer times out
- times out connect after 3 seconds (previously no timeout)
- supports staging red url (previously hardcoded to supabase.co)

fix: retry connecting to remote postgres

---

internal/start/start.go
internal/utils/config.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

Bug fix/feature
You have to use multi-tenant azure application to enable sign-in with azure. which is impractical if you are making an org specific URL. 
This allows specifying a `url` property on external auth providers which will be passed along to GoTrue:
```toml
[auth.external.azure]
enabled = true
client_id = "****"
secret = "****"
url = "https://login.microsoftonline.com/****"
```
The property is optional and will not be passed along if not specified. 
Related ticket in gotrue: https://github.com/supabase/gotrue/issues/292

feat: support configuring arbitrary OIDC provider url for gotrue

---

internal/db/remote/changes/changes.go
internal/db/remote/commit/commit.go
internal/start/start.go
internal/utils/docker.go
internal/utils/docker_test.go

Bug fix
Some ephemeral errors, like rate exceeded, are causing `supabase start` to fail
Retry with exponential backoff in case of ephemeral error
This catch all case should alleviate problems experienced in #419 

fix: implement retry for docker image pull

---

.github/workflows/ci.yml
internal/start/start.go
internal/utils/misc.go
tools/listdep/main.go

Bug fix #493 
log stream from image pull may return `io.EOF` when download isn't complete
happens mostly on public ECR, possibly due to rate limits
check that image exists after pulling, otherwise retry

fix: check image exists after docker pull

---

cmd/db.go
internal/db/branch/switch_/switch_.go
internal/db/diff/migra.go
internal/db/lint/lint.go
internal/db/reset/reset.go
internal/db/test/templates/test.sh
internal/db/test/test.go
internal/db/test/test_test.go
internal/utils/misc.go
internal/utils/templates/initial_schemas/14.sql

feature: `supabase db test`
no cli native way to run tests
- installs `pg_prove` on `supabase_db_cli` container once
- copies `supabase/tests` into `supabase_db_cli` container
- enable pgtap extension temporarily
- runs `pg_prove` via docker exec and prints out results
Example `order_test.pg`
```sql
BEGIN;
SELECT plan(1);
SELECT has_column(
'public',
'order',
'status',
'status should exist'
);
SELECT * FROM finish();
ROLLBACK;
```
Output
```bash
$ supabase db test
supabase/tests/order_test.pg .. ok
supabase/tests/pet_test.pg .... ok
All tests successful.
Files=2, Tests=2,  1 wallclock secs ( 0.01 usr  0.00 sys +  0.04 cusr  0.02 csys =  0.07 CPU)
Result: PASS
```

feat: add db test command using pgtap

---

internal/start/start.go
internal/utils/config.go
internal/utils/config_test.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

Feature
Adds [storage] table to config.toml with a file_size_limit_bytes value that defaults to 50 MiB. This config value becomes the FILE_SIZE_LIMIT env var for the storage docker container.
The storage-api's file size limit is hard-coded to 50 MiB and is not configurable.
This PR fixes #489
The storage-api's file size limit can be configured in config.toml like below:
```
[storage]
file_size_limit_bytes = 52428800
```
If the storage table or the file_size_limit_bytes key are not specified, the limit defaults to 50 MiB.
I'm unfamiliar with Go, so please let me know if I did anything wrong! :grinning:

feat: add storage.file_size_limit_bytes config

---

internal/utils/templates/initial_schemas/13.sql

Bug fix #460
pg_graphql is not available on pg13 docker image
don't call pg_graphql extensions

fix: disable graphql on pg13

---

cmd/start.go
internal/db/diff/migra.go
internal/db/reset/reset.go
internal/start/start.go
internal/start/start_test.go
internal/utils/misc.go
internal/utils/templates/initial_schemas/14.sql

Bug fix #497
Bug fix #498
- updates initial schema such that it can be applied on `postgres` database (will update db reset in another PR)
- uses pgx to initialise globals and apply migrations (avoids size limit of docker exec arg)
- uses pgx to seed data (avoids copying seed file to `/tmp/seed.sql` inside container)
- failure to restore `dump.sql` will not clear branch directory (user may fix the error and restart)

fix: refactor supabase start to use pgx

---

internal/db/lint/lint_test.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/start/start.go

Bug fix #158 
migrations are run in branch database
- run all migrations in postgres database

fix: run db reset on postgres database

---

internal/db/remote/commit/commit.go
internal/db/remote/commit/commit_test.go
internal/link/link.go
internal/migration/list/list.go
internal/utils/api.go
internal/utils/parser/token.go
test/db_test.go
test/link_test.go
test/login_test.go
test/secrets_test.go
test/status_test.go
tools/docgen/main.go

Bug fix
db password `pass word` is parsed as `pass+word` because of `url.QueryEscape()`
db password `pass word` is parsed as `pass word`

fix: improper url-escaping of db password

---

cmd/root.go
internal/utils/misc.go
internal/utils/misc_test.go

fixes #329 and closes #517 
- Cannot execute cli commands in subdirectories. 
- Cannot specify working directory 
- The CLI now will try to find the root of the project upon initialization. 
- If root project is found, then the working directory is changed to it (i.e. for `status`, `start`, `stop` and such).
- If no root project was found, the directory will be kept as is (i.e. for `init` and such).
- The CLI now accepts a new flag `--workdir` that allows users to specify the desired working directory as shown in the help menu:
<p align="center"><img width="816" alt="Screen Shot 2022-10-12 at 10 35 18 PM" src="https://user-images.githubusercontent.com/46427323/195432185-599ef875-fc95-43b4-bb1a-c1942daf4d48.png"></p>
The second change was minimal so I thought it was okay to add it to the …

fix: allow CLI to work within any sub-directory of a supabase project

---

internal/stop/stop.go

Bug fix #184 
Internal schemas are not backed up
Dump all schemas for now. Things could break between CLI version upgrades if image tags change. 
Will revisit after centralising internal schema migrations. 

fix: update ignore schemas for backup dump

---

internal/utils/parser/state.go
internal/utils/parser/state_test.go

Bug fix #527 
single quotes in identifiers causes split error
handles double quote state

fix: handle single quote in identifier name

---

cmd/root.go

Feature
No way to specify which commands are experimental.
Experimental commands can do:
```go
myExperimentalCmd.MarkFlagRequired("experimental")
```
to make sure the flag is explicitly set
To be used for https://github.com/supabase/cli/pull/534

feat: add `--experimental`

---

internal/init/init.go
internal/init/init_test.go

Bug fix #277
no seed.sql generated after init
generates seed.sql as [documented](https://supabase.com/docs/guides/cli/local-development#add-sample-data)

fix: initialise seed.sql as documented

---

internal/start/start.go
internal/utils/config.go
internal/utils/templates/init_config.toml

[Feature]
Allows users to override the `redirect_uri` for an auth provider. This is particularly useful when wanting to run the cli locally and needing to tunnel the redirect uri from some public url to localhost (eg: using Ngrok). 
Closes https://github.com/supabase/cli/issues/543

Allow Redirect URI Overrides from config.toml

---

internal/utils/misc.go
internal/utils/misc_test.go

Bug fix #554
introduced in https://github.com/supabase/cli/pull/522
silently ignore errors from `fs.Exists`, such as permission denied, or path not a directory.

fix: error in getting project root

---

cmd/db.go
internal/db/diff/diff.go
internal/db/diff/migra.go
internal/db/diff/migra_test.go
internal/db/diff/templates/migra.sh
internal/db/lint/lint.go
internal/testing/apitest/helper.go
internal/utils/config.go
internal/utils/docker.go
internal/utils/parser/token.go

Bug fix #479
- creates shadow database in the same container as postgres
- cannot use migra to diff remote project
- adds `db diff --linked` flag
- adds apitest helpers for mocking docker
- sets local pg connect timeout to 2 seconds
- fixes `migra.sh` reporting success on error code 1
- creates shadow database in a new container to accommodate pg_cron

fix: diff against linked project using migra

---

cmd/customHostname.go
cmd/db.go
cmd/test.go

command alias
`supabase db test`
adds alias for `supabase test db` in preparation for more test types

chore: add supabase test command alias

---

cmd/customHostname.go
cmd/db.go
cmd/domains.go
cmd/functions.go
cmd/gen.go
cmd/init.go
cmd/link.go
cmd/login.go
cmd/migration.go
cmd/orgs.go
cmd/projects.go
cmd/root.go
cmd/secrets.go
cmd/start.go
cmd/status.go
cmd/stop.go
cmd/test.go

docs update
too many commands in root, making help text look messy
group commands by their use case
```
$ supabase help
Supabase CLI
Usage:
supabase [command]
Local Development:
db                Manage local Postgres databases
gen               Run code generation tools
init              Initialize a local project
link              Link to a Supabase project
login             Authenticate using an access token
migration         Manage database migration scripts
start             Start containers for Supabase local development
status            Show status of local Supabase containers
stop              Stop all local Supabase containers
test              Run tests on local Supabase containers
Management APIs:
domains           Manage custom domain names for Supabase projects
functions …
```

fix: group cli commands help text

---

internal/db/test/templates/test.sh
internal/db/test/test.go
internal/db/test/test_test.go

fix #571 
`.sql` not supported
- match documented behaviour

fix: support tests in .sql extension

---

internal/db/test/templates/test.sh
internal/db/test/test.go
internal/utils/docker.go

Bug fix / enhancement
See #578 
The `supabase db test` command does not print the `pg_prove` test results if any of the tests fail. This of course makes it difficult to identify the failing test.
The command will now print the stdout results from the `pg_prove` command if it exits with a non-zero exit code.
The new output looks like what I shared in the "Expected behavior" section of the referenced issue.
This makes a small change to a shared function in `internal/utils/docker.go`. It's not clear to me if this will have undesired side effects for other commands. Let me know if you think this could be handled differently.
Thanks!

fix: show pg_prove failing test results

---

internal/start/start.go
internal/utils/docker.go

Bug fix #595
temporary fix as we replace initial schema with migrate.sh

fix: temporarily silence migrate.sh error

---

cmd/functions.go
internal/utils/misc.go

Enable ESZIP format for deploying functions by default. Also, updates Deno to 1.28.0.
Currently, ESZIP format is disabled and can be enabled via `--legacy-bundle=false` flag.
ESZIPs are enabled by default and if you need legacy bundling you will need to add `--legacy-bundle=true` flag.

feat: enable ESZIPs for functions

---

internal/functions/serve/serve.go

Disable `npm` specifiers in `functions serve` since it's not supported in Deno Deploy yet.

fix: disable npm resolution in deno serve

---

internal/db/remote/commit/commit.go

Bug fix
3 seconds may be too short if the RTT is around 1 second
10 seconds should be enough...

fix: bump connect timeout to 10 seconds

---

internal/start/templates/kong_config
internal/status/status_test.go
internal/utils/config.go
internal/utils/templates/initial_schemas/13.sql
internal/utils/templates/initial_schemas/14.sql

Bug fix
Realtime Broadcast and Presence don't work b/c the channel begins with `realtime:` and having the tenant id / external_id as `realtime` causes conflict internally.
Realtime Broadcast and Presence works as expected.
- Issue: https://github.com/supabase/realtime/issues/353

fix: update Realtime tenant id to realtime-demo

---

.github/workflows/mirror.yml

docker images
more than 30 seconds faster image pull when run from GHA: https://github.com/supabase/supabase-action-example/pull/15

chore: mirror dependencies to ghcr

---

cmd/db.go
cmd/link.go
cmd/migration.go
cmd/projects.go
go.mod
go.sum
internal/db/push/push.go
internal/link/link.go
internal/migration/list/list.go
internal/migration/list/list_test.go
internal/utils/credentials/store.go

feature
db password needs to be entered every time
- uses https://github.com/zalando/go-keyring to store db credentials
- support storing credentials for multiple projects (might add `unlink` in the future)
- credentials are saved under `Supabase CLI` namespace
Alternative libraries considered
- https://github.com/docker/docker-credential-helpers
These helper binaries are distributed with docker desktop installation. They talk to each platform's native C APIs. The only downside is credentials are labeled with `Docker Credentials` and will easily confuse with actual docker credentials.
- https://github.com/99designs/keyring
It uses an outdated linux dbus api. Not sure if it's actively maintained.
- implement our own
On **macOS**, we can call `/usr/bin/security` to access keychain. It …

feat: store db pass in credentials store

---

internal/db/push/push_test.go
internal/migration/list/list_test.go
internal/utils/connect.go
internal/utils/connect_test.go

Bug fix #646 
Setting config object does not work on windows
Use dsn format which treats all params as string literal

fix: use escaped pg url for connecting on windows

---

internal/functions/deploy/deploy.go
internal/functions/deploy/deploy_test.go

Currently, users don't have an easy way to find their function's size when deploying. Supabase checks and returns an error in the API layer if the script is above the permitted limit. However, the error is not very user-friendly since users don't know the size of their script.
This PR prints another line when deploying a function (ie. `deploying {name} (script size: X.XMB)`)
This should also work when `--legacy-bundle` flag is set.

fix: show script size after function deploy

---

cmd/db.go
cmd/domains.go
cmd/migration.go
cmd/restrictions.go

Bug fix #680
workdir is parsed before project ref, resulting in ref not found
always parse workdir before loading project ref

fix: load project ref after parsing workdir

---

cmd/functions.go
internal/functions/deploy/deploy.go
internal/functions/deploy/deploy_test.go
internal/functions/serve/serve.go
internal/functions/serve/serve_test.go
internal/utils/eszip/build.ts

This PR allows users to set a custom `--import-map` flag with relative path to an import map. 
This covers following use cases:
* Creating a project-level import_map.json outside of `supabase/functions` to be shared across all functions in the project.
* If you run `deno vendor`, those vendored dependencies needs to be linked using `vendor/import_map.json`

feat: allow providing custom import-map paths to function serve/deploy

---

internal/start/start.go
internal/utils/misc.go

uses the SUPABASE_PUBLIC_URL env var, else the default api endpoint is http://localhost:8080

feat: update studio to add storage UI

---

internal/utils/misc.go

Upgrades postgrest docker image to [v10.1.1.20221212](https://github.com/PostgREST/postgrest/releases/tag/v10.1.1.20221212)

fix: upgrade postgrest to v10.1.1.20221212

---

internal/link/link_test.go
internal/login/login.go
internal/login/login_test.go
internal/utils/misc.go
test/login_test.go

part one of #267 
access token is saved to `~/.supabase/access-token`
prefer saving to native credentials store
fallback to home directory if not available

fix: prefer saving access token to credentials store

---

internal/start/start.go
internal/start/start_test.go
internal/utils/docker.go

Bug fix #707 
also related #687, #665, #142, #118
image pull logs are hidden behind debug flag, resulting in confusing errors
Print pull logs by default. Once the image has been downloaded locally, these logs won't be printed.
```bash
$ supabase start
15.1.0.11: Pulling from supabase/postgres
025c56f98b67: Pull complete
26dc25c16f4e: Pull complete
a032d8a894de: Pull complete
40dba7d35750: Pull complete
8ebb44a56070: Pull complete
813fd6cf203b: Pull complete
7024f61bf8f5: Pull complete
23f986b322e8: Pull complete
1fb05ff7a8d6: Pull complete
74afc7d9bc5c: Pull complete
7c2c7eebef2f: Pull complete
bdd9df7f1d37: Pull complete
33d269a3a052: Pull complete
0e60f1aa369a: Pull complete
6746734d6cc0: Pull complete
976e3d3274d5: Pull complete
b685a82d955c: Extracting …
```

fix: print pull logs by default

---

.goreleaser.yml
README.md

ci
chocolatey package is blocked because goreleaser doesn't support `.tar.gz` format https://github.com/goreleaser/goreleaser/blob/main/internal/pipe/chocolatey/template.go#L37
According to the package reviewer, we need to call `Get-ChocolateyUnzip` on the resulting `.tar` file.
> Hi,
>
> Unfortunately, `Install-ChocolateyZipPackage` is not able to extract .tar.gz files in one step.
> It is caused because of a limitation in 7zip, see this issue: https://github.com/chocolatey/choco/issues/386
>
> You can a call to `Get-ChocolateyUnzip` to extract the resulting .tar file from Install-ChocolateyZipPackage
>
> Regards, TheCakeIsNaOH
skips publishing for now

chore: skip publishing to chocolatey

---

internal/db/remote/changes/changes.go
internal/db/remote/commit/commit.go
internal/start/start.go
internal/start/start_test.go
internal/utils/docker.go
internal/utils/docker_test.go

regression from #709 
Rate limit bug reappeared https://github.com/supabase/setup-cli/actions/runs/3717908241/jobs/6305704807
Use a single pull with retry method

fix: unify image pull with retry implementation

---

internal/db/diff/migra_test.go
internal/start/start_test.go
internal/stop/stop.go
internal/stop/stop_test.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

related #715
pg_dump 14 cannot be used on pg15 project, breaking `--backup` flag
use pg15 image for backup
updates supabase init to pg15 for new projects

fix: initialise pg15 project by default

---

package.json

Bug fix #717 
npx determines bin path from package.json
links are still created postinstall. non-existent bin path won't cause failure

fix: declare placeholder bin for npx

---

internal/db/diff/migra_test.go
internal/testing/apitest/helper.go
internal/utils/docker.go
internal/utils/docker_test.go

Bug fix #715 
AutoRemove might kick in before we inspect container exit code
remove container explicitly

fix: race condition in stop with backup

---

.github/workflows/ci.yml
.github/workflows/mirror.yml
.github/workflows/release.yml
internal/functions/serve/serve.go

supersedes #722 
supersedes #700 
user defined envs are only available to functions
pass user defined envs to all deno commands

fix: inject user envs to all deno commands

---

internal/utils/misc.go

Bug fix #743 
switch to the official mirror

fix: use upstream imgproxy image from docker hub

---

.github/workflows/install.yml
.goreleaser.yml
scripts/postinstall.js

allows github release redirect
eg. https://github.com/supabase/cli/releases/latest/download/supabase_1.27.10_checksums.txt

chore: remove version from archive name

---

internal/utils/misc.go
internal/utils/templates/initial_schemas/15.sql

Bug fix #726
vault was released prematurely
- use latest postgres image without vault
- update gotrue to match hosted platform

fix: bump gotrue image version to match hosted

---

internal/utils/templates/initial_schemas/15.sql

Bug fix #760
left out some entries which caused migrations to rerun
add entries to auth schema migrations table

fix: update auth schema migrations

---

internal/start/start.go
internal/utils/misc.go
internal/utils/templates/initial_schemas/15.sql

feature
updates to latest realtime release
based on https://github.com/supabase/realtime/blob/v2.0.0/docker-compose.yml

fix: bump realtime to 2.0

---

internal/utils/config.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

Docs update
The template for new config.toml files does not include all the currently implemented OAuth providers.
All currently available OAuth providers are listed when initializing a supabase project.
-

Update list of supported OAuth providers

---

internal/stop/stop.go
internal/stop/stop_test.go

Bug fix #729
allow `supabase stop` to clean up all containers and networks even when db is no longer running

fix: clean up containers and network with stop

---

internal/db/start/start.go
internal/start/start.go

Bug fix
relates to #778
10s wait time seems to short on GHA
wait for 20s in total

fix: increase service wait timeout to 20s

---

internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/db/start/start_test.go
internal/start/start.go
internal/start/start_test.go
internal/status/status.go
internal/status/status_test.go

Bug fix
`supabase status` errors if a container is excluded from start
since `supabase start` now waits for services to be healthy, we can change `supabase status` to print stopped services to stderr

fix: report excluded containers with status command

---

cmd/functions.go
internal/functions/deploy/deploy.go
internal/functions/deploy/deploy_test.go
internal/functions/serve/serve.go
internal/functions/serve/serve_test.go
internal/utils/config.go

Feature
Need to set `--no-verify-jwt` flag every time `functions serve` and `functions deploy` commands are run.
Add per-function config to allow setting `verify_jwt`. `verify_jwt` value falls back to the config is the flag is not set - if it's set, it overrides the config.
Closes https://github.com/supabase/cli/issues/280

feat: support `verify_jwt` functions config

---

internal/functions/deploy/deploy.go
internal/functions/deploy/deploy_test.go
internal/functions/serve/serve.go
internal/utils/misc.go

Feature
For each function, `import_map.json` is implicitly used from `supabase/functions/my_func/import_map.json`.
Implicitly fall back to `supabase/functions/import_map.json` if the per-function import map doesn't exist. The priority becomes (in decreasing order):
- `--import-map` flag
- `import_map` per-function config
- `supabase/functions/<function name>/import_map.json`
- `supabase/functions/import_map.json`
[Context](https://supabase.slack.com/archives/C02KMRX22NR/p1673582728382819?thread_ts=1673233215.735009&cid=C02KMRX22NR)

feat(functions): fallback import_map.json to FunctionsDir

---

internal/utils/misc.go

Feature
`supabase/postgres-meta` docker image is currently at v0.54.1.
Upgrades `supabase/postgres-meta` docker image to latest v0.58.0.
Specifically I'm interested in some recent updates to the TypeScript generation logic.

fix: upgrade postgres-meta to v0.58.0

---

cmd/functions.go
internal/link/link.go
internal/login/login.go

Bug fix
`Enter your password:` is printed to stdout, causing wrong content to be piped.
Print interactive prompts to stderr. This seems to be standard practice accepted by posix shell https://unix.stackexchange.com/questions/380012/why-does-bash-interactive-shell-by-default-write-its-prompt-and-echoes-its-inter.

fix: print interactive prompts to stderr

---

internal/gen/types/typescript/typescript.go

Bug fix.
Get an error. #797 
No changes.
The path was changed since `supabase/postgres-meta:v0.56.0`
Current version is v0.58.0, So that makes an error.
https://github.com/supabase/cli/blob/main/internal/utils/misc.go#L36

fix: Correct type generation script path.

---

cmd/start.go
docs/supabase/start.md
docs/templates/examples.yaml
internal/db/remote/changes/changes.go
internal/db/remote/commit/commit.go
internal/db/start/start.go
internal/start/start.go
internal/start/start_test.go
internal/utils/docker.go

Closes #787
relates to #778
If supabase is already started, throws error.
If any service is unhealthy, throws error.
- exit 0 instead (consistent with `db start`)
- adds `--ignore-health-check` flag to exit 0 when services are unhealthy

fix: bypass non-fatal errors when running supabase start

---

internal/start/start.go

Bug fix and feature
Currently healthchecks based on `printf` return always 0 and are false-positive.
Healthcheck config (the port is wrong in order to test, rest has 3000 open, 4000 is closed):
```sh
$ docker inspect -f '{{json .Config.Healthcheck }}' supabase-rest
{"Test":["CMD","printf","\\0",">","/dev/tcp/localhost/4000"],"Interval":5000000000,"Timeout":5000000000,"Retries":3}
```
```sh
$ docker inspect -f '{{json .State.Health.Log }}' supabase-rest
[{"Start":"2023-01-20T17:51:21.136686444Z","End":"2023-01-20T17:51:21.203277311Z","ExitCode":0,"Output":"\u0000printf: warning: ignoring excess arguments, starting with '>'\n"},{"Start":"2023-01-20T17:51:26.211514237Z","End":"2023-01-20T17:51:26.279377587Z","ExitCode":0,"Output":"\u0000printf: warning: ignoring excess arguments, starting …
```

fix: healthcheck printf returns 0

---

cmd/root.go
internal/db/branch/switch_/switch_.go
internal/db/branch/switch_/switch__test.go
internal/db/diff/migra_test.go
internal/db/reset/reset_test.go
internal/db/start/start.go
internal/db/test/test_test.go
internal/functions/serve/serve.go
internal/link/link_test.go
internal/start/start.go
internal/start/start_test.go
internal/status/status.go
internal/status/status_test.go
internal/stop/stop_test.go
internal/utils/config.go
internal/utils/misc.go

Bug fix
sometimes the suggested `--debug` flag doesn't help
- If the error is due to a problem with user's host system, report the underlying error instead of prompting for debug flag.
- include the working directory in error report

chore: improve error handling with command suggestion

---

internal/functions/serve/serve.go

feature
no consistent way for locally served functions to reach host OS
Starting from Docker Engine `20.04`, it's now possible to use `host.docker.internal` consistently across platforms https://stackoverflow.com/a/61424570
https://github.com/supabase/supabase/discussions/9837#discussioncomment-4805370

fix: allow deno functions to reach host OS

---

internal/utils/misc.go

pgmeta update 
Addresses https://github.com/supabase/postgres-meta/pull/483#issuecomment-1408730211

fix: update pgmeta to latest version

---

internal/db/diff/migra.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go

Bug fix #822 
Deferred statements are run before function returns, not when out of scope.
Close migration files immediately to release resources back to the host OS.
Tested locally with
```bash
ulimit -n 200
for i in {1..250}; do supabase migration new "$i"; done
supabase db start
```
Checked all other usage of `defer` keyword and found an issue where postgREST may be restarted before database is fully up. Fixed it in this PR as well.

fix: close migration file immediately after executing

---

cmd/functions.go
internal/db/diff/diff.go
internal/functions/serve/serve.go
internal/functions/serve/serve_test.go
internal/utils/docker.go
internal/utils/misc.go

This PR introduces **experimental** `functions serve --all` option, which would use edge-runtime to serve all edge functions in a project locally.
Please note this is still experimental and missing several key features:
- `verify-jwt` option doesn't work
- `import-maps` doesn't work
TODO:
[x] Update the edge-runtime image tag

feat: Allow serving all edge functions using edge runtime

---

internal/db/diff/diff.go
internal/functions/serve/serve.go
internal/utils/docker.go

If we don't set the container name, the kong proxying to the container wouldn't work.

fix: set container name when calling DockerRunOnceWithStream

---

internal/db/start/start.go

Fixes #825 
The locale of the Postgres database is inherited from the host system.
The locale of the Postgres database matches that of Supabase cloud.
None.

fix: match db locale of Supabase cloud in local development

---

internal/functions/serve/serve.go
internal/utils/misc.go

This updates edge-runtime to v1.0.8, which includes a critical bug fix. Also, I've updated the serve command to pass the `--debug` flag to the container.

Update edge runtime

---

internal/functions/serve/serve.go

A mistake in the previous PR, should have appended the `--verbose` flag instead of sending an empty string. Keep forgetting Docker passes the empty args.

fix: sending empty args to edge-runtime

---

internal/start/start.go

Bug fix
Local auth server is invalidating refresh token - see `GOTRUE_SECURITY_REFRESH_TOKEN_ROTATION_ENABLED` in https://github.com/supabase/gotrue/blob/master/README.md, which is enabled by default.
Disable this security feature, since it's not relevant within a local dev context.

fix: disable refresh token security

---

cmd/root.go
cmd/sslEnforcement.go
internal/ssl_enforcement/get/get.go
internal/ssl_enforcement/update/update.go

Experimental commands for enabling/disabling SSL enforcement for
connections to the DB (PG+pooler).

feat: adds support for enabling SSL enforcement on DB conns

---

cmd/functions.go
internal/functions/serve/serve.go
internal/functions/serve/serve_test.go
internal/utils/config.go
internal/utils/config_test.go

chore
`functions serve` errors without `--all` arg
`supabase functions serve` defaults to serving all functions

fix: defaults to serve all functions

---

internal/utils/misc.go

Bumps edge-runtime to v1.0.15 which included bug fix for #869

fix: bump edge-runtime to 1.0.15

---

internal/utils/misc.go

fixes https://github.com/supabase/cli/issues/870
updates postgres and studio image

fix: bump postgres image to latest slim

---

internal/functions/serve/serve.go
internal/utils/misc.go

This PR bumps edge-runtime to 1.0.20, which adds import maps support.

fix: update edge-runtime to support import maps

---

internal/utils/misc.go

* Updates the Deno binary used by CLI to 1.30.3
* Updated functions-relay to 1.6.0 (which uses Deno 1.30.3)
* Updated edge-runtime to 1.1.1 (which uses Deno 1.30.3)

fix: update Deno 1.30.3

---

internal/db/diff/migra.go
internal/db/diff/migra_test.go
internal/utils/misc.go

Bug fix https://gist.github.com/tmcw/6f43e433bae38fffacec6d2aa5c9345a
- removes all temporary schemas from being diffed by default
- uses `pg_*` wildcard pattern to support both diff and dump

fix: exclude temporary schemas from db diff

---

internal/utils/api.go

Bug fix
There have been more reported cases where dns timed out locally but the fallback resolver was not used.
Use dns over https to handle more cases where native go resolver fails.
tested locally by setting a bogus dns

fix: fallback to dns over http on timeout

---

cmd/root.go
internal/utils/api.go
internal/utils/api_test.go
internal/utils/connect.go

feature
- `supabase link --dns-resolver=https` will use dns-over-https resolver for both api and db hostname

feat: support overriding dns resolver with flag

---

cmd/link.go

Bug fix https://github.com/supabase/cli/issues/878
Required arg validation is processed after PreRun callback, causing confusing errors.
Move project ref validation to RunE
```bash
$ supabase link
Error: required flag(s) "project-ref" not set
Try rerunning the command with --debug to troubleshoot the error.
exit status 1
$ supabase link --project-ref invalid
Error: Invalid project ref format. Must be like `abcdefghijklmnopqrst`.
exit status 1
```
database password is only prompted after ref validation

fix: flag validation order when linking project

---

cmd/db.go
cmd/link.go
cmd/migration.go
internal/db/diff/diff.go
internal/db/diff/migra.go
internal/db/diff/migra_test.go
internal/db/dump/dump.go
internal/db/dump/dump_test.go
internal/db/push/push.go
internal/db/push/push_test.go
internal/db/remote/changes/changes.go
internal/db/remote/commit/commit.go
internal/link/link.go
internal/link/link_test.go
internal/migration/list/list.go
internal/migration/list/list_test.go
internal/migration/repair/repair.go
internal/migration/repair/repair_test.go
internal/utils/connect.go
internal/utils/connect_test.go
internal/utils/misc.go

feature
closes https://github.com/supabase/cli/issues/753
support migrations for self-hosted database via `--db-url` flag, including

feat: support self hosted urls with db commands

---

cmd/start.go
docs/supabase/start.md
docs/templates/examples.yaml

Documentation change to better describe the comma seperated string for excluding multiple containers from starting.
...docs update, ...
Docs for start --exclude describe it as able to exclude multiple containers but only describe excluding one and the syntax is non-obvious.
More documentation is present across manual and docs.

chore: update docs for excluding multiple container images from start

---

internal/db/test/test.go
internal/utils/connect.go
internal/utils/connect_test.go

Bug fix https://github.com/supabase/cli/issues/843
`filepath.Join` returns back slash on windows
Always construct path using forward slash inside container.

fix: db tests path in windows container

---

internal/functions/serve/serve.go

Bug fix https://github.com/supabase/cli/issues/944
`SUPABASE_URL` already points to an internal ip via kong_id, make db_url consistent by using db_id.

fix: use db container url for functions serve

---

internal/start/start.go
internal/start/start_test.go
internal/start/templates/kong_config

feature
Additional jwt tokens can be injected into kong.yaml via env var. For example, the following env var allows jwt token for role `read_only` to be authenticated with kong.
```bash
SUPABASE_AUTH_READ_ONLY_KEY=<jwt_token> supabase start
```

feat: support custom role and jwt keys

---

internal/utils/docker.go

Bug fix #928 
Docker's [IsUserDefined](https://github.com/moby/moby/blob/master/api/types/container/hostconfig_windows.go#L16) is implemented differently on windows. Unify it with unix.
tested in win10 bootcamp

fix: host network identification on windows

---

internal/utils/misc.go

Bumps edge-runtime to 1.1.7 (contains couple of minor fixes, no changes to public API)

fix: update to edge-runtime 1.1.7

---

cmd/functions.go
cmd/sso.go
internal/sso/info/info.go
internal/sso/internal/render/render.go

* Adds the info cmd which returns the service provider (gotrue) SAML settings to be added to the identity provider 
* `supabase sso info --project-ref <project_ref>`
```
PROPERTY             │                               VALUE
───────────────────────────────┼─────────────────────────────────────────────────────────────────────
Single sign-on URL (ACS URL) │ https://projectref.supabase.co/auth/v1/sso/saml/acs
Audience URI (SP Entity ID)  │ https://projectref.supabase.co/auth/v1/sso/saml/metadata
Default Relaystate           │ https://projectref.supabase.co
```

feat: add sso info cmd

---

internal/utils/denos/build.ts

Show a more descriptive and easy-to-understand error when a user tries to deploy a function that doesn't exist.
Ideally, this should be fixed in the Go code that handles the deploy command. However, we currently do some deduction of paths when a directory doesn't exist (eg: traversing down `supabase/functions`). We can refactor that logic and account for true non-existing functions in a future iteration.

fix: Provide a better error message for non-existing function

---

internal/sso/update/update.go

* `--add-domains` wasn't adding the domain because `params.Domains` always defaults to an empty slice and will never by `nil`
* `--remove-domains` wasn't removing the domain because `var domains []string` defaults to nil instead of an empty slice. When the `domainsSet` is empty, `domains` will remain `nil` and thus, no domains will be removed.

fix: make add-domains and remove-domains work

---

internal/start/templates/vector.yaml

supersedes https://github.com/supabase/cli/pull/976
adds vector remap transform for converting container logs to logflare sample format

chore: improve vector logging config

---

internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/db/start/start.go
internal/db/start/start_test.go
internal/start/start.go
internal/start/start_test.go

Bug fix
Seeding can only happen after all service migrations have been run.

fix: seed database after all services are up

---

internal/start/start.go
internal/utils/misc.go

Bumps logflare version to 1.0.1, which has improved health checks and data seeding flow for supabase mode.

chore: bump logflare version

---

internal/functions/serve/serve.go
internal/start/start.go
internal/start/start_test.go
internal/start/templates/vector.yaml
internal/utils/docker.go
internal/utils/misc.go

feature
serving functions locally require a separate command
- `supabase start` will also serve all functions locally
- loads env vars from `supabase/functions/.env` by default
- logs are ingested to logflare and viewable at http://localhost:54327/sources/3
- running `supabase functions serve` after `supabase start` will restart edge runtime

feat: serve all functions on supabase start

---

cmd/sso.go

We'd like users to use `--metadata-url` whenever possible.

fix: use a different example for `sso add`

---

internal/utils/misc.go

New Logflare image was released, bumping up from 1.0.1 to 1.0.2

fix: Bump up Logflare image

---

internal/start/start.go

Bug fix https://github.com/supabase/cli/issues/997
`realtime` schema is owned by `supabase_admin` so migrations have to be run as the same user

fix: use supabase admin role for realtime

---

internal/utils/misc.go

Bump storage image version from 0.34.0 to 0.35.1
I recently ran into this issue https://github.com/supabase/storage-api/issues/255 (can't read a 2+GB file from disk), which is fixed in storage-api version 0.35.0
I'm curious to try out the new version so I can read large files from disk.

fix: update storage api image

---

internal/start/start.go
internal/start/start_test.go
internal/start/templates/kong.yml

Bug fix https://www.notion.so/supabase/Remove-Kong-Token-AuthN-28782c22a29a45b5a1317cb795d98df5?pvs=4
Kong validates jwt which means tokens must be predefined before starting local dev stack
Allows arbitrary jwt to pass through kong. 

fix: remove key auth from kong config

---

internal/db/push/push.go
internal/db/push/push_test.go
internal/migration/list/list.go
internal/migration/list/list_test.go

Bug fix
When running `supabase migration list --db-url` on fresh self-hosted projects, a missing table error is thrown.
```bash
$ supabase migration list --db-url 'postgres://self-hosted'
LOCAL      │ REMOTE │     TIME (UTC)
─────────────────┼────────┼──────────────────────
20230410135622 │        │ 2023-04-10 13:56:22
```

fix: handle missing migration history table as empty

---

internal/utils/templates/globals.sql

Bug fix https://github.com/supabase/storage-api/issues/315
New roles were added to [postgres/init-scripts](https://github.com/supabase/postgres/blob/develop/migrations/db/init-scripts/00000000000000-initial-schema.sql) but they are not available in pg14 docker image.
- add those new roles to globals

fix: update global roles for pg14

---

cmd/functions.go
cmd/login.go
internal/link/link.go
internal/login/login.go
internal/login/login_test.go
internal/utils/access_token.go
internal/utils/access_token_test.go
internal/utils/credentials/input.go
internal/utils/credentials/input_test.go
internal/utils/misc.go

Bug fix
Mask access token like password during login
```bash
$ supabase login
You can generate an access token from https://app.supabase.com/account/tokens
Enter your access token:
Error: Invalid access token format. Must be like `sbp_0102...1920`.
Try rerunning the command with --debug to troubleshoot the error.
exit status 1
```

fix: mask access token when login

---

internal/functions/serve/serve.go
internal/utils/deno.go
internal/utils/deno_test.go
internal/utils/misc.go

feature
fixes https://github.com/supabase/cli/issues/1040
- unable to import modules relative to parent directories
- rewrites import map to a `supabase/.temp/import_maps/<hash>.json`
- bind mounts imported directories to `/home/deno/modules/<hash>` in edge runtime container
- relative paths to parent directories are solved to absolute paths inside container

feat: resolve relative deno import paths for mounting in docker

---

internal/migration/apply/apply.go
internal/utils/parser/token.go

Bug fix https://github.com/supabase/cli/issues/1058
The first file size was carried over due to the use of `viper.Set`. Switch to use a variable instead. 

fix: buffer size override

---

internal/db/reset/reset_test.go
internal/db/start/start.go
internal/db/start/start_test.go
internal/link/link_test.go
internal/migration/apply/apply_test.go
internal/start/start_test.go
internal/testing/fstest/open.go
internal/utils/access_token_test.go
internal/utils/config_test.go

Bug fix https://github.com/supabase/cli/issues/1055
- introduced a scoped variable for checking if backup exists
- refactors common error fs for testing

fix: skip migrations when backup volume exists

---

internal/functions/serve/serve.go
internal/start/start.go
internal/utils/deno.go
internal/utils/deno_test.go

Follow up https://github.com/supabase/cli/issues/1040
- serialized import map should have have lowercase fields, ie. `imports`
- unlike files, imported directories should end with `/`
unrelated
- added health checks so that `docker ps -a` is more informative
Tested with the following config
- `supabase/functions/import_map.json`
```json
{
"imports": {
"http-server": "https://deno.land/std@0.168.0/http/server.ts",
"shared/": "../../shared/"
}
}
```
- `supabase/functions/hello_world/index.ts`
```typescript
import { serve } from "http-server";
import { handler } from "shared/index.ts";
serve(handler, { port: 8081 });
```
- `shared/index.ts`
```typescript
export const handler = async (req) => {
const { name } = await req.json();
const data = {
message: `Hello World ${name}!`,
};
return new …
```

fix: deno import map resolved directory paths

---

internal/functions/serve/serve.go
internal/start/start_test.go
internal/status/status.go

follow up #1061 
container health check is logging too much error
switch to external http health check from host

fix: use external health check for edge runtime

---

internal/utils/templates/initial_schemas/15.sql
internal/utils/templates/initial_schemas/README.md
tools/dump_initial_schema.sh

chore
Since we are restarting auth and storage containers after db reset, it's better to let those services run their own migrations. This simplifies the upgrade process as only image version bump is needed for pg15.
pg14 and pg13 still require updating initial schema.

chore: remove auth and storage from initial schemas

---

cmd/migration.go
internal/db/push/push.go
internal/db/push/push_test.go
internal/db/reset/reset_test.go
internal/migration/apply/apply.go
internal/migration/apply/apply_test.go
internal/migration/up/up.go
internal/migration/up/up_test.go

feature
follow up https://github.com/supabase/cli/issues/1055#issuecomment-1535019708
```bash
$ supabase migration up
Applying migration 20220730063745_full.sql...
Local database is up to date.
```

feat: implement migration up command

---

internal/utils/misc.go

Bug fix https://github.com/supabase/cli/issues/1079
Wrong env var was used by studio. Fixed in new release. https://github.com/supabase/supabase/pull/14205

fix: bump studio image

---

internal/utils/misc.go

Fixes https://github.com/supabase/cli/issues/1071

fix: bump edge-runtime to v1.2.19

---

cmd/stop.go
internal/db/start/start.go

https://supabase.slack.com/archives/C03S3SW9485/p1683767717245129?thread_ts=1683749208.015289&cid=C03S3SW9485
- `supabase stop` will save the backup volume by default
- adds `supabase stop --no-backup` flag to delete volumes

fix: default to save backup on stop

---

cmd/functions.go
cmd/root.go

follow up https://github.com/supabase/cli/pull/1091
call the correct prerun function

fix: functions new arg parsing

---

cmd/functions.go
internal/functions/deploy/deploy.go
internal/functions/deploy/deploy_test.go
internal/functions/serve/serve.go
internal/utils/deno.go
internal/utils/deno_test.go
internal/utils/denos/build.ts

feature
closes https://github.com/supabase/cli/issues/1028
- pass in absolute paths to build.ts
- also drops json bundle support

feat: support deploying functions that imports from parent directory

---

cmd/db.go
internal/db/lint/lint.go
internal/db/lint/lint_test.go
internal/utils/misc.go

Bug fix https://github.com/supabase/cli/issues/1096
- parses `--db-url` and `--linked` flag so that `db lint` works against remote db

fix: support linting remote database by url

---

internal/gen/keys/keys.go
internal/start/start.go

follow up #1081 
- GHA only checks out the head ref of branch by default. To get the branch name, we need to allow env var override.
- connecting realtime to preview branch errors due to missing `_realtime` schema. Let the container initialise itself.

fix: account for github head ref env var

---

cmd/functions.go
internal/functions/serve/serve.go
internal/utils/colors.go

Bug fix https://github.com/supabase/cli/issues/1093
Clearer logs when deno relay is used.

chore: print suggestion when serving with legacy deno relay

---

cmd/db.go
internal/db/diff/migra.go
internal/db/diff/migra_test.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/db/reset/templates/drop.sql

feature
closes https://github.com/supabase/cli/issues/480
closes https://github.com/supabase/cli/issues/1099
Conservatively resets the remote database.
- ignores all supabase managed schemas, including auth, storage, extensions, etc.
- only drop objects in `public` schema to preserve default schema privileges for `supabase_admin`
- applies all location migrations and seeds remote database
```bash
$ supabase db reset --db-url 'postgres://postgres:postgres@localhost:54322/postgres'
Resetting remote database...
Applying migration 20220810154537_full.sql...
Seeding data supabase/seed.sql...
```

feat: support reseting remote database

---

internal/functions/serve/templates/main.ts
internal/utils/misc.go

- Upgrade Edge Runtime to 1.3.4.
- Modified the main serve function to pass `forceCreate: true` option so it will recreate workers per request.

fix: upgrade to edge runtime 1.3.4

---

internal/start/start.go

This reverts commit 3ef9d042a4404b90fc82d563d7479c50d9969149.
Bug fix https://github.com/supabase/cli/issues/1115

Revert "chore: create _realtime schema on startup"

---

internal/utils/misc.go

Upgrade Edge Runtime to 1.3.5, which contains fixes for #1071 and #1114

fix: upgrade edge runtime to 1.3.5

---

internal/db/dump/templates/dump_role.sh

Bug fix https://github.com/supabase/cli/issues/933
Roles with `nosuperuser` and `noreplication` attribute cannot be restored as non-superuser.
Discard these role attributes from pg_dump as these the are [default values](https://www.postgresql.org/docs/current/sql-createrole.html) anyway.

fix: discard role attributes that require superuser from dump

---

cmd/functions.go
internal/functions/deploy/deploy.go
internal/functions/deploy/deploy_test.go

feature
closes https://github.com/supabase/cli/issues/456
- deploys all functions in `supabase/functions` sequentially
- avoids copying build scripts repeatedly for each function
- allow configuring max concurrency
TODO:
We could also consider deploying a single bundle with different entrypoint for each function.
```bash
$ supabase functions deploy
Version 1.30.3 is already installed
Bundling hello
Deploying hello (script size: 306.9kB)
Deployed Function hello on project cimpzzikygouamvsjwxa
You can inspect your deployment in the Dashboard: https://app.supabase.com/project/cimpzzikygouamvsjwxa/functions/hello/details
Bundling hello_world
Deploying hello_world (script size: 21.14kB)
Deployed Function hello_world on project cimpzzikygouamvsjwxa
You can inspect your deployment in the …
```

feat: support deploying all functions

---

internal/gen/keys/keys.go

Follow up https://github.com/supabase/cli/pull/1125
Fixes flakey unit test when gitroot is nil

fix: check for nil git root

---

internal/utils/denos/build.ts

Bug fix https://github.com/orgs/supabase/discussions/14177#discussioncomment-5957134
```ps
file:///C:/Users/qiao/work/cli/supabase/functions/import_map.json
error: Uncaught (in promise) Error: Error: The filename, directory name, or volume label syntax is incorrect. (os error 123)
const ret = new Error(getStringFromWasm0(arg0, arg1));
```

fix: path resolution for deno on windows

---

internal/functions/serve/templates/main.ts

Increases the worker time for edge functions locally

fix: bump local edge functions to 5min of working time

---

internal/db/start/start_test.go
internal/init/init.go
internal/init/init_test.go
internal/testing/fstest/create.go
internal/testing/fstest/stat.go
internal/utils/misc.go

Bug fix https://github.com/supabase/cli/issues/1143
GetGitRoot changes workdir, causing subsequent write to vscode setting to fail if the search recurses to `/`.
Use go-git library for finding git root.

fix: finding git root should not change workdir

---

internal/db/branch/switch_/switch_.go
internal/db/diff/migra.go
internal/db/lint/lint.go
internal/db/lint/lint_test.go
internal/db/reset/reset_test.go
internal/db/start/start.go
internal/migration/apply/apply_test.go
internal/migration/up/up.go
internal/migration/up/up_test.go
internal/start/start.go
internal/status/status.go
internal/utils/config.go
internal/utils/connect.go
internal/utils/connect_test.go

Bug fix https://github.com/supabase/cli/issues/1141

fix: use db password everywhere

---

internal/utils/misc.go

Bump pg-meta to v0.66.0 which incorporates:
- https://github.com/supabase/postgres-meta/pull/577
- https://github.com/supabase/postgres-meta/pull/580
The version currently on prod is v0.64.6, guess we forgot to update the CLI. Diff: https://github.com/supabase/postgres-meta/compare/v0.64.6...v0.66.0

feat(typegen): relationships

---

internal/gen/types/typescript/typescript.go

This was changed [here](https://github.com/supabase/postgres-meta/commit/5e4c87f7b9738b49ff438278d5d99c824a6580bf)

fix(typegen): use the right pg-meta script

---

internal/utils/misc.go

Includes fix for https://github.com/supabase/edge-runtime/issues/104 and better error handling for module load issues.

fix: bump edge runtime to 1.4.1

---

internal/utils/misc.go

https://github.com/supabase/edge-runtime/releases/tag/v1.4.2

fix: bump edge runtime to 1.4.2

---

cmd/init.go
internal/init/init.go
internal/init/init_test.go

Feature, closes #1106.
Users must interact with the prompt to run the init command.
Users can provide a flag to bypass the prompt for the init command.  If the flag isn't provided, there isn't any behavior change.
Without any argument
```bash
nrayburn@nrayburn-macbook cli % go run main.go init                                                                          
Generate VS Code workspace settings? [y/N] y
Open the cli.code-workspace file in VS Code.
Finished supabase init.
```
With yes/y argument
```bash
nrayburn@nrayburn-macbook cli % go run main.go init --create-vscode-workspace=yes                                            
Open the cli.code-workspace file in VS Code.
Finished supabase init.
```
With no/n argument
```bash
nrayburn@nrayburn-macbook cli % go run main.go init …
```

feat: add flag to bypass the prompt for creating a vscode workspace

---

.github/workflows/release-beta.yml
CONTRIBUTING.md
README.md
package.json

docs update
- add steps to install beta release channel
- shorten readme by collapsing non-npm installation steps 
- adds contributing guide for hotfix release and reverting stable

chore: collapse install sections of readme

---

cmd/functions.go
internal/functions/serve/serve.go

Always serve all functions, even when the function name is provided.
Unless there are bugs in edge-runtime, this shouldn't be a breaking change. Otherwise, we roll back this change in a hotfix.

feat(functions): always serve all

---

internal/db/diff/migra.go
internal/db/diff/migra_test.go

Bug fix https://github.com/supabase/supabase/issues/12825
Too many mishaps with diffing auth and storage by default
auth and storage schemas can only be diffed with explicit `-s` flag

fix: exclude auth schema from default diff

---

.github/workflows/release-beta.yml
.goreleaser.yml

release
hopefully allows beta release
- `brew install supabase/tap/supabase@beta`
- `scoop install supabase@beta`

chore: revive beta tap and bucket

---

cmd/migration.go
internal/db/push/push_test.go
internal/db/reset/reset.go
internal/link/link.go
internal/link/link_test.go
internal/migration/apply/apply.go
internal/migration/apply/apply_test.go
internal/migration/repair/repair.go
internal/migration/repair/repair_test.go

feature
closes https://github.com/supabase/cli/issues/1166
- adds a list of statements executed to migration history
TODO:

feat: track migration statements in history table

---

internal/db/test/test.go

`supabase db test` chdirs to /tmp before running tests. This allows `\i supabase/tests/my_helpers` psql macro to work properly.
I just wanted to create and use common helper functions in my pgtap tests without including them to the actual production db via migrations. \i macro could work, but, `supabase db tests` copies supabase/tests directory to the container in the /tmp directory, and then runs `pg_prove /tmp/supabase/tests` from the `/` directory. This forces me to use absolute paths in `\i`, like `\i /tmp/supabase/tests/helpers`. 
```
> supabase test db
/tmp/supabase/tests/database/001_row_level_security.sql .. ok
/tmp/supabase/tests/database/002_course_view.sql ......... ok
/tmp/supabase/tests/database/003_learning_paths.sql ...... ok
All tests successful.
Files=3, Tests=18,  0 …
```

fix: use relative paths for pg_prove to allow psql includes

---

internal/migration/repair/repair.go

Bug fix https://github.com/supabase/cli/issues/1209
- users must supply a version number as per [migration example](https://github.com/supabase/cli/blob/main/docs/supabase/migration/repair.md#supabase-migration-repair)

fix: validate version number for migration repair

---

internal/stop/stop.go
internal/stop/stop_test.go

https://www.notion.so/supabase/Show-a-spinner-when-running-supabase-stop-27519c4405644d3c8cdbd6b6cd43aeae?pvs=4

chore: add spinner for stopping containers

---

cmd/migration.go
internal/migration/squash/squash.go
internal/migration/squash/squash_test.go

Bug fix https://github.com/supabase/cli/issues/192#issuecomment-1599364500
Baselines the earliest version if none is specified.

fix: baseline should work without specifying version

---

internal/utils/misc.go

Bug fix https://github.com/supabase/cli/issues/633
relates to https://github.com/supabase/storage-api/pull/344

fix(storage): copied object should use new version

---

docs/supabase/stop.md

Documentation update for stop command
Incorrectly shows the previous functionality where supabase stop would drop all data by default
Updated the docs to show the new behavior, but I'm not sure I worded it very well.  I tried to maintain the original docs style.

chore(docs): update stop.md to match new default

---

internal/utils/docker.go

Bug fix https://github.com/supabase/cli/issues/1223
Initialise the docker cli in order to extract the api client with active context.
Tested locally by printing the `cli.CurrentContext()`

fix: use active docker context

---

internal/functions/serve/serve.go
internal/stop/stop.go

Bug fix
No need to persist the deno cache volume between docker restarts.

fix: do not mount deno cache volume

---

internal/functions/serve/templates/main.ts
internal/utils/misc.go

* add navigator global ([77ebaf1](https://github.com/supabase/edge-runtime/commit/77ebaf1d24de02b8a11b6a7acf95e033a490cac3))
* handling concurrent requests to workers ([d47f05d](https://github.com/supabase/edge-runtime/commit/d47f05df6a04af2ffa307ae73be53a2c25627f0f))
Also, set the worker timeout to 1 min.
Updated to 1.5.2, which includes this fix - https://github.com/supabase/edge-runtime/pull/127

fix(functions): bump to Edge Runtime 1.5.2

---

cmd/postgres.go
internal/db/diff/migra.go
internal/db/diff/migra_test.go

Bug fix https://github.com/supabase/cli/issues/1253
broke db diff during last refactor, partly because we were missing a unit test
added unit test to check that local migrations are after creating shadow db

fix: apply migrations after creating shadow db

---

internal/db/diff/migra.go
internal/db/diff/migra_test.go
internal/db/start/start.go
internal/db/start/start_test.go
internal/start/start.go
internal/start/start_test.go

Bug fix https://github.com/supabase/cli/issues/1255
Unifies the way database is setup between supabase start, db start, and db diff.

fix: db start should apply internal migrations

---

internal/utils/misc.go

Bug fix #1267 
Storage UI broke between these 2 releases https://github.com/supabase/supabase/compare/7a24ddd...18c0a32
Revert studio to last working version

fix: downgrade studio to avoid storage ui lockup

---

internal/start/start.go
internal/utils/config.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

This PR adds the ability to configure [Kong's `nginx_worker_processes`](https://docs.konghq.com/gateway/latest/reference/configuration/#nginx_worker_processes) value via the below TOML config:
```toml
[kong]
nginx_worker_processes = 1
```
When running in memory-constrained environments, Kong/Nginx may spawn an excessive number of workers, drastically increasing memory usage.
This PR allows users to fine-tune the number of Kong/Nginx worker processes when desired. If no configuration is provided, the previous behavior (`auto`) is used.
For my use case, this allowed me to cut memory usage of the entire Supabase Docker compose by 79%! (1487 MiB -> 312 MiB) by setting it to just `1` (I'm not especially concerned about the reduced routing performance).

feat: add kong config with nginx_worker_processes option

---

internal/db/branch/switch_/switch_.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/db/start/start.go
internal/start/start.go

Bug fix https://github.com/supabase/cli/issues/1277
Wait for storage migrations to finish running before applying user migrations.

fix: wait for containers to be ready after db reset

---

cmd/db.go

feature
`supabase db diff` defaults to diffing against the local database, but there's no `--local` flag, which makes it inconsistent with other `supabase db` subcommands.
Add `--local` flag (basically a noop vs. the existing behavior).

feat(db diff): add --local flag

---

internal/start/start.go

Bug fix #1279 
Removes unnecessary statements from run.sh https://github.com/Logflare/logflare/blob/staging/run.sh#L35

fix: logflare entrypoint should not wait for network

---

.github/workflows/mirror.yml
internal/utils/misc.go

Bug fix
Something broke the upstream [configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials/tree/v2) action v2 since 6 July.

fix: pin configure-aws-credentials action to v1

---

internal/functions/serve/templates/main.ts
internal/utils/misc.go

This PR upgrades Edge Runtime to version 1.6.6
Notable changes:
* CPU time restriction is enforced locally, so users can simulate them locally and tweak their functions (currently set to 500ms for a function with wall clock time of 5mins)
* All function invocations will show the CPU time it used.

fix: upgrade to Edge Runtime 1.6.6

---

.goreleaser.yml

Bug fix https://github.com/supabase/cli/issues/1306
- trims paths so that panics don't reveal build paths like `/home/runner/cli/...`
- strips debug symbols from release build for 25% smaller binary size: `-s -w`
- disable cgo explicitly to force static linking when build on linux runner

fix: build statically linked binaries on linux

---

internal/db/start/start.go

Bug fix
`LC_COLLATE` should match hosted platform which is `C.UTF-8`

fix: set lc_collate to c.utf-8

---

api/beta.yaml
cmd/branches.go
cmd/root.go
internal/branches/create/create.go
internal/branches/delete/delete.go
internal/branches/disable/disable.go
internal/branches/get/get.go
internal/branches/list/list.go
internal/branches/update/update.go
internal/gen/keys/keys.go
internal/projects/list/list.go
internal/sso/internal/render/render.go
internal/utils/render.go
pkg/api/client.gen.go
pkg/api/types.gen.go

feature
Add `--experimental` commands for managing preview branches.
- `create Production` enables preview branching
- `get` retrieves branch db connection details
- `list` displays all branches in a table
- `update <uuid> --git-branch main`  updates git branch
- `delete <uuid>` deletes a branch by id
- `disable` disables branching for the project
These new commands would also allow GHA workflows to launch preview branches for each PR.

feat: implement preview branch management commands

---

cmd/db.go
internal/db/push/push.go
internal/db/push/push_test.go
internal/db/reset/reset.go
internal/db/start/start.go

feature
Allows custom roles and seed data to be optionally pushed along with migrations.
```bash
supabase db push --include-roles --include-seed
```
Helps with setting up preview branch on remote project.

feat: add flags to push custom roles and seed data

---

internal/utils/misc.go

I don't know if it is that simple, but tests seem to pass and nothing showed up during casual usage ¯\_(ツ)_/¯ 
This release includes pg_graphql v1.2.3 which enables computed fields to return `setof`, that is a essential feature for one to many relations in general (we're using it for i18n)
https://supabase.github.io/pg_graphql/computed_fields/#to-many

fix(db): bump pg15 release to 15.1.0.103

---

docs/supabase/db/dump.md

A small typo fix in the command description.
There is a typo.
One less typo!

fix: typo in supabase db dump description

---

internal/functions/serve/templates/main.ts
internal/utils/misc.go

Bumps Edge Runtime image to 1.8.1 and also increases the CPU limit.

fix(functions): bump edge runtime 181

---

internal/start/start.go

Bug fix
https://github.com/supabase/supabase/issues/16100

fix(auth): email urlpaths using kong container name instead of `localhost`

---

package.json

ci update
Adds a new hotfix channel because `npm publish --tag <name>` cannot be a semver string.

chore: update channel name for hotfix branch

---

internal/utils/misc.go

Bumps Logflare version to 1.4.0

bump to logflare to version 1.4.0

---

cmd/db.go
internal/db/push/push.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/db/start/start.go
internal/migration/apply/apply.go
internal/migration/apply/apply_test.go
internal/migration/repair/repair.go
internal/migration/squash/squash.go

https://news.ycombinator.com/reply?id=37075043&goto=item%3Fid%3D37072464%2337075043
> Using supabase migration up would mean moving the latest migration out of the migrations folder, running supabase db reset, moving the file back in and then calling supabase migration up.
Allows resetting database to a specific version. For eg.
- `supabase/migrations/20221014075902_first.sql`
- `supabase/migrations/20221014075903_second.sql`
```bash
$ supabase db reset --version 20221014075902
Resetting local database to version: 20221014075902
...
$ supabase migration up
Applying migration 20230810083342_test_pgsodium.sql...
$ supabase db reset --version 0
glob supabase/migrations/0_*.sql: file does not exist
...
```

feat: support resetting database to a specific version

---

internal/utils/misc.go

chore
Updates studio image to match self-hosted.

fix: bump studio image version to 20230803

---

internal/utils/misc.go

Bug fix
If a column has multiple check constraints, pg-meta returns duplicate entries on `GET /columns` and generated types.
Fix the bug
Fixes https://github.com/supabase/postgres-meta/issues/590

fix: pg-meta returning duplicate columns

---

internal/start/start.go

Bug fix https://github.com/supabase/cli/issues/1083
Studio seems to need a longer time for health check to pass. Changed total wait time from 20s to 30s.

fix: add 10 seconds startup time for studio

---

internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/migration/squash/squash.go

Bug fix https://github.com/supabase/cli/issues/1326
Some commands are missing confirmation when updating remote.
In general, we should prompt for confirmation before updating remote database. The exception is when the command name is explicit, for eg. db push.

fix(db): confirm before resetting remote database

---

internal/utils/misc.go

This PR updates the edge runtime to 1.11.1 image.
Notable changes:
* Uses Deno 1.36
* Experimental support for Node built-ins 
* Enabled `Deno.stdout` or `Deno.isatty`

fix: update edge runtime to 1.11.1

---

cmd/db.go
internal/utils/config.go

deprecation
Local branching is superseded by remote branching.
```bash
supabase --experimental branches <command>
```

chore: add deprecation notice to local branch commands

---

internal/functions/deploy/deploy.go
internal/functions/deploy/deploy_test.go

Bug fix https://github.com/supabase/cli/issues/456
`getFunctionSlugs` should only return valid function slugs. This is so that `deployAll` will skip shared modules.

fix: include only valid function slugs in deploy all

---

internal/start/start.go
internal/utils/docker.go

Bug fix https://github.com/supabase/cli/issues/1403
BitBucket pipeline only support bind mount.
Since we don't need to support backing up volumes in CI pipeline, skip named volumes altogether.

fix: skip volume mounts when running bitbucket pipeline

---

internal/start/start.go
internal/utils/config.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

closes https://github.com/supabase/cli/issues/1198
Adds the following config
- `realtime.enabled` allow disabling realtime service
- `realtime.ip_version` allow binding realtime to IPv4

feat(realtime): support configuring realtime ip version

---

docs/supabase/inspect/db-total-table-sizes.md

We didn't document that system tables are excluded from the `supabase inspect db total_table_sizes` command. Some users use this query to check their db size usage and wonder why it doesn't match up.

chore: note that system tables are not included in table_sizes inspection command

---

internal/db/reset/reset.go
internal/db/reset/reset_test.go

follow up https://github.com/supabase/cli/pull/1392
CI environments do not evaluate to terminal, hence the default value is used without prompting.
This PR allows running `db reset --db-url ...` in CI.

fix: reset prompt defaults to true for CI environments

---

internal/utils/misc.go

* Deno.serve support
* fix for missing `globalThis.addEventListener`

fix: bump edge-runtime to 1.13.1

---

internal/db/diff/diff.go
internal/db/diff/migra.go
internal/db/diff/migra_test.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/db/start/start.go

fixes https://github.com/supabase/cli/issues/1415
fixes https://github.com/supabase/cli/issues/1447
Use the same db health check timeout of 30 seconds everywhere.

fix(db): increase db start timeout to 30s

---

package.json
scripts/postinstall.js

Enabled `node-fetch` proxy support by using `proxy-agent`.
`npm install supabase` fails to run in environments where a proxy is required.
It works fine under proxy environment.
None.

feat: add proxy support to npm install

---

internal/migration/new/new.go

Remove an extra period on new migrations that negatively affects usability in CLI. For example, double clicking will copy an invalid file path, since it has a trailing period.
Period is printed.
Period is removed.
N/A

fix: remove extra period on migration creation

---

internal/db/reset/reset.go
internal/db/start/start.go
internal/start/start.go

Bug fix https://github.com/supabase/cli/issues/1415#issuecomment-1707025589
fixes https://github.com/supabase/cli/issues/1367
- increases database health timeout to accommodate more machine types
- reduces idle cpu usage by increasing health check interval from 2s => 10s 

fix: reduce idle cpu usage with longer health check interval

---

internal/utils/misc.go

Based on latest build from https://hub.docker.com/r/supabase/studio/tags

Bump offline studio version from prod deploy on 120923

---

internal/db/reset/templates/drop.sql

Bug fix https://github.com/supabase/cli/issues/1470
When resetting linked project
- drops non-default extensions first
- drops sequences after tables

fix(db): drop non-default extensions when resetting remote

---

cmd/db.go
cmd/migration.go
cmd/root.go
cmd/services.go
cmd/version.go
internal/link/link.go
internal/link/link_test.go
internal/services/services.go
internal/utils/tenant/client.go
internal/utils/tenant/client_test.go
internal/utils/tenant/gotrue_test.go
internal/version/version.go

closes https://github.com/supabase/cli/issues/1230
```bash
$ supabase services
SERVICE IMAGE      │      LOCAL       │   LINKED
─────────────────────────┼──────────────────┼─────────────
supabase/postgres      │ 15.1.0.103       │ 15.1.0.103
supabase/gotrue        │ v2.92.1          │ v2.92.1
postgrest/postgrest    │ v11.1.0          │ v11.1.0
supabase/realtime      │ v2.10.1          │ -
supabase/storage-api   │ v0.40.4          │ -
supabase/edge-runtime  │ v1.16.0          │ -
supabase/studio        │ 20230912-748fd33 │ -
supabase/postgres-meta │ v0.68.0          │ -
supabase/logflare      │ 1.4.0            │ -
bitnami/pgbouncer      │ 1.20.1           │ -
darthsim/imgproxy      │ v3.8.0           │ -
```

feat: add services command for listing service versions

---

internal/utils/misc.go

Updates edge-runtime to 1.18.1:
- Adds support to `Deno.version`
- [perf improvement] creating user workers are non-blocking now.

fix: upgrade edge-runtime to 1.18.1

---

internal/functions/new/templates/index.ts

update template of new function as `serve` from `http/server.ts` is deprecated.
`import { serve } from "https://deno.land/std@0.201.0/http/server.ts";` is being used to serve 
`Deno.serve()` will be used for functions as it's what recommended from Deno

fix: update functions template to remove deprecated serve

---

internal/utils/credentials/store.go

fixes https://github.com/supabase/cli/issues/1506
fixes https://github.com/supabase/cli/issues/1483
fixes https://github.com/supabase/cli/issues/899
This means that db password won't be saved. Access token will be written to a file.

fix: disable keyring on wsl

---

internal/utils/misc.go

Bump PG15 image to [latest](https://github.com/supabase/postgres/releases) v15.1.0.117.
Required to use pgvector v0.5.0 locally.

fix(db): bump PG15 to 15.1.0.117

---

internal/link/link.go
internal/link/link_test.go
internal/utils/config.go
internal/utils/misc.go
internal/utils/tenant/client.go

closes https://github.com/supabase/cli/issues/491
Now that initial schema is removed, it is possible to use arbitrary pg15 image for local development. This PR links remote database image version to match local dev.

feat: sync database version with remote pg15 project

---

internal/db/dump/dump.go

Bug fix
We should include user data from extension managed schemas. This is useful for migrating to new supabase project.
- `pgsodium` and `vault` for encrypted columns and values
- `net` for http request queue and history
- `cron` for cron jobs and run history
- `supabase_functions` for webhooks invocation history
Support for `postgins_tiger_geocoder` and `timescaledb` are still experimental. Users can try it by dumping them separately via `supabase db dump --schema tiger_data` flag.

fix: include more schemas in data only dump

---

internal/utils/misc.go

fix: bump edge-runtime to 1.20.1

---

internal/functions/serve/templates/main.ts
internal/utils/misc.go

This PR updates Edge Runtime dependency to 1.20.2. Also, updates the Edge Function error responses to return same status codes & messages as production.
Currently if a function experience a boot error or runs into a resource limit it returns a generic 500 error response. This differs from production, which returns specific error responses (eg: 546 status code for resource limit errors)
New behavior brings local dev in parity with production by returning the same error statuses and messages.

Return same error responses as production for Edge Functions

---

cmd/db.go

docs update
As a first time user and CLI noob, it took me a bit to figure out the list of schema had to be comma separated, so I thought it would be useful to add this bit to the docs. This is consistent with other parts of the docs such as the description of domains flag in the sso add command.

chore(docs): clarify need for commas in schema flag of db commands

---

internal/init/templates/.gitignore

We recommend to use `.env` file to manage Edge Functions secrets in our [guide](https://supabase.com/docs/guides/functions/secrets#production-secrets), so thought it would make sense to add it to the default .gitignore file.

fix: adds .env to initial .gitignore file

---

cmd/functions.go
cmd/root.go

Bug fix
Sets cancellable context in root command. Currently context is only cancellable if run with `--debug` flag.

fix: enable cancel context for management apis

---

internal/start/start.go

Configures the `GOTRUE_JWT_ISSUER` environment variable to point to the local setup's Auth URL. This makes it easy to identify where the JWT came from and makes it easy to to use other tools like pg_graphql, graphbase and others that require the `iss` claim to be present.

feat: expose issuer in local JWTs

---

internal/link/link.go

Bug fix https://github.com/supabase/cli/issues/1599
Since the error is non-fatal, only emit the log when debug flag is on.

fix: log service link error only on debug flag

---

internal/db/start/start_test.go
internal/utils/docker.go

relates to #1581 
Deletes custom network by label.

fix: prune local docker network by label

---

internal/utils/misc.go

Bumps edge-runtime to 1.22.3. Main changes are:
* Upgrade to Deno 1.37.1

fix: bump edge-runtime to 1.22.3

---

internal/utils/denos/extract.ts

This PR fixes the issue with downloading edge functions. Looks like the function payload is now automatically decompressed (from brtoli), so no longer need to decompress payload manually (couldn't find the change that caused the behavior change though)

fix: no need to decompress buffer when downloading functions

---

internal/utils/misc.go

Fixes https://github.com/supabase/cli/issues/878
Depends on https://github.com/supabase/cli/pull/1633

ref: Provide better missing project id error message

---

internal/utils/misc.go

Bump edge-runtime to 1.22.4 (updates to Deno 1.37.2)

fix: bump edge-runtime to 1.22.4

---

README.md

This is a readme update to include pkgx package manger install instructions
I created the build script from source [here](https://github.com/pkgxdev/pantry/blob/0a870774137cde2e1e9a6fb0bd63064077127bf3/projects/supabase.com/cli/package.yml)

chore: add pkgx to install options in readme

---

internal/utils/misc.go

Bump up Realtime to version 2.25.27

fix: Bump up Realtime to version 2.25.27

---

internal/start/start.go
internal/start/start_test.go

```
fix: adding gotrue expected format to testotp env
* Removing previous json encoding
* Adding a new method that outputs map as key1:value1,key2:value2,...
* Adding new test for the method above
```
This PR aims to address what has been pointed in https://github.com/supabase/gotrue/issues/1293.
In short:
* the cli was encoding a `map[string]string` as a json string
* this string was the value for a env that gotrue was trying to use to generate the same map
* the library gotrue is using expected `key1:value1,key2:value2,...` instead of json
The current behavior generates a json string as the value for the `GOTRUE_SMS_TEST_OTP` environment variable that gotrue is supposed to use.
To attest this:
```bash
go run . init
go run . start
export CONTAINER=$(docker container ls | grep gotrue | …
```

fix: adding gotrue expected format to GOTRUE_SMS_TEST_OTP env

---

internal/start/start.go
internal/utils/config.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

Use SMS template from `config.toml` instead of hardcoded string
Uses the hardcoded template for sending SMS otp
Uses template from env for sending SMS OTP message
gotrue repo already has the env, let me know if any other changes are required
https://github.com/supabase/gotrue/blob/93e5f82ced83c08799ce99020be9dea82fc56d24/example.env#L183

feat: use sms template from config.toml

---

internal/utils/misc.go

Bump up Realtime to 2.25.35
Fixes seeding issues:
https://github.com/supabase/realtime/pull/742
https://github.com/supabase/realtime/pull/739
https://github.com/supabase/realtime/pull/736

fix: Bump up Realtime to 2.25.35

---

internal/projects/list/list.go

In this PR, I added the 'REFERENCE' word in the projects list so that it becomes easy to know what is ID actually because when I was trying to delete the project, I was not sure what to enter in the ID. 
The ID could be anything but it's good to mention that the reference ID is required.

chore: added the 'REFERENCE' word in the projects list so that it becomes easy to know the ID

---

cmd/functions.go
cmd/login.go
cmd/root.go
internal/login/login.go
internal/login/login_test.go
test/login_test.go

Adds automated login flow, which uses the browser session to authenticate and generate a new token, which is used in the cli `login` command.
```
Usage:
supabase login [flags]
Flags:
-h, --help           help for login
--name string    Name that will be used to store token in your settings, defaults to built-in token name generator
--no-browser     Do not open browser automatically
--token string   Use provided token instead of automatic login flow
```
RFC: https://www.notion.so/supabase/RFC-Automatic-browser-based-CLI-login-flow-fc4f91fc7e7f4f168d2da6192841dcec?d=d8c9bcbe826c4665a89f9240d0854a36
API changes: https://github.com/supabase/infrastructure/pull/15529
Studio changes: https://github.com/supabase/supabase/pull/18641

feat: Add automatic login flow support

---

internal/storage/client/buckets.go

Bug fix https://github.com/supabase/cli/issues/1674

fix: bucket reponse should be typed as string array

---

internal/login/login.go
internal/login/login_darwin.go
internal/login/login_windows.go
internal/login/login_xdg.go

Right now it only worked in environments that had `open` command.

fix: Use skratchdot/open-golang to open login url in the browser

---

internal/functions/serve/templates/main.ts
internal/utils/misc.go

This upgrade introduces soft and hard limits for CPU time.
* An isolate can handle multiple requests for a function. It will run till the wall clock limit (set to 400s).
* When an isolate reaches soft limit it will be retired, which means it won’t handle anymore new requests. But it will run to complete any pending requests until it reaches the CPU time hard limit or wall clock limit (whichever comes first).
* Any new requests will be handled by a newly created isolate.

feat: Upgrade to edge-runtime 1.23

---

cmd/stop.go
internal/stop/stop.go
internal/stop/stop_test.go
internal/utils/config.go
internal/utils/docker.go

feature
closes https://github.com/supabase/cli/issues/1221
- Stop supabase stack from any directory by specifying the local project id
```bash
supabase stop --project-id cli-demo
```
- Suggest using a different port when bind fails
```bash
$ supabase db start
Starting database...
Error response from daemon: driver failed programming external connectivity on endpoint supabase_db_cli (7a755ba6e40a10271d24e270728bcb4982cea5d2c7206b6ab17f795630b638f4): Bind for 0.0.0.0:54322 failed: port is already allocated
Try stopping the running project with supabase stop --project-id cli-demo
Or configure a different db port in supabase/config.toml
exit status 1
```

feat: support stopping supabase without config file

---

internal/functions/deploy/deploy.go

Bug fix
Path inside container should always be unix style.

fix: entrypoint path for functions deploy on windows

---

internal/utils/deno.go

Bug fix https://github.com/supabase/cli/issues/1739
Preserves imported file extension so that deno is happy.

fix: preserve file extension when bundling import map paths

---

internal/db/dump/templates/dump_data.sh
internal/utils/docker.go

Bug fix https://github.com/supabase/cli/issues/1420
Since data only dump is an exact copy of the database state, we should always disable triggers when restoring.
This setting may not apply to handwritten seed.sql so we don't apply it in code.

fix(db): generate data only dump with disabled triggers

---

internal/db/start/start.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

Bug fix
Text fields should work.
```sql
create extension orioledb;
create table foo (
id int,
name text
) using orioledb;
```

fix: use C collation when launching orioledb

---

.goreleaser.yml

closes https://github.com/supabase/cli/issues/1315
Configure goreleaser to build for windows surface 9.

fix: support arm64 build for windows surface

---

internal/utils/config.go
internal/utils/config_test.go

Bug fix
Tedious to rotate `anon` and `service_role` keys as they need to be statically generated.
Allows defining a single `SUPABASE_AUTH_JWT_SECRET` env var to rotate JWT tokens.

fix: generate anon and service keys from custom jwt secret

---

api/beta.yaml
internal/link/link.go
internal/projects/create/create_test.go
internal/utils/config.go
internal/utils/connect.go
internal/utils/connect_test.go
internal/utils/flags/db_url.go
internal/utils/misc.go
pkg/api/client.gen.go
pkg/api/types.gen.go

supersedes https://github.com/supabase/cli/pull/1730
Since pgbouncer is being deprecated, use supavisor connection string when available.

feat: use pooler connection string when available

---

internal/utils/misc.go

Bug fix: https://github.com/supabase/cli/issues/1767
Update default PostgREST version and mirror to ECR.

fix(api): bump postgrest image to 12.0.1

---

internal/functions/deploy/deploy.go

Bug fix https://github.com/supabase/cli/issues/1774
Bind mounts need to be world writable for containerized processes to save output file.

fix(functions): update bundle output directory permission

---

internal/db/diff/migra.go
internal/db/diff/migra_test.go

Bug fix https://github.com/supabase/cli/issues/1721
Print warnings when drop statements are generated.

fix(diff): warn about generated drop statements

---

internal/db/diff/migra.go
internal/db/diff/migra_test.go
internal/db/dump/dump.go
internal/db/lint/lint.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/utils/misc.go

closes https://github.com/supabase/cli/issues/1671
Users typically want to restore the migration history table as well.

feat: include migration history in db dump

---

internal/start/start.go
internal/utils/config.go
internal/utils/misc.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

Bug fix https://github.com/supabase/cli/issues/1784
Allows configuring max header length in config.toml.

feat: allow configuring max header length for realtime

---

.github/workflows/mirror-image.yml
.github/workflows/pg-prove.yml

chore
Add ci workflows for publishing [pg_prove image](https://hub.docker.com/r/horrendo/pg_prove) with support for arm64 build.

chore: add ci workflows for publishing pg_prove image

---

.github/workflows/mirror.yml

ci
Reuse https://github.com/supabase/cli/blob/main/.github/workflows/mirror-image.yml
Ran successfully https://github.com/supabase/cli/actions/runs/7344887371

chore: reuse mirror image workflow

---

scripts/postinstall.js

relates to https://github.com/supabase/cli/issues/1769
Reuse the same tcp connection for downloading multiple files from github release.

fix: keep alive tcp connection when downloading binary

---

internal/utils/misc.go

With the latest deploy, GoTrue is now on v2.130.0 
Looks like no sql statements are involved. Diff: https://github.com/supabase/gotrue/compare/v2.125.1...v2.130.0

feat: update auth version to v2.130.0

---

internal/db/diff/templates/migra.sh
internal/utils/misc.go

Bug fix
Pin migra image version instead of using pip install every time.

fix(diff): pin migra image to version 3.0.1663481299

---

internal/functions/serve/templates/main.ts

Updates Edge Functions CPU limits to match to the limits currently set in the hosted version.

fix: match CPU limits to the hosted version

---

cmd/gen.go
internal/gen/types/typescript/typescript.go
internal/gen/types/typescript/typescript_test.go

feature
When running `supabase gen types typescript` with `--db-url`, we can't check which PostgREST version the client lib will query against, and unfortunately PostgREST v10 has a breaking change which changes the format of a nested table for one-to-one relationships from `T[]` to `T | null`. The generated types can only support one or the other.
For the hosted platform and local dev this isn't an issue since we can detect the PostgREST version and switch between the 2 formats accordingly, but for `--db-url` we need this to be configurable.
Add `--postgrest-v9-compat` flag, which can only be used in conjunction with `--db-url`.

feat(typegen): support `--postgrest-v9-compat` for `--db-url`

---

internal/db/start/start.go
internal/db/start/start_test.go
internal/start/start.go
internal/stop/stop.go
internal/stop/stop_test.go
internal/testing/apitest/helper.go
internal/utils/docker.go

Bug fix
If there's a local backup volume and db start encounters an error, the backup volume is deleted.
If backup volume exists, failed start should not remove them. Otherwise if it's a fresh start, delete any backup volume.
Also in this PR:
- adds project label to named volumes by creating them explicitly via docker api
- reuses remove all method in stop command
- cleans up dead code for docker add file

fix(db): failed start should not remove backup volume

---

internal/utils/misc.go

We're upgrading GoTrue to v2.132.3 and we should update CLI to reflect that. We should probably also update self-hosted. The deploy for the last region is in progress so we should probably only merge this after GMT+8 midnight

feat: upgrade GoTrue CLI version to 2.132.3

---

internal/db/test/test.go

Bug fix https://github.com/supabase/cli/issues/1830
BitBucket pipeline enables user namespace for docker daemon, which doesn't allow host network mode. https://community.atlassian.com/t5/Bitbucket-articles/Changes-to-make-your-containers-more-secure-on-Bitbucket/ba-p/998464
When connecting to local database, join the existing custom network instead.

fix(test): support bitbucket pipeline for pgtap tests

---

internal/db/diff/migra_test.go
internal/db/push/push_test.go
internal/link/link_test.go
internal/migration/apply/apply_test.go
internal/migration/history/history.go
internal/migration/repair/repair.go
internal/migration/repair/repair_test.go
internal/migration/squash/squash.go
internal/migration/squash/squash_test.go
internal/testing/pgtest/helper.go

Bug fix https://github.com/supabase/cli/issues/1428
Since migration history table is now dumped by db pull, we have to insert into the history table after applying user's migration to accommodate for future schema changes to the history table.

fix(db): create history table before inserting migration

---

cmd/root.go
cmd/start.go
internal/services/services.go
internal/start/start.go
internal/start/start_test.go

relates to https://github.com/supabase/cli/issues/1617
It's not intuitive how to update local service versions.
Show suggestion when service images are found to be out of date.
```bash
$ supabase start
You are running outdated service versions:
supabase/postgres:15.1.0.147 => 15.1.0.155
postgrest/postgrest:v12.0.1 => v12.0.2
Run supabase link to update them.
Started supabase local development setup.
```

feat: check local service versions on supabase start

---

internal/start/start.go
internal/utils/config.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

Allow us to test manual linking in localhost
[Please link any relevant issues here.](https://github.com/supabase/gotrue/pull/1317#issuecomment-1892937708)
It allows you to specify config.toml value that lets us test manual linking locally

fix: add enable manual linking option to auth config

---

internal/db/diff/migra.go
internal/db/start/start.go
internal/migration/squash/squash.go
internal/start/start.go
internal/start/templates/kong.yml
internal/status/status.go
internal/utils/config.go
internal/utils/connect.go
internal/utils/flags/db_url.go
internal/utils/misc.go

Bug fix https://github.com/supabase/cli/issues/1603
`supabase start` fails in GitLab CI because `docker:dind` does not expose service ports on localhost.
Make local hostname configurable so that docker daemon address can be used instead of 127.0.0.1.
This change also supports use cases where docker daemon is installed on a remote machine.

fix(db): make local hostname configurable for docker-in-docker

---

internal/utils/misc.go

Edge Runtime 1.31.1 contains various stability fixes on CPU & Wall clock time enforcement. Check the EdgeRuntime releases for more details - https://github.com/supabase/edge-runtime/releases/tag/v1.31.0

fix: upgrade edge-runtime to 1.31.1

---

internal/db/dump/dump.go

Bug fix https://github.com/supabase/cli/issues/1844
When dumping data to seed.sql, migration history is included by default. This breaks when seeding local database.
Let CLI manage writing to `schema_migrations` table instead.

fix(db): do not dump migration history entries by default

---

internal/db/pull/pull.go

Bug fix https://github.com/supabase/cli/issues/1840
First pull always should always be a full pg_dump for integrity. To avoid managed schemas from being included in the dump, suggest db pull again to diff auth and storage policies.

fix(db): suggest diffing managed schemas after first pull

---

internal/utils/connect.go

fix(db): parse pooler connection string more safely

---

api/beta.yaml
cmd/projects.go
cmd/restrictions.go
internal/projects/create/create_test.go
internal/restrictions/get/get.go
internal/restrictions/update/update.go
internal/restrictions/update/update_test.go
pkg/api/client.gen.go
pkg/api/types.gen.go

feature https://www.notion.so/supabase/support-ipv6-network-restrictions-3b6a98b2c2da40e4a76ca3899145b2f7?pvs=4
Support IPv6 addresses as arguments for `--db-allow-cidr` flag.

feat: support IPv6 CIDR for network restrictions

---

internal/db/start/start.go

Bug fix https://github.com/supabase/cli/issues/1877
`DB_INSTALL_ROLES` is introduced in storage version 0.46.3. Set to false for backwards compatibility.
Verified locally with `supabase start`

fix(storage): default db_install_roles to false for backwards compat

---

.github/workflows/install.yml
scripts/postinstall.js

related to https://github.com/supabase/cli/issues/1769
add yarn berry to ci check matrix

chore: add yarn berry to ci check

---

cmd/db.go
cmd/init.go
internal/db/dump/dump.go
internal/db/dump/dump_test.go
internal/db/remote/commit/commit.go

closes https://github.com/supabase/cli/issues/1772
```
supabase db dump --data-only --exclude auth.audit_log_entries,auth.mfa_amr_claims
```

feat(migration): exlude custom schema.table from data-only dump

---

internal/db/dump/dump.go
internal/db/dump/templates/dump_schema.sh
internal/db/reset/reset.go
internal/utils/misc.go

reverts https://github.com/supabase/cli/pull/1783
Too many errors pulling the migration history table https://github.com/supabase/cli/issues/1428#issuecomment-1911563752
Revert back to the old default of not including history schema. We will recommend dumping `supabase_schema.schema_migrations` separately in docs.
```bash
$ supabase db dump -s supabase_schema
Dumping schemas from remote database...
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
CREATE SCHEMA IF NOT EXISTS "supabase_migrations";
ALTER …
```

fix: do not dump migration history schema by default

---

internal/db/dump/dump.go
internal/db/dump/templates/dump_schema.sh

Bug fix https://github.com/supabase/cli/issues/1428#issuecomment-1913329636
`'*'` was double escaped to `'\''*'\''` by bash.
Always set `--schema` flag so we don't need to optionally pass in `--extension` flag to pg_dump.

fix: prevent wild card pattern from double escaped

---

internal/start/start.go
internal/utils/misc.go

fix(storage): bump storage version to v0.46.4

---

internal/utils/misc.go

Bumps Edge Runtime to 1.32.4 (check Edge Runtime [release notes](https://github.com/supabase/edge-runtime/releases) for details)

fix: bump edge runtime to 1.32.4

---

internal/utils/misc.go

This updates Edge Runtime to use Deno 1.39.2

fix: bump to edge-runtime 1.33.0

---

internal/utils/connect.go
internal/utils/flags/db_url.go

Bug fix https://github.com/supabase/cli/issues/1625
Prefer using pooler url when available because some hosts cannot resolve IPv6.

fix: use pooler url for all docker commands

---

cmd/migration.go
internal/db/pull/pull.go
internal/db/remote/commit/commit.go
internal/migration/history/history.go
internal/migration/repair/repair.go
internal/migration/repair/repair_test.go

feature
- allows multiple versions to be applied / reverted together
```bash
$ supabase migration repair --status reverted 0 ... 2
Connecting to remote database...
Repaired migration history: [0 1 2] => reverted
Finished supabase migration repair.
Run supabase migration list to show the updated migration history.
```
- prompts to repair the whole history if no version is specified
```bash
$ supabase migration repair --status applied
Do you want to repair the entire migration history table to match local migration files? [y/N] y
Connecting to remote database...
Finished supabase migration repair.
Run supabase migration list to show the updated migration history.
```

feat(migration): support batch repair of migration history

---

internal/functions/serve/templates/main.ts
internal/utils/misc.go

Show Edge Runtime & Deno version at start of `supabase functions serve`
It's hard to find the exact Edge Runtime & Deno version when running Edge Functions locally.
Check screenshot below

fix: show edge-runtime & deno version on start

---

internal/utils/misc.go

Updates service studio new version to [20240205-b145c86](https://hub.docker.com/layers/supabase/studio/20240205-b145c86/images/sha256-5434f89c18caf7bdc070f411abbc07dcb652113f53f86dcfbe816d02d6013ab9?context=explore).

feat: bump studio version to 20240205

---

internal/utils/config.go

Bug fix https://github.com/supabase/cli/issues/1923
Did not account for minor version.
Use semver package for comparison.

fix: use semver package for image version comparison

---

internal/utils/misc.go

Upgrade to Edge Runtime 1.34.1 (compatible with Deno 1.40.3)

fix: bump edge runtime to 1.34.1

---

internal/gen/types/typescript/typescript.go

Bug fix https://github.com/supabase/cli/issues/1945

fix(typegen): pass down sslmode param to pgmeta

---

internal/utils/misc.go

fix: bump edge-runtime to 1.36.1

---

internal/db/diff/diff_test.go
internal/db/lint/lint_test.go
internal/db/pull/pull_test.go
internal/db/push/push.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/db/test/test.go
internal/db/test/test_test.go
internal/migration/apply/apply_test.go
internal/migration/list/list.go
internal/migration/list/list_test.go
internal/migration/squash/squash.go
internal/migration/squash/squash_test.go
internal/migration/up/up.go
internal/migration/up/up_test.go
internal/utils/connect.go

Bug fix https://github.com/supabase/cli/issues/1956
If user specifies `--db-url` flag, always treat it as a remote database.

fix: always treat db-url flag as remote database

---

internal/gen/types/typescript/typescript.go
internal/start/start.go
internal/utils/misc.go

Bug fix https://github.com/supabase/postgres-meta/issues/719
Updates `postgres-meta` to 0.77.2 for ssl support.

fix(typegen): support db-url that require ssl mode

---

internal/utils/misc.go

fix: bump edge-runtime to 1.36.5

---

cmd/gen.go
cmd/stop.go
internal/gen/types/typescript/typescript.go
internal/gen/types/typescript/typescript_test.go
internal/utils/flags/db_url.go
internal/utils/misc.go

feature
```bash
$ supabase gen types typescript
Select a project:
>  1. <redacted> [name: <redacted>, org: supabase, region: us-west-1]
```

feat: prompt for project id when running typegen

---

internal/utils/misc.go

fix: bump edge-runtime to 1.36.7

---

internal/db/dump/templates/dump_schema.sh

Remove comments in extensions
Bug fix https://github.com/supabase/cli/issues/1328
Every dump does not include the comments for tables, columns, functions, etc.
The db dump includes the comments for tables, columns, functions, etc. but not for the extensions. The extension is enabled by dashboard user and does not need to change the comment about the extension itself.
If you use the supabase cli as a backup solution for schema, data and roles data like it is described in [Supabase Doc - Automated backups using GitHub Actions](https://supabase.com/docs/guides/cli/github-action/backups) and you have setup a lot of comments for tables, functions etc. You will loose these comments, they are never included in the schema.
I removed the `--no-comments` flag in template `dump_schema.sh` because of …

fix: dont loose comments when dumping schema

---

internal/db/push/push.go
internal/db/reset/reset.go
internal/migration/repair/repair.go

related https://github.com/supabase/cli/issues/1976
```bash
$ supabase db push
Connecting to remote database...
Do you want to push these migrations to the remote database?
• 0_schema.sql
• 1_test.sql
[Y/n] n
context canceled
exit status 1
```

fix: confirm pushing migrations to remote database

---

internal/utils/docker.go

Bug fix https://github.com/supabase/cli/issues/1982
Analogous to `docker volume prune --all --filter <key=value>`

fix: prune volumes with all flag

---

cmd/gen.go
internal/gen/types/typescript/typescript.go
internal/gen/types/typescript/typescript_test.go
internal/utils/misc.go

Bug fix https://github.com/supabase/cli/pull/1965#issuecomment-1962237151
Fixes regression introduced by previous refactoring.

fix: check for sslmode explicitly when generating types

---

internal/start/start.go
internal/utils/config.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

Allows users to bring their own OpenAI API key into the Supabase Studio so Supabase AI works when developing locally too.
When using the Supabase AI fields locally, one gets an error message which is just the HTML of the standard error page. Also, the container throws an error that the OpenAI key cannot be found.
When specifying the `OPENAI_API_KEY` while starting Supabase locally, it should now pass it through the config into the container as an env variable.
Further ideas for improvement:
- If accepted, should add this to the docs somewhere so people know where and how to add their OpenAI keys
- It would really be great if `supabase start` would also read the `.env` file (also for social auth secrets)
- Show a better error message when using the AI without the key (maybe pointing to …

feat: enable Supabase AI during local development

---

internal/start/templates/kong.yml
internal/utils/misc.go

Adds REST routes to CLI so users can call Broadcast endpoint and in the future handle their Channels.
We were only supporting Websockets at the moment which means users could not use the HTTP Broadcast approach
Opened up routes for Realtime API to be accessible via HTTP requests
Test after the change:

fix: Add Realtime REST routes to CLI

---

internal/start/start.go
internal/utils/misc.go

This PR bumps the Studio image to the latest one. It also removes `SUPABASE_REST_URL` since it's not used anywhere in the studio.

fix: Bump studio to 2024-03-01

---

internal/db/diff/diff_test.go
internal/db/push/push_test.go
internal/migration/apply/apply.go
internal/migration/apply/apply_test.go
internal/migration/repair/repair.go
internal/migration/repair/repair_test.go
internal/migration/squash/squash.go
internal/migration/squash/squash_test.go

Bug fix
Running alter table after actual migration may lead to deadlock.
Update migration history schema before running mgirations.

fix: update migrations history separately from applying

---

internal/gen/types/typescript/typescript.go
internal/link/link.go
internal/link/link_test.go
internal/migration/apply/apply.go
internal/migration/history/history.go
internal/migration/repair/repair.go
internal/migration/squash/squash.go
internal/testing/pgtest/helper.go

Bug fix
Adds lock timeout when altering `schema_migrations` table.

fix: set lock timeout when migrating history schema

---

internal/db/diff/diff.go
internal/migration/squash/squash.go
internal/migration/squash/squash_test.go
internal/migration/squash/testdata/after.sql
internal/migration/squash/testdata/before.sql
internal/migration/squash/testdata/diff.sql

Bug fix https://github.com/supabase/cli/issues/1493
Account for managed schema changes by dumping before and after migrations.

fix: squash auth and storage schema changes

---

internal/db/pull/pull.go
internal/utils/credentials/store.go

Bug fix https://github.com/supabase/cli/issues/2005

fix: disable keyring when exec binary is not found

---

internal/utils/misc.go

https://github.com/supabase/postgres-meta/compare/v0.79.5...v0.79.9
Includes https://github.com/supabase/postgres-meta/commit/3b6c4aaef77444bf947fb9a05a62f8a2bc756298 which affects typegen

fix: pg-meta v0.79.9

---

internal/utils/connect.go

Bug fix https://github.com/supabase/cli/issues/2077
Since CLI commands are short lived, one off commands, there's no reason to use transaction mode.

fix: always use session mode when connecting to pooler

---

internal/db/dump/dump.go
internal/db/dump/templates/dump_schema.sh
internal/migration/list/list.go

Bug fix https://github.com/supabase/cli/issues/1493#issuecomment-1994535314

fix: include publication in db dump

---

internal/utils/misc.go

Bump edge runtime to 1.41.2 (includes `Supabase.ai` API changes + better memory handling in isolates)

fix: bump edge runtime to 1.41.2

---

internal/storage/cp/cp.go

Bug fix
`supabase storage cp --workdir /tmp ss:///test .` downloads files to `/tmp` instead of the current directory.
Respect the relative path passed in from cli arg.

fix(storage): resolve relative path from cwd

---

cmd/login.go
internal/bootstrap/bootstrap.go
internal/login/login.go
internal/login/login_test.go
internal/migration/new/new.go

Bug fix https://github.com/supabase/cli/issues/1054
Order of token parsing should be flag > env > stdin.

fix: reuse common login flows

---

cmd/bootstrap.go
internal/bootstrap/bootstrap.go
internal/bootstrap/bootstrap_test.go

fix: suggest npm commands after bootstrap

---

internal/bootstrap/bootstrap.go

Bug fix
Bootstrap project may timeout waiting to become active healthy.
Sepearate database and pooler status checks so that bootstrap is more robust against timeouts.
```
Linking project...
Retry (1/8): Linking project...
Checking project health...
Retry (1/8): Checking project health...
Retry (2/8): Checking project health...
Retry (3/8): Checking project health...
Retry (4/8): Checking project health...
Retry (5/8): Checking project health...
Connecting to remote database...
Retry (1/8): Connecting to remote database...
Retry (2/8): Connecting to remote database...
Retry (3/8): Connecting to remote database...
Retry (4/8): Connecting to remote database...
Retry (5/8): Connecting to remote database...
Retry (6/8): Connecting to remote database...
Remote database is up to date.
To start …
```

fix: check project health on bootstrap

---

internal/utils/misc.go

Updates edge-runtime to 1.41.3, which fixes a bug prevented some npm modules from working.

fix: bump edge runtime to 1.41.3

---

internal/utils/credentials/store.go

Bug fix https://github.com/supabase/cli/pull/1509#issuecomment-2030225608
Check for string either `WSL` or `Microsoft`.

fix: disable keyring on WSL1

---

internal/utils/misc.go

Upgrade auth version to 2.145.0 as we are nearing the end of the deploy. A follow up PR will be made to add relevant env vars.

feat: bump auth version 2.145.0

---

internal/functions/deploy/deploy.go
internal/functions/download/download.go

Bug fix https://github.com/supabase/cli/issues/1912
If only `--entrypoint` flag is used, the eszip will be unbundled as a single `index.ts` file
```
edge-runtime bundle --entrypoint functions/hello/index.ts --output /tmp/output.eszip
edge-runtime unbundle --eszip /tmp/output.eszip --output .
```
But if an `--import-map` flag is also used, for eg.
```
edge-runtime bundle --entrypoint functions/hello/index.ts --import-map import_map.json --output /tmp/output.eszip
edge-runtime unbundle --eszip /tmp/output.eszip --output .
```
The entrypoint file will be extracted relative to the import map:
```
import_map.json
functions/hello/index.ts
```
It's too complicated to maintain the original bundled file structure when extracting. So we will simply extract the eszip folder as it is.
Add any other …

fix(functions): unbundle to slug directory by default

---

api/beta.yaml
internal/bootstrap/bootstrap.go
pkg/api/types.gen.go

Adds the `template_url` value when the `bootstrap` command is executed, for tracking which template was used to create a project.
I've manually edited the OpenAPI file, as it appears the latest platform generated OpenAPI renames `CreateProjectBody` to `V1CreateProjectBody`.
Do not merge until the API is deployed.

feat: add `template_url` param to `bootstrap`

---

internal/db/diff/diff_test.go
internal/db/pull/pull_test.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/inspect/bloat/bloat.go
internal/inspect/blocking/blocking.go
internal/inspect/cache/cache.go
internal/inspect/calls/calls.go
internal/inspect/index_sizes/index_sizes.go
internal/inspect/index_usage/index_usage.go
internal/inspect/locks/locks.go
internal/inspect/long_running_queries/long_running_queries.go
internal/inspect/outliers/outliers.go
internal/inspect/queries.go
internal/inspect/replication_slots/replication_slots.go
internal/inspect/role_connections/role_connections.go
internal/inspect/seq_scans/seq_scans.go
internal/inspect/table_index_sizes/table_index_sizes.go
internal/inspect/table_record_counts/table_record_counts.go
internal/inspect/table_sizes/table_sizes.go
internal/inspect/total_index_size/total_index_size.go
internal/inspect/total_table_sizes/total_table_sizes.go
internal/inspect/unused_indexes/unused_indexes.go
internal/inspect/vacuum_stats/vacuum_stats.go
internal/utils/misc.go

Feature/Fix: moving queries for inspect to the root `inspect` module and removing Supabase schemas from queries
Queries are within the command and show results from Supabase schemas that could cause concern or make the user take actions on schemas they do not own
- Queries moved into a single place (could be further developed to template similar queries)
- Supabase schemas removed from relevant queries
- Explanation of hit rates added to `cache-hit` command and a column explains whether action might be needed

fix: exclude supabase managed schemas from inspect subcommand

---

cmd/bootstrap.go
internal/bootstrap/bootstrap.go
internal/bootstrap/bootstrap_test.go
internal/projects/create/create.go

supersedes https://github.com/supabase/cli/pull/2130

fix: suggest bootstrap start command from template

---

docs/supabase/migration/repair.md

docs update
The example provided with the command `migragrion repair` was showing an output with no issue and thus the example was hard to understand
NA

fix: migration repair example more understandable

---

internal/start/start.go

follow up https://github.com/supabase/cli/pull/2164
Health check now initialises `realtime` schema.

fix: update realtime health check

---

internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

Bug fix https://github.com/supabase/cli/issues/1570
Open smtp port by default so that signup emails can be delivered to inbucket without additional config.

fix: expose inbucket smtp port by default

---

internal/functions/serve/serve.go
internal/utils/deno.go
internal/utils/deno_test.go

Bug fix https://github.com/supabase/cli/issues/1338
- Always use absolute path in generated import map when serving inside edge runtime, because import map must be mounted at `/home/deno` instead of `/home/deno/functions`
- Rewrite windows path separator to unix for mounting in container.
- Avoid duplicate mount point when both `--import-map` flag and `functions/import_map.json` are used.

fix(functions): always resolve absolute path in container

---

cmd/branches.go
internal/branches/create/create.go
internal/branches/create/create_test.go
internal/branches/disable/disable.go
internal/branches/list/list.go
internal/utils/console.go

feature
```
$ supabase --experimental branches get
Selected project: zekxecbchaedtrzpqysa
Select a branch:
1. fix-import [5f9b7ee4-5204-4cb5-94b5-3ab2bb8ed2f4]
>  2. fly-branch [8ec676b6-3a8d-4375-b326-1322965ba211]
↑/k up • ↓/j down • / filter • q quit • ? more
```

feat(branch): add persistent flag for project ref

---

internal/utils/misc.go

GoTrue version 2.145.0 has a bug where generating a signup link will fail with "user_not_found", which was fixed in 2.146.0 (https://github.com/supabase/auth/pull/1514). Since 2.145.0 is locked in the CLI, we can't get the bug fix out, and the only fix is to downgrade to an older version.
This PR updates the image to 2.149.0 which is the most recent version as of 2024-04-22 so the signup link generation works again.
The CLI is fixed on GoTrue version 2.145.0 which has a bug related to signup link generation.
The CLI now uses GoTrue version 2.149.0 which does not have a bug related to signup link generation.

fix(auth): update GoTrue Image to avoid signup link generation bug

---

internal/utils/misc.go

Bump up the version for Realtime on self hosted

chore: Bump up the version for Realtime on self hosted

---

internal/db/diff/diff_test.go
internal/db/pull/pull_test.go
internal/db/reset/reset_test.go
internal/utils/misc.go

Bug fix
Ignore `dbdev` schema since it's managed by extension.

fix: add dbdev to schema ignore list

---

internal/db/reset/templates/drop.sql

Adds a fixed order when selecting the types to drop for the `supabase db reset`command.
Currently, the order is not defined and this can lead to errors when dropping types. (More details: https://github.com/supabase/cli/issues/2207)
The types are dropped in a fixed order. The order is the number of type dependencies ascending.
The idea is that "base" types are always dropped before e.g. "array" types which have at least 1 type dependency to its "base" type.

fix: add fixed order when selecting types to drop (fixes issue #2207)

---

cmd/migration.go
internal/migration/fetch/fetch.go
internal/migration/history/history.go

feature
`supabase migration fetch` to download statements in migration history table as local migration files.

feat: support fetching migration history table to files

---

internal/utils/misc.go

fix: bump edge-runtime to 1.46.3

---

internal/utils/misc.go

fix: bump edge-runtime to 1.48.0

---

internal/db/pull/pull.go
internal/db/pull/pull_test.go
internal/db/remote/changes/changes.go
internal/db/remote/commit/commit.go
internal/db/start/start_test.go
internal/start/start_test.go
internal/utils/docker.go

chore: clean up db pull implementation

---

internal/start/start.go
internal/utils/config.go
internal/utils/config_test.go
internal/utils/templates/init_config.test.toml

Adds the corresponding configuration for the `SendSMS` and `SendEmail` HTTP Hooks. Also introduces Secrets for previous hooks - `custom_access_token`, `mfa_verification_attempt` , `password_verification_attempt`
Backend PR (Merged): https://github.com/supabase/infrastructure/pull/17848
Frontend PR (WIP): https://github.com/supabase/supabase/pull/22495

feat: add HTTP hook Secret Configuration

---

internal/debug/postgres.go
internal/inspect/cache/cache.go
internal/inspect/cache/cache_test.go
internal/migration/list/list_test.go
internal/testing/pgtest/mock.go

Bug fix
- Support mocking struct as postgres reply type.
- Fixes an issue where pgconn is not closed by run.

fix: add unit test for cache hit

---

internal/utils/misc.go

fix: bump edge-runtime to 1.49.0

---

internal/utils/misc.go

fix: bump edge-runtime to 1.53.0

---

cmd/bootstrap.go
cmd/root.go
go.mod
go.sum
internal/bootstrap/bootstrap.go
internal/db/push/push.go
internal/db/reset/reset.go
internal/functions/new/new.go
internal/link/link.go
internal/migration/repair/repair.go
internal/utils/misc.go
internal/utils/release.go
internal/utils/release_test.go
tools/bumpdoc/main.go
tools/changelog/main.go
tools/publish/main.go
tools/selfhost/main.go
tools/shared/github.go

closes https://github.com/supabase/cli/issues/2051
```
$ supabase --version
1.0.0
A new version of Supabase CLI is available: v1.167.4 (currently installed v1.0.0)
We recommend updating regularly for new features and bug fixes: https://supabase.com/docs/guides/cli/getting-started#updating-the-supabase-cli
```

feat: suggest upgrade when cli version is outdated

---

internal/db/dump/templates/dump_schema.sh

Bug fix
- `alter foreign data wrapper ... owner to ...` fails due to superuser requirement
- `pgtle` schema may be absent when creating `pg_tle` extension

fix(db): handle fdw and pgtle extension

---

internal/utils/misc.go

fix: bump edge-runtime to 1.53.1

---

internal/start/start.go
internal/utils/config.go
internal/utils/misc.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

Bug fix https://github.com/supabase/cli/issues/1414
Not possible to disable edge runtime from config.toml
Adds `[edge_runtime]` block to config.

fix(config): support disabling edge runtime from toml

---

internal/utils/misc.go

Bump edge-runtime to 1.53.2
* change the status code emitted when an idle timeout occurs for a worker ([#349](https://github.com/supabase/edge-runtime/issues/349)) ([8ff5c47](https://github.com/supabase/edge-runtime/commit/8ff5c479d2deecd043e234277a74d407904bdebb))
* relaxing the condition which can be activated inspector feature ([#348](https://github.com/supabase/edge-runtime/issues/348)) ([0edba27](https://github.com/supabase/edge-runtime/commit/0edba27680e83333f7ea03ba16c17b1943a2a4b1))

fix: bump edge-runtime to 1.53.2

---

internal/init/init.go

chore
```
$ supabase init
failed to create config file: open supabase/config.toml: file exists
Run supabase init --force to overwrite existing config file.
exit status 1
```

chore: suggest init force when config exists

---

internal/utils/misc.go

Bump edge-runtime to 1.53.3
* don't emit `RequestCancelledBySupervisor` when event loop error has been raised ([#350](https://github.com/supabase/edge-runtime/issues/350)) ([e27ffca](https://github.com/supabase/edge-runtime/commit/e27ffcac24577b3b4d6ba7347d042650b8c92f5a))

fix: bump edge-runtime to 1.53.3

---

cmd/functions.go
docs/supabase/functions/serve.md
internal/functions/serve/serve.go
internal/functions/serve/serve_test.go
internal/functions/serve/templates/main.ts
internal/start/start.go
internal/utils/config.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

Feature
closes https://github.com/supabase/cli/issues/2311
closes https://github.com/supabase/edge-runtime/issues/212
This PR introduces several flags to the `supabase functions serve` command to enable the inspector capability of edge-runtime.
See the [doc](https://github.com/supabase/cli/blob/a20368fc36857eb25dae07c93f6c8d23fc2d359c/docs/supabase/functions/serve.md) added to this PR for about these flags.

feat: enable edge runtime inspector feature

---

internal/utils/config.go

closes https://github.com/supabase/supabase/issues/23296
Allows env substitution for `auth.site_url`
```
site_url = "env(MY_ENV)"
```

feat: support loading site url from env var

---

internal/db/reset/templates/drop.sql

Bug fix https://github.com/orgs/supabase/discussions/20722
Should not truncate `auth.schema_migrations` table when resetting.

fix(db): exclude auth schema migrations table from linked reset

---

internal/projects/delete/delete.go
internal/unlink/unlink.go

Bug fix
Not all temp files are cleared when deleting a project.
Refactor to use the same deletion code as unlink.

fix: unlink all temp files when deleting project

---

cmd/bootstrap.go
cmd/link.go

Bug fix https://github.com/supabase/cli/issues/2347
Reuse dbPassword variable to bind pflag.

fix: declare password flag for viper bind

---

internal/start/start.go

Bug fix https://github.com/supabase/cli/issues/2348
Podman parses health check command as space separated strings. This is different from docker where the entire command is treated as one string.
Wraps health check command in quotes so it's treated as one string by podman.

fix: escape health check cmd for podman

---

cmd/root.go
internal/db/diff/migra.go
internal/db/dump/dump.go
internal/db/test/test.go
internal/gen/types/typescript/typescript.go
internal/stop/stop.go
internal/utils/config.go
internal/utils/docker.go

closes https://github.com/supabase/cli/issues/2358
supersedes: https://github.com/supabase/cli/pull/1581
```
supabase start --network-id test-network
```
or 
```
SUPABASE_NETWORK_ID=test-network supabase test db --db-url <conn-string>
```

feat: support custom docker network id

---

cmd/functions.go
docs/supabase/functions/serve.md

Improvement
Adjust `--inspect` flag to be an alias for `--inspect-mode brk` based on Slack discussion.

fix: adjust `--inspect` to be an alias for `--inspect-mode brk`

---

internal/db/test/test.go
internal/functions/deploy/deploy.go
internal/functions/download/download.go
internal/functions/serve/serve.go
internal/start/start.go
internal/utils/deno.go

relates to https://github.com/supabase/cli/issues/265#issuecomment-1832282812
`z` volume option is not supported by podman on macOS because it's an extended filesystem attribute.
```
lsetxattr /Users/.../supabase/functions: operation not supported
```
Since we don't need to share volume between containers, it is safe to remove `z` volume option.

fix: remove z option from docker volume config

---

internal/login/login.go
internal/utils/cloudflare/dns.go
pkg/fetcher/http.go
pkg/storage/buckets.go
pkg/storage/objects.go

Bug fix
Set max retries (90) when waiting for login token, instead of waiting indefinitely for non-404 server error.
Also addresses a memory leak where closing http response reader is deferred on retry until program exit.

fix: set default max retry for auto login

---

internal/bootstrap/bootstrap.go
internal/db/diff/diff.go
internal/db/diff/diff_test.go
internal/db/diff/pgadmin.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/db/start/start.go
internal/login/login.go
internal/migration/squash/squash.go
internal/migration/squash/squash_test.go
internal/sso/internal/saml/files.go
internal/start/start.go
internal/status/status.go
internal/status/status_test.go
internal/stop/stop.go
internal/utils/cloudflare/api.go
internal/utils/config.go
internal/utils/docker.go
internal/utils/tenant/client.go
test/status_test.go
tools/publish/main.go

chore
Difficult to fetch logs when database fails to start.
- Stream database logs to stderr on health check failure.
- Check service status using a single docker api call.

fix: show logs when failing to start database

---

internal/db/start/start.go
internal/services/services.go
internal/start/start.go
internal/utils/config.go
internal/utils/misc.go

closes https://github.com/supabase/cli/issues/1702
Allows pooler and realtime image versions to be overridden locally.
```bash
echo "v2.28.32" > supabase/.temp/realtime-version
echo "1.1.56" > supabase/.temp/pooler-version
```

feat: support custom pooler and realtime image

---

internal/functions/deploy/deploy.go
internal/functions/serve/serve.go
internal/functions/serve/serve_test.go
internal/secrets/set/set.go
internal/utils/config.go
internal/utils/deno.go
internal/utils/deno_test.go

Bug fix https://github.com/supabase/cli/issues/2002
`--env-file` and `--import-map` flags are resolved relative to workdir.
Resolve file path flags relative to current working directory.
Refactor common code paths between deploy and serve.

fix: use env file paths relative to current directory

---

cmd/root.go

Bug fix
Bash completion is sometimes added to ~/.zshrc files resulting in `supabase/.temp/cli-latest` created in every directory where a new shell is launched.
Only writes the version file if there's an existing `supabase` directory.

fix: only write version file if supabase directory exists

---

internal/utils/misc.go

Bump edge-runtime to 1.54.2
* Deno 1.43 upgrade ([aa72f73](https://github.com/supabase/edge-runtime/commit/aa72f7370ebf55bbe647b2b6500995d23ec90272))
* bump rust builder image to `1.78-bookworm` ([#361](https://github.com/supabase/edge-runtime/issues/361)) ([c6313b3](https://github.com/supabase/edge-runtime/commit/c6313b3c59f8553b7a3253873a3cab2021f9ec3e))
* downgrade rust builder image to `rust:1.77.2-bookworm` ([#362](https://github.com/supabase/edge-runtime/issues/362)) ([cb19187](https://github.com/supabase/edge-runtime/commit/cb19187532c948836d6fa0c5c2bd72d14857f104))

fix: bump edge-runtime to 1.54.2

---

internal/status/status.go
internal/status/status_test.go

Bug fix https://github.com/supabase/cli/issues/2419
Docker container name is prefixed with `/`

fix: prefix docker container id with slash

---

internal/functions/deploy/deploy.go
internal/functions/download/download.go
internal/functions/serve/serve.go
internal/utils/deno.go
internal/utils/deno_test.go

Bug fix https://github.com/supabase/cli/issues/1303
Users can provide import map in the following order of precedence
1. `--import-map <path>` flag
2. `[functions.name] import_map = "path"` in config.toml
3. create `supabase/functions/import_map.json`
For compatibility with deno LSP, entries in those import maps should be specified relative to the json file. Hence, we resolve the host paths on creating the `ImportMap` struct.
~When mounting into edge runtime container, relative paths above workdir are resolved to `/home/deno/modules/<hash>` so it doesn't mount in arbitrary levels. Import maps are then rewritten to `/home/deno/import_maps/<hash>.json`. If the host import map path is 3, and it doesn't import from 2 levels up, we use 3 as it is.~
Add any …

fix: import map resolution for all relative paths

---

internal/utils/console.go

Bug fix
Serialises reading from stdin using a mutex so that input can be consumed as needed.

fix: console prompt conflict with bubble tea

---

internal/functions/deploy/deploy.go
internal/functions/serve/serve.go
internal/utils/deno.go

Bug fix https://github.com/supabase/cli/issues/2428
Removes `C:` from docker path on windows.

fix: remove volume name from docker mount path

---

internal/utils/misc.go

Bump edge-runtime to 1.54.3
* include more detailed memory metric in mem check record ([#364](https://github.com/supabase/edge-runtime/issues/364)) ([ac6a0a4](https://github.com/supabase/edge-runtime/commit/ac6a0a42269ef5b60eb37d9962a8582b5676f39c))

fix: bump edge-runtime to 1.54.3

---

internal/utils/misc.go

Bump edge-runtime to 1.54.4
* simplify the shutdown reason due to the memory limit of the event record ([#367](https://github.com/supabase/edge-runtime/issues/367)) ([29d2176](https://github.com/supabase/edge-runtime/commit/29d2176ced4030b4c63c4662973c70b7777f89b0))

fix: bump edge-runtime to 1.54.4

---

internal/start/start.go
internal/utils/config.go
internal/utils/config_test.go
internal/utils/templates/init_config.test.toml
internal/utils/templates/init_config.toml

Some change generated using ChatGPT.
Supabase CLI only works with Inbucket.
Add support for Custom SMTP using Supabase CLI.
Maybe need to iterate so it still supports Inbucket.
```
$ go build -o supabase.exe
$ cp supabase.exe ~/project/node_modules/supabase/bin/supabase.exe
$ cd ~/project
```
Add the following to your `config.toml`:
```
smtp_admin_email = "3ilbi6ee8c@gmail.com"
smtp_host = "smtp.sendgrid.net"
smtp_port = "587"
smtp_user = "apikey"
smtp_pass = "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"
smtp_sender_name = "John Doe"
```
Restart:
```
$ ./node_modules/supabase/bin/supabase.exe stop
$ ./node_modules/supabase/bin/supabase.exe start
```
Try sending a transactional email by inviting an user in Supabase Studio:
```
2024-06-13 11:40:40 …
```

feat(auth): add custom smtp support

---

internal/utils/misc.go

Bump edge-runtime to 1.54.6
* **node:** refer the internal rid correctly ([#373](https://github.com/supabase/edge-runtime/issues/373)) ([88f8b77](https://github.com/supabase/edge-runtime/commit/88f8b77b780b4bc62be221684029c64accbe195e))

fix: bump edge-runtime to 1.54.6

---

internal/functions/serve/serve.go
internal/start/start.go
internal/start/templates/pooler.exs
internal/utils/misc.go

Bug fix https://github.com/supabase/cli/issues/2440
Pooler always recreates tenant on restart.
Check if tenant exists before creating.

fix(pooler): check if tenant exists before creating

---

internal/utils/misc.go

Bump edge-runtime to 1.54.8
* mitigate denoland/deno_core#762 ([#377](https://github.com/supabase/edge-runtime/issues/377)) ([107f27d](https://github.com/supabase/edge-runtime/commit/107f27d031a47cc16a580c8f480763e8b05160bf))

fix: bump edge-runtime to 1.54.8

---

cmd/db.go
internal/link/link.go
internal/utils/config.go
internal/utils/config_test.go

Bug fix
When the `projectId` is derived, one must ensure that the total length of the created container is smaller than `63` chars or else we will have failures within the container network due to unmatchable hostnames
For new repos: Truncation.
For existing ones: Warnings.
Create a folder like this and try to initialize and run Supabase locally: 
`project_id = "Crafting-Production-Ready-Web-Apps-Using-Supabase-Test"`

fix: truncate project id in config when longer than 40 chars

---

internal/db/start/start.go
internal/start/start.go
internal/start/templates/pooler.exs
internal/utils/misc.go

This removes some complexity from starting up realtime into realtime startup process. To know more please check https://github.com/supabase/realtime/pull/1081

fix(realtime): bump up version to 2.29.13

---

internal/utils/misc.go

Bump edge-runtime to 1.54.9
* narrow the lifetime of the connection token ([#379](https://github.com/supabase/edge-runtime/issues/379)) ([ef3c0a1](https://github.com/supabase/edge-runtime/commit/ef3c0a1814c60e6ae6139af701be0f6fb068c399))

fix: bump edge-runtime to 1.54.9

---

internal/start/start.go
internal/utils/config.go

follow up #2061 
Show warning only on supabase start.

fix: move docker socket warning to start cmd

---

cmd/gen.go
internal/gen/types/types.go
internal/gen/types/types_test.go
internal/utils/misc.go

feature
relates to https://github.com/supabase/cli/pull/2476
```bash
supabase gen types --lang=go --local
```

feat(typegen): support generating types for golang

---

cmd/seed.go
internal/seed/buckets/buckets.go
internal/start/start.go

follow up https://github.com/supabase/cli/pull/2460
Broke start with console waiting for input.
Disable interactive console when seeding on start.

fix: disable interactive console when seeding on start

---

internal/utils/misc.go

Bump Realtime image to 2.29.15

fix: Bump Realtime image to 2.29.15

---

cmd/gen.go
internal/gen/types/types.go
internal/gen/types/types_test.go

Add swift type generation
Example
```sh
$ supabase gen types --lang=swift --local --schema public --swift-access-control public
```

feat(typegen): add swift type generator

---

internal/utils/misc.go

https://github.com/supabase/postgres-meta/compare/v0.83.0...v0.83.2
Fixes Swift generated types and `interval` representation

fix: pg-meta v0.83.2

---

internal/db/start/start.go
internal/utils/docker.go

Bug fix https://github.com/supabase/cli/issues/2407
Don't initialise auth, storage, or realtime schemas if those services are disabled.

fix: make dependent service schemas optional

---

cmd/root.go
internal/utils/release.go

Bug fix https://github.com/supabase/cli/issues/2470
If user is offline, version check will error and an empty file will be created to skip subsequent checks.

fix: skip version check if user is offline

---

internal/utils/misc.go

Bump edge-runtime to 1.54.10
* missing early retire signal ([#384](https://github.com/supabase/edge-runtime/issues/384)) ([e84efc0](https://github.com/supabase/edge-runtime/commit/e84efc030467961a367b6983369e5051000472c2))

fix: bump edge-runtime to 1.54.10

---

internal/start/start.go

Fix open ai key being passed in start.go to enable Supabase AI Assistant. 
Bug introduced in https://github.com/supabase/supabase/pull/21856
Riffs off of https://github.com/supabase/cli/pull/1986
See https://github.com/supabase/supabase/issues/27884
Hopefully can reestablish communication with our savior, the almighty GPT🤞
I'm creating this without any local tests as I understand that a beta release can be created by reading the CONTRIBUTION guide. I'm doing this because I'm lazy and don't want to setup my machine to be able to build and run this package. Hoping I can just `npx supabase@<my-beta-verion> start` and test if it works. Lmk if there's a more desirable way to do this.

fix: change openai api key name passed in start.go

---

internal/functions/deploy/bundle.go
internal/functions/serve/serve.go
internal/start/start.go
internal/utils/docker.go
internal/utils/docker_linux.go
pkg/config/config_test.go

Bug fix https://github.com/supabase/cli/issues/2538
relates to https://github.com/supabase/cli/issues/2531
Defaults to `DOCKER_HOST=tcp://localhost:2375` on windows.

fix: use http scheme for vector docker host

---

pkg/config/constants.go

relates to https://github.com/supabase/supabase/issues/26785
Seems like postgres and api gateway logs are still broken on windows.

fix(studio): bump to latest version

---

pkg/migration/list.go
pkg/pgxv5/rows.go

Bug fix
pgxconn.Query error is safe to ignore.

fix: ignore missing table when listing remote migrations

---

pkg/config/config.go
pkg/config/constants.go

Upgrade auth version to v2.157.1
Prior art for external config: https://github.com/supabase/cli/pull/1858/files#diff-315c0e4898fa48b5e5394e5a8d8d65437eac539e6b363a7660c157055a166fa9
Relevant thread: https://supabase.slack.com/archives/C022071RB2L/p1722589931235649

fix: upgrade auth version to v2.157.1 and add slack oidc config

---

docs/main.go
internal/link/diff.go
internal/link/link.go
internal/utils/api.go
internal/utils/flags/db_url.go
internal/utils/tenant/postgrest.go

Bug fix
```
$ supabase link
WARNING: Local config differs from linked project. Try updating supabase/config.toml
diff supabase/config.toml <project-ref>
--- supabase/config.toml
+++ <project-ref>
@@ -3,7 +3,7 @@
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
-max_rows = 100
+max_rows = 1000
[api.tls]
enabled = true
@@ -14,6 +14,6 @@
[db.pooler]
enabled = false
port = 54329
-pool_mode = "session"
+pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100
```
Also shows a forget password link
```
$ supabase db push
Forgot your password? Reset it from the Dashboard: https://supabase.com/dashboard/project/_/settings/database
Enter your database password:
```

fix: use unix diff for clearer config changes

---

pkg/config/constants.go

Bump edge-runtime to 1.56.0
* support setting network permissions via allowNet option ([#386](https://github.com/supabase/edge-runtime/issues/386)) ([5d9d180](https://github.com/supabase/edge-runtime/commit/5d9d180c67014ff3ba8233a68e89055b3ca2d646))

fix: bump edge-runtime to 1.56.0

---

cmd/seed.go
internal/db/reset/reset.go
internal/seed/buckets/buckets.go
internal/seed/buckets/buckets_test.go
internal/start/start.go
internal/storage/cp/cp.go
internal/storage/cp/cp_test.go
pkg/config/config.go
pkg/config/templates/config.toml
pkg/config/testdata/config.toml

feature
Allows configuring an `objects_path` for seeding buckets. Files under the path will be uploaded to their respective bucket.
```
[storage.buckets.images]
objects_path = "./images"
```
Path will be resolved relative to `config.toml`, ie. the path above resolves to `supabase/images`.
Also seeds automatically when running the following commands locally
- `supabase start`
- `supabase db reset`
For hosted projects, a separate command needs to be run:
- `supabase seed buckets`
This works fine for small objects but large files will require a separate solution.

feat: support declaring objects path for seeding buckets

---

internal/start/start.go
pkg/config/config.go
pkg/config/constants.go
pkg/config/templates/config.toml
pkg/config/testdata/config.toml

Introduces the supporting Auth configuration for  MFA (Phone). This include:
1. The respective enable / disable flows for each toggle `MFA.Phone.EnrollEnabled` and `MFA.Phone.VerifyEnabled`
2. `MFA.MaxEnrolledFactors`  which is already exposed on the platform
4. Phone also comes with a configurable OTP Length as well as Template. We don't include the provider specific configuration as they are derived from the primary provider. We also expose MaxFrequency

feat: add MFA (Phone) related config

---

internal/start/start.go
pkg/config/config.go
pkg/config/templates/config.toml

Adds support for configuring a Third-Party Auth provider to be used alongside Supabase Auth.
Internally both Storage, Realtime and PostgREST support this if they're configured with a JWKS.

feat: add third-party auth support for local dev

---

internal/start/start.go
internal/start/templates/kong.yml
internal/utils/docker.go
pkg/config/constants.go

Bug fix/feature
Currently, we use the docker port forwarding feature to direct traffic from port: 54323 -> to 8000 which is the port kong is listening to.
In order for kong to provide the correct `x-forwarded-port` instead of 8080 we shoukd configure [port_maps](https://docs.konghq.com/gateway/latest/reference/configuration/#port_maps) 
This PR sets the `port_maps` and bumps the version of Storage to v1.10.1 which conforms better to the canonical x-forwarded headers

fix(storage): configure and parse x-forwarded-for header

---

pkg/config/constants.go

Bump edge-runtime to 1.56.1
BREAKING CHANGE: This PR changes the way eszip is bundled. It should remain in draft status until it is determined to be stable enough.
* implement lazy load for eszip entities ([#343](https://github.com/supabase/edge-runtime/issues/343)) ([3f7863b](https://github.com/supabase/edge-runtime/commit/3f7863ba4b2f3b838934979cfb6fe2b0e7d6db3e))

fix: bump edge-runtime to 1.56.1

---

cmd/bootstrap.go
internal/bootstrap/bootstrap.go
internal/utils/release.go
tools/bumpdoc/main.go
tools/changelog/main.go
tools/publish/main.go
tools/selfhost/main.go

I fixed the typo in the name of utils.GetGitHubClient()
It's currently named utils.GetGtiHubClient()
n/a
n/a
n/a

chore: Fixed typo in 'GetGitHubClient()' function name

---

pkg/config/config.go

Fixes https://github.com/supabase/cli/issues/2527
Currently, the external_api_url is not read from the config.toml. 
I know there is an ongoing subject about mutualizing auth/studio url but it requires too much changes. 
This is a quick fix that improves the features of the CLI without removing any

fix(api): add external_url while a replacement is found for auth/studio

---

internal/start/start.go
pkg/config/config.go
pkg/config/templates/config.toml

This feature can be found in the Supabase Hosted Dashboard but doesn't have a way to configure it in the `config.toml`.
No way to set **Secure password change**
Can now set **Secure password change** in the `config.toml` file.

feat: add secure password change config

---

pkg/config/constants.go

Bump edge-runtime to 1.58.1
BREAKING CHANGE: This PR changes the way eszip is bundled. It should remain in draft status until it is determined to be stable enough.
* version up the Deno codebase to 1.45.2 ([#389](https://github.com/supabase/edge-runtime/issues/389)) ([82588d6](https://github.com/supabase/edge-runtime/commit/82588d6def254a2dfe008faabfdcb9202fb858a1))
* support declarative style fetch handler ([#400](https://github.com/supabase/edge-runtime/issues/400)) ([5d4a9b4](https://github.com/supabase/edge-runtime/commit/5d4a9b40ad1dfa58e35173e5c376eab6be899fe6))
* **deps:** bump openssl from 0.10.64 to 0.10.66 ([#397](https://github.com/supabase/edge-runtime/issues/397)) ([b27190c](https://github.com/supabase/edge-runtime/commit/b27190ca093e48df1c5768845cab09d7d7a06527))
* …

fix: bump edge-runtime to 1.58.1

---

pkg/config/constants.go

Bump up docker image to 2.30.34

fix(realtime): Bump up docker image to 2.30.34

---

pkg/config/constants.go

Bump edge-runtime to 1.58.2
* inspector causes panic ([#404](https://github.com/supabase/edge-runtime/issues/404)) ([8b29aa1](https://github.com/supabase/edge-runtime/commit/8b29aa16c6985a3911beb510ce7103cb3cee060c)) (Fixes #2646)

fix: bump edge-runtime to 1.58.2

---

internal/db/reset/reset.go
internal/db/reset/reset_test.go

When performing the "reset db" check against the config to find "enabled" services and only restart the ones that are enabled. Also only "seed storage" service if the storage service is actually enabled.
Fixes https://github.com/supabase/cli/issues/2658
- Make "restartServices" only restart enabled services
- Skip the bucket seeding phase if "storage" service isn't enabled.
In terms of output there should be no differences.

fix: db reset with disabled services

---

pkg/config/config.go

When fetching the well-known configuration for an OIDC third-party auth provider, we used the issuerURL which is just the baseURL instead of the discoveryURL as seems intended. This caused Auth0 configurations to try to parse HTML instead of the correct configuration, and I suspect this is the case for all the other providers as well.
With this bugfix it should work as expected for at least Auth0.
The `supabase start --debug` command fails with: `failed to parse response body: invalid character '<' looking for beginning of value`
Debug output:
```
supabase start --debug
Using workdir /Users/daginge/code/draum/frontend
Supabase CLI 1.191.3
2024/09/03 10:37:35 DNS Start: {Host:dev-kk0wnodjovc335tb.eu.auth0.com}
2024/09/03 10:37:35 DNS Done: {Addrs:[{IP:104.19.152.19 Zone:} {IP:104.19.153.19 …
```

fix: Use discoveryURL when fetching third-party OIDC config

---

pkg/config/constants.go

Bump edge-runtime to 1.58.3
* improve stability ([#406](https://github.com/supabase/edge-runtime/issues/406)) ([50eb636](https://github.com/supabase/edge-runtime/commit/50eb636b9d7313f33939f324da93813ef662e721))

fix: bump edge-runtime to 1.58.3

---

pkg/config/config.go

A small update to the configuration processing to allow AWS Cognito configuration values to be injected into `config.toml` using environment variables.
In order to use Cognito as a third party auth provider, configuration values must be added to `config.toml` in plain text.
```
[auth.third_party.aws_cognito]
enabled = true
user_pool_id = "my-user-pool-id"
user_pool_region = "us-east-1"
```
AWS Cognito configuration can now be injected via environment variables.
```
[auth.third_party.aws_cognito]
enabled = true
user_pool_id = "env(SUPABASE_AUTH_AWS_COGNITO_POOL_ID)"
user_pool_region = "env(SUPABASE_AUTH_AWS_COGNITO_REGION)"
```
AWS Cognito configuration is slightly broken (or at least confusing) until https://github.com/supabase/cli/pull/2655 is fixed.

feat: allow Cognito configuration from env var

---

internal/start/start.go

This solves the issue where the `supabase start` command exits with an error because the health check isnt performed properly.
This is a bug fix
`supabase start` results in an error and all containers getting killed. This is caused because the command to be executed isn't parsed properly by Podman Compose, resulting in a malformed health check command.
The error:
```
[eval]:1
'fetch("http://127.0.0.1:8080/health").then((r)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
at makeContextifyScript (node:internal/vm:185:14)
at node:internal/process/execution:107:22
at [eval]-wrapper:6:24
at runScript (node:internal/process/execution:101:62)
at evalScript (node:internal/process/execution:133:3)
at node:internal/main/eval_string:51:3
Node.js v20.15.0
``` …

fix: Health Check issue on Podman/Windows

---

cmd/db.go
docs/supabase/db/lint.md
internal/db/lint/lint.go
internal/db/lint/lint_test.go

Feature: Adds a `--fail-on` flag to the `db lint` command in the Supabase CLI.
Currently, `db lint` does not provide an option to exit with a non-zero status code on lint errors, limiting its use in CI/CD pipelines.
See: #1812
Introduces a `--fail-on` flag with options (`error`, `warning`, `none`) to control the exit status of `db lint` based on lint results.
Tested by running `db lint` with different `--fail-on` options to ensure correct exit statuses are returned.

feat: add db lint fail-on flag

---

internal/init/templates/.vscode/settings.json

Bug fix.
VS Code `settings.json` uses deprecated boolean option for ´deno.unstable´ flag.
VS Code `settings.json` now uses the granular flags while maintaining the same behavior.
Fixes #2682.
Before merging this PR, consider updating the code snippet in https://supabase.com/docs/guides/functions/import-maps#configuring-vscode to use the granular unstable flags too.

fix: update deno.unstable settings in VS Code settings.json template

---

cmd/start.go
internal/start/start.go

When providing --exclude flags, check the arguments match actuals images names show a warning otherwise.
Also fix a bug where stack couldnt start if storage was enabled in config but excluded in the arguments
Related: https://www.notion.so/supabase/exclude-doesnt-seem-to-work-f38b8444b62f4308aef657a52d51692b
Also might be worth considering allowing to alias between config services names and "containers exclusions" names. As it's not clear for instance that "gotrue" container relate to the "auth" service.

chore: start command validate exclude arguments

---

internal/db/start/start.go
internal/start/start.go
internal/utils/docker.go

Remove the plain RLIMIT_NOFILE values to ensure it won't be greater than the host system.
Fixes #2693

fix: the container ulimits for reatime

---

internal/hostnames/common.go

Remove the reference to replacing any CNAME records as this is no longer a requirement of the custom domain setup.

chore: remove cname swap message as it is no longer a requirement

---

internal/utils/docker.go

Skip unsupported `SecurityOpt` on bitbucket runners.
Fixes #2703 
Tested with the `setup-cli` on bitbucket platform using the current branch.

fix: disable security opts for db test on bitbucket runner

---

cmd/db.go
cmd/start.go
internal/db/push/push.go
internal/db/push/push_test.go
internal/db/reset/reset_test.go
internal/db/start/start_test.go
internal/init/init.go
internal/init/init_test.go
internal/migration/apply/apply.go
internal/migration/apply/apply_test.go
internal/utils/misc.go
internal/utils/misc_test.go
pkg/config/config.go
pkg/config/templates/config.toml
pkg/config/testdata/config.toml
pkg/config/utils.go
pkg/migration/seed.go

Feature enhancement: Improved seed data handling and configuration
Currently, the system uses a single, fixed seed file path (`utils.SeedDataPath`) for database seeding. This limits flexibility in organizing and applying seed data.
1. Introduces a new configuration option in `config.toml` for specifying multiple seed file paths using glob patterns:
```toml
[db.seed]
enabled = true
path = ['./seed.sql', './seeds/*.sql']
```
2. Implements a new function `GetSeedFiles` that:
- Matches files based on the configured glob patterns
- Deduplicates matched files to avoid duplicate seeding
- Sorts the files to ensure consistent application order
3. Updates various parts of the codebase to use the new seeding mechanism:
- Modifies the `SeedDatabase` function to use the new `GetSeedFiles` function
- …

feat: add custom seed path to config

---

README.md

Add a badge to keep an eye over the pipeline from bitbucket and gitlab.

chore: add bitbucket build canary badge

---

pkg/config/constants.go

Bump edge-runtime to 1.58.11
* **node:** mitigate denoland/deno[#24678](https://github.com/supabase/edge-runtime/issues/24678) ([#407](https://github.com/supabase/edge-runtime/issues/407)) ([fbcd8c5](https://github.com/supabase/edge-runtime/commit/fbcd8c5c0ce850cc20f9239218c3f969dc0ed4e8))
* **node:** mitigate denoland/deno[#25279](https://github.com/supabase/edge-runtime/issues/25279) ([#412](https://github.com/supabase/edge-runtime/issues/412)) ([41c7624](https://github.com/supabase/edge-runtime/commit/41c7624fd3c0659c78f0dd2b8725e8dfd9e24fa1))
* **sb_core:** add an API for chaos testing ([#411](https://github.com/supabase/edge-runtime/issues/411)) ([1c19701](https://github.com/supabase/edge-runtime/commit/1c19701acd71a676f884b21a0d48b84b473a1cb3))
* **base:** partial revert some …

fix: bump edge-runtime to 1.58.11

---

internal/db/diff/diff_test.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/db/start/start.go
internal/db/start/start_test.go
internal/migration/squash/squash_test.go
internal/start/start_test.go
internal/status/status.go

Bug fix
`db start && db reset` throws an error because storage container is missing.
Only seeds storage if local container is started.

fix: inspect storage container before seeding buckets

---

internal/db/push/push.go
internal/db/push/push_test.go
internal/db/reset/reset.go
internal/db/start/start.go
internal/db/start/start_test.go
internal/link/link.go
internal/link/link_test.go
internal/migration/apply/apply.go
internal/migration/apply/apply_test.go
internal/testing/helper/history.go
internal/utils/flags/db_url.go
pkg/migration/apply_test.go
pkg/migration/file.go
pkg/migration/history.go
pkg/migration/seed.go
pkg/migration/seed_test.go
pkg/pgtest/mock.go
pkg/pgxv5/rows.go

feature
Track seed files in a history table.
- `path` resolves to local seed file and is also they primary key
- `hash` is the sha256 checksum of the seed file
When loading seed files, we check the history table for path and hash match. Any unmatched files will be seeded next.
If file path exists in history but checksum doesn't match, the seed file will be marked dirty. Dirty files are not seeded, only their hash column will be updated.
If both path and hash match, the seed file is skipped, as it has been applied before.
```
$ supabase db push --local --include-seed
Connecting to local database...
Schema migrations are up to date.
Do you want to seed the remote database with these files?
• supabase/seeds/buckets.sql
• supabase/seeds/users.sql
[Y/n] n
context canceled
exit status 1
``` …

feat: track seeded files in migration table

---

pkg/config/constants.go

Bump edge-runtime to 1.58.12
* make sure that we can use various exts as an entrypoint when bundling ([#425](https://github.com/supabase/edge-runtime/issues/425)) ([5f87d9a](https://github.com/supabase/edge-runtime/commit/5f87d9aa3dbc450f2f768e4435b31c5ed982b784))

fix: bump edge-runtime to 1.58.12

---

api/beta.yaml
internal/link/link.go
internal/link/link_test.go
pkg/api/client.gen.go
pkg/api/types.gen.go

Following: https://github.com/supabase/infrastructure/pull/20022
We check the status of the project at link time and provide better error and warning message to the user.
Goal is to reduce confusion when errors raise in CI in such cases
Related: https://github.com/supabase/infrastructure/pull/20117

feat: check project status at link time

---

pkg/config/config.go

Bug fix https://github.com/supabase/cli/issues/2734
Convert path separator to `/` on windows.
Tested in VM.

fix: update path separator for windows glob

---

internal/db/start/start.go
pkg/config/constants.go

Bug fix https://github.com/supabase/cli/issues/2738
`STORAGE_FILE_BACKEND_PATH` is now required if `STORAGE_BACKEND=file` is set.

fix(storage): update default storage version to 1.11.13

---

pkg/migration/history.go

Bug fix https://github.com/supabase/cli/issues/2725
Due to a mistake in our schema, `name` column is nullable instead of always defaulting to empty string.

fix(migration): handle null value when fetching migration name

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/testdata/config.toml

feature
The values in `auth.additional_redirect_urls` can't read from the env.
The values in `auth.additional_redirect_urls` can read from the env. 😄 
I need that in order to have an environment agnostic configuration for the example I'm building showcasing social login in a Next.js app using `@supabase-labs/nextjs`.
In principle every time we have a config value being URL related, it should be able to read from the env.

feat: read env in auth.additional_redirect_urls values

---

pkg/config/constants.go

Bump edge-runtime to 1.58.13
* graceful shutdown should wait until the event worker has finished all its work ([#426](https://github.com/supabase/edge-runtime/issues/426)) ([fbddb16](https://github.com/supabase/edge-runtime/commit/fbddb1620732e0490b170d2c081361bc834fe124))

fix: bump edge-runtime to 1.58.13

---

pkg/config/constants.go

Bugfix/dependencies upgrade
Allow to deploy this bugfix for local dev: https://github.com/supabase/supabase/pull/29646

fix(studio): upgrade studio image to latest

---

internal/functions/deploy/deploy.go
internal/functions/serve/serve.go
pkg/config/config.go
pkg/function/batch.go

relates to https://github.com/supabase/cli/pull/2688
Check in `UpsertFunctions` if a slug should be skipped. 

fix: skip upserting disabled function

---

pkg/config/constants.go

Bump edge-runtime to 1.59.0
* support specifying npm registries via .npmrc ([#427](https://github.com/supabase/edge-runtime/issues/427)) ([051a276](https://github.com/supabase/edge-runtime/commit/051a2766f5859f8ed0071829d0e4928586fd702b))
See: https://supabase.slack.com/archives/C02KMRX22NR/p1729129599200949?thread_ts=1729052150.094779&cid=C02KMRX22NR

fix: bump edge-runtime to 1.59.0

---

cmd/root.go
pkg/config/config.go
pkg/config/config_test.go

Bug fix https://github.com/supabase/cli/issues/2772
For future reference, the order of loading env var to config is
1. cobra loads cli flags to viper with automatic env
2. godotenv loads .env / .env.local / .env.development files
3. mapstructure dumps default config struct to map
4. viper loads from config map (4) with automatic env (3)
5. viper dumps its state back to config
We can potentially remove dependency on godotenv by having viper load from .env files.

fix: squash base config with mapstructure

---

pkg/config/api.go

Bug fix
Empty array is a valid config if user doesn't want to expose any schemas or search paths.
```
[api]
schemas = []
extra_search_path = []
```

fix: empty array is valid api config

---

internal/stop/stop_test.go
internal/testing/apitest/docker.go
internal/utils/docker.go

**Bug fix** for `supabase stop --no-backup` for users on old versions of Docker or on Podman.
Before Docker API version 1.42, the `all` flag in `Docker.VolumePrune` is not required.
Podman prints an error like the following when the `all` flag is passed ([Podman's only compatible with Docker API v1.41][1]), e.g. when running `supabase stop --no-backup`:
```console
alois@pc:~/app (develop)$ npx supabase@1.207.4 stop --no-backup
failed to prune volumes: Error response from daemon: failed to parse filters for all=true&label=com.supabase.cli.project%3Dapp: "all" is an invalid volume filter
Try rerunning the command with --debug to troubleshoot the error.
```
[1]: https://github.com/containers/podman/blob/290d94d3c00857dd582ffbee6bd0677a0904c783/version/version.go#L46
See: …

fix: prune volumes without all flag for pre-Docker v1.42

---

pkg/migration/queries/drop.sql

Bug fix #2640 
supersedes https://github.com/supabase/cli/pull/2780
Failed to delete user-created publications, causing the migration to create publications to fail.
Add a function to drop user-created publications, excluding `supabase_realtime`.

fix: drop user created publications during reset

---

cmd/functions.go
go.mod
internal/branches/create/create_test.go
internal/functions/deploy/deploy.go
internal/functions/deploy/deploy_test.go
internal/functions/serve/serve_test.go
internal/init/init_test.go
internal/storage/cp/cp_test.go
internal/storage/ls/ls_test.go
internal/storage/mv/mv_test.go
internal/storage/rm/rm_test.go
internal/utils/api.go
internal/utils/console.go
internal/utils/misc.go
internal/utils/release_test.go

- refactor `utis.Ptr` to `cast.Ptr`
- make `go-cmp` direct dependency (`go mod tidy`)

chore: refactor use cast ptr

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/testdata/config.toml

- Bugfix: set the default value of seed for declared remotes to false
Related:
https://github.com/supabase/branching/pull/187

fix(config): default value for seed remote

---

internal/db/start/start.go
internal/db/start/start_test.go
pkg/config/db.go
pkg/config/db_test.go

- Apply settings set under db.settings to the local running db instance
Closes #2611

feat(config): allow local postgres configuration

---

scripts/postinstall.js

- Bug fix: 
Fix `node-fetch` `fetch` command hangs indefinitely when fetching the checksum file after fetching the binary, on some macOS devices that have stricter network restrictions. This PR will fix #2798 
- Misc:
Added some comments to explain the process clearly.
#2798 : running `npm install supabase@latest --save-dev` hangs and failed after waiting for a long time, the error happens at the fetching of the checksum file. However, running `sudo npm install ...` works.
Some investigation shows that this error starts happening from version `1.90.0`, version `1.89.1` did not have such issue. The change that was made between these two version is in this commit: https://github.com/supabase/cli/commit/571f336c117c182f015b6f6ba270c726a01732a7
By examining the commit, it shows that checksum …

fix: node-fetch hanging issue when fetching checksum after fetching binary

---

internal/start/start.go
pkg/config/config.go
pkg/config/constants.go
pkg/config/templates/config.toml
pkg/config/testdata/config.toml

Increment Auth version to v2.163.2 and update Auth version

feat(auth): add mfa webauthn config variables

---

internal/start/start.go
pkg/config/config.go
pkg/config/templates/config.toml
pkg/config/testdata/config.toml

Bug fix https://github.com/supabase/cli/issues/2802
Adds email opt length and expiry config.

fix(auth): support email otp length and expiry

---

internal/functions/deploy/bundle.go
internal/functions/deploy/deploy.go
internal/functions/serve/serve.go
internal/functions/serve/templates/main.ts
pkg/config/config.go

feature
Allow functions entrypoint to be customized, ie. `functions/my-slug/index.js`
TODO:

feat(functions): allow custom functions entrypoint path

---

api/beta.yaml
pkg/api/types.gen.go
pkg/config/config.go
pkg/config/storage.go
pkg/config/updater.go
pkg/config/updater_test.go

feature
Sync storage config from file to remote. Unblocks users with branching error:
```
{"statusCode":"413","error":"Payload too large","message":"The object exceeded the maximum allowed size"}
```

feat(config): implement storage config update

---

pkg/config/constants.go

Bump edge-runtime to 1.59.1
* **sb_graph:** checksum size is not a constant ([#433](https://github.com/supabase/edge-runtime/issues/433)) ([d06b556](https://github.com/supabase/edge-runtime/commit/d06b556cb0cdfd8af404d24ebb3e1366be549f23))

fix: bump edge-runtime to 1.59.1

---

cmd/inspect.go
internal/inspect/report_test.go
internal/inspect/role_configs/role_configs.go
internal/inspect/role_configs/role_configs.sql
internal/inspect/role_configs/role_configs_test.go

Feature
New `role-configs` command under `inspect` to show all users that have a configuration that is different from the standard
Useful for debugging and auditing

feat(inspect): add role-configs command to list db roles with custom settings

---

pkg/config/constants.go

Bump edge-runtime to 1.60.1
* onnx runtime shared sessions  ([#430](https://github.com/supabase/edge-runtime/issues/430)) ([fc80ebb](https://github.com/supabase/edge-runtime/commit/fc80ebba747cc411dde3a737575b3a478984c1f6)) (@kallebysantos)
* **sb_core:** expose web MessageChannel API ([#434](https://github.com/supabase/edge-runtime/issues/434)) ([ec9b270](https://github.com/supabase/edge-runtime/commit/ec9b270e33a1fcdd1b195cb3427fa76f269a5de9))
* **cli:** `--static` flag could not be used multiple times ([#432](https://github.com/supabase/edge-runtime/issues/432)) ([f2556c7](https://github.com/supabase/edge-runtime/commit/f2556c74bda04ee8a099fe3c478271f3d979c0e0))

fix: bump edge-runtime to 1.60.1

---

internal/functions/deploy/deploy.go
internal/functions/deploy/deploy_test.go
pkg/config/config.go
pkg/config/config_test.go

feature
Currently each edge function shares a global `import_map.json` by default.
To use one particular import map per function the user has to define it manually in `config.toml`
We now automatically load `deno.json` and `deno.jsonc` under the `supabase/functions/<slug>` directory.
Each function should be treated as a different project with its own set of dependencies.
`import_map.json` disappeared from Deno's doc since as of v1.19.2: https://deno.land/x/manual@v1.19.1/npm_nodejs/import_maps.md?source
Imports should now be declared as part of deno's config file `deno.json`.
We might want to deprecate `import_map.json`, especially when we will ship deno v2 support.

feat(config): load local deno.json file as import map

---

scripts/postinstall.js

chore
The technique for publishing a Go CLI on NPM is very interesting. However, the link is no longer valid. It looks like Xendit has moved its technical blog to Medium.

chore: update NPM publishing blog link

---

pkg/config/constants.go

Bump edge-runtime to 1.61.0
* partial enable s3 and tmp file system ([#429](https://github.com/supabase/edge-runtime/issues/429)) ([b10fb3d](https://github.com/supabase/edge-runtime/commit/b10fb3dcbc5c673f554da873172db2def3b3bc95))

fix: bump edge-runtime to 1.61.0

---

go.mod
pkg/config/db.go
pkg/config/updater.go

Following: https://github.com/supabase/infrastructure/pull/20462
Let the api decide if the service restart is necessary.
**caution**
Deduplicating the logic remove our ability to log a message to the user but since we didn't allowed to act on it (agree / refute) I think it's alright to let the API be the source of truth.

chore: refactor let api decide for restart

---

pkg/function/batch.go

Bug fix
When initiating a retry, reusing the buffer reader results in 0 length body. Instantiate a new reader instead.

fix(functions): create new reader for retrying deploy

---

pkg/config/auth.go
pkg/config/auth_test.go
pkg/config/config.go

part 3 of https://github.com/supabase/cli/pull/2814
Also adds `figma` and `kakao` auth providers to local.

feat(config): sync external provider config to remote

---

pkg/config/constants.go

Bump studio to the latest version. This studio version contains [the PR](https://github.com/supabase/supabase/pull/30332) to fix an issue with [auth, storage and realtime](https://github.com/supabase/cli/issues/2834).

fix(studio): bump studio image to 20241106-f29003e

---

api/beta.yaml
pkg/api/types.gen.go

Bug fix
Could not link project after updating cli.
Fixes generated api type.

fix: link fails due to wrong api key type

---

internal/functions/deploy/deploy.go

Bug fix https://github.com/supabase/cli/issues/2846
`import_map` is only set if the function is declared in config.toml
Also set `import_map` for function slugs globbed from local directories.

fix: auto detect deno.json for globbed slugs

---

internal/postgresConfig/update/update.go
pkg/config/db.go

feature
Support new postgres config option.
```
supabase --experimental postgres-config update --config track_commit_timestamp=true
```
At some point, we probably want to transition to using `[db.settings]` in config.toml for config updates.

feat: support tracking commit timestamp

---

internal/db/push/push.go

Bug fix
Allows disabling `[db.seed]` via `[remotes]` config.

fix: skip seeding for disabled remote

---

pkg/config/constants.go

Bump edge-runtime to 1.61.2
* **sb_workers:** allow extra context to be passed in from js land ([#440](https://github.com/supabase/edge-runtime/issues/440)) ([1bb7f70](https://github.com/supabase/edge-runtime/commit/1bb7f70bc9a9f4312ca3bbe5d249157ad5da13a8))

fix: bump edge-runtime to 1.61.2

---

pkg/config/auth.go
pkg/config/auth_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/templates/config.toml
pkg/config/testdata/config.toml

part 4 of https://github.com/supabase/cli/pull/2814
Sync `hook`, `mfa`, and `sessions` config to remote.

feat(config): sync hook and mfa config to remote

---

internal/start/start.go
pkg/config/api.go
pkg/config/auth.go
pkg/config/auth_test.go
pkg/config/config.go
pkg/config/db.go
pkg/config/storage.go
pkg/config/updater_test.go

part 5 of https://github.com/supabase/cli/pull/2814
Syncs `email` and custom `smtp` config to remote.

feat(config): sync smtp and email config to remote

---

pkg/config/constants.go

Bump edge-runtime to 1.62.1
* exposing onnx backend to JS land ([#436](https://github.com/supabase/edge-runtime/issues/436)) ([1052be2](https://github.com/supabase/edge-runtime/commit/1052be2bfba9a357609dd330f5f1b552687e2f18)) (@kallebysantos)
* **ci:** release workflow failure ([#442](https://github.com/supabase/edge-runtime/issues/442)) ([390a5c1](https://github.com/supabase/edge-runtime/commit/390a5c160b324ccc336fd0cf8e68d525fdaab1d0))

fix: bump edge-runtime to 1.62.1

---

cmd/bootstrap.go
internal/sso/internal/saml/files.go
internal/storage/client/scheme.go
internal/storage/cp/cp.go
pkg/parser/state.go

chore: replace case conversion with equal fold

---

cmd/config.go
internal/config/push/push.go
pkg/config/updater.go

feature
Running `supabase config push` will prompt user to update linked project's config to match local config.toml. For eg.
```
Pushing config to project: vpefcjyosynxeiebfscx
Updating API service with config: diff remote[api] local[api]
--- remote[api]
+++ local[api]
@@ -1,7 +1,7 @@
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
-max_rows = 1000
+max_rows = 100
port = 54321
external_url = "https://127.0.0.1:54321"
Do you want to push api config to remote? [Y/n]
```
Answering `Y` (default) will call mgmt-api to update config, `n` will skip to next config, and ctrl + c will abort the update.

feat: support config push command

---

internal/start/start.go
pkg/config/api_test.go
pkg/config/auth.go
pkg/config/auth_test.go
pkg/config/config.go
pkg/config/db_test.go
pkg/config/testdata/TestApiDiff/detects_differences.diff
pkg/config/testdata/TestApiDiff/handles_api_disabled_on_local_side.diff
pkg/config/testdata/TestApiDiff/handles_api_disabled_on_remote_side.diff
pkg/config/testdata/TestDbSettingsDiff/detects_differences.diff
pkg/config/testdata/TestDbSettingsDiff/handles_api_disabled_on_local_side.diff
pkg/config/testdata/TestDbSettingsDiff/handles_api_disabled_on_remote_side.diff
pkg/config/testdata/TestEmailDiff/local_disabled_remote_enabled.diff
pkg/config/testdata/TestEmailDiff/local_enabled_remote_disabled.diff
pkg/config/testdata/TestExternalDiff/local_enabled_and_disabled.diff
pkg/config/testdata/TestHookDiff/local_enabled_and_disabled.diff
pkg/config/testdata/TestMfaDiff/local_enabled_and_disabled.diff
pkg/config/testdata/TestSmsDiff/enable_sign_up_without_provider.diff
pkg/config/testdata/TestSmsDiff/local_disabled_remote_enabled.diff
pkg/config/testdata/TestSmsDiff/local_enabled_remote_disabled.diff

part 6 of https://github.com/supabase/cli/pull/2814
Loads email template from `content_path` to `Content` field for remote diff.
Added `assertSnapshotEqual` test utility.
- Run tests after `rm -rf testdata/**/*.diff` to initialise snapshot files
- Run tests again to assert equality on subsequent changes

fix(config): diff email template content with remote

---

internal/functions/serve/templates/main.ts

Hosted platform doesn't do this anymore. There's a request idle timeout of 150s (https://supabase.com/docs/guides/functions/limits). This is built into the edge-runtime itself.

fix: do not abort function reqs after 200s

---

pkg/config/constants.go

Bump edge-runtime to 1.62.2
* **sb_ai:** Sessions are dropped while still in use ([#443](https://github.com/supabase/edge-runtime/issues/443)) ([e522925](https://github.com/supabase/edge-runtime/commit/e522925c480951576d6f3e732f0bf7881b94c063)) (@kallebysantos)

fix: bump edge-runtime to 1.62.2

---

internal/config/push/push.go

Bug fix
Overrides local project id when no remote is declared.

fix: use base config when no remote is declared

---

internal/functions/serve/templates/main.ts

Need to enable readFileSync API since edge-runtime 1.62.1 explicitly

fix: enable readFileSyncAPI in user workers

---

internal/functions/serve/templates/main.ts

Updated error codes / messages returned in `functions serve` to match to what's returned currently in hosted platform.

fix: match edge function error codes to hosted platform

---

pkg/config/constants.go

Main changes described here: https://github.com/supabase/auth/compare/v2.163.2...v2.164.0

fix: increment auth version to v2.164.0

---

pkg/migration/queries/drop.sql

Bug fix https://github.com/supabase/cli/issues/2696
Also clears `supabase_functions.hooks` table on reset.

fix: drop webhooks request history on remote reset

---

internal/link/link.go
internal/link/link_test.go
pkg/config/api.go
pkg/config/auth.go
pkg/config/db.go
pkg/config/storage.go
pkg/config/templates/config.toml
pkg/config/testdata/config.toml

feature
Diff configs by merging mgmt-api response to local struct.
```
WARNING: Project status is RESTORING instead of Active Healthy. Some operations might fail.
Enter your database password (or leave blank to skip):
Finished supabase link.
WARNING: Local config differs from linked project. Try updating supabase/config.toml
diff supabase/config.toml ljkpogxamxkdhowzcjvo
--- supabase/config.toml
+++ ljkpogxamxkdhowzcjvo
@@ -2,7 +2,7 @@
[api]
enabled = true
-schemas = ["public", "graphql_public"]
+schemas = ["public", "storage", "graphql_public"]
```
A simpler change than https://github.com/supabase/cli/pull/2895

feat: diff auth and storage config on link

---

api/beta.yaml
cmd/projects.go
internal/bootstrap/bootstrap.go
internal/link/link.go
internal/link/link_test.go
internal/projects/apiKeys/api_keys.go
internal/projects/create/create.go
internal/projects/create/create_test.go
internal/projects/list/list.go
internal/utils/tenant/client.go
pkg/api/client.gen.go
pkg/api/types.gen.go

chore: update api/beta.yaml from staging v1-yaml

---

pkg/config/constants.go

Bump edge-runtime to 1.64.1
* **base:** sent low memory notification when worker switches to retired state ([#450](https://github.com/supabase/edge-runtime/issues/450)) ([388d2ea](https://github.com/supabase/edge-runtime/commit/388d2ea69729777f31426bb16d9766d67d902cee))
* support dispatching the runtime events ([#351](https://github.com/supabase/edge-runtime/issues/351)) ([997f2d9](https://github.com/supabase/edge-runtime/commit/997f2d9ede86169ceb0651d7560b6f4d966ea0b8))
* exposing `deno_cache` + `ai cache interceptor` ([#446](https://github.com/supabase/edge-runtime/issues/446)) ([13ee2a2](https://github.com/supabase/edge-runtime/commit/13ee2a29dc41b1b049ee9a86ef06c46cf8eb0cfa)) (@kallebysantos)
* polishing tmp fs and s3 fs ([#444](https://github.com/supabase/edge-runtime/issues/444)) …

fix: bump edge-runtime to 1.64.1

---

internal/inspect/role_configs/role_configs.sql

Bug fix
Hanging `;` in role-configs
Fixed

chore: remove trailing semicolon from role_configs.sql

---

pkg/config/constants.go

Bump realtime image to the latest [version](https://github.com/supabase/realtime/releases/tag/v2.33.51)

fix(realtime): bump realtime image to 2.33.51

---

internal/db/branch/switch_/switch__test.go
internal/db/diff/diff.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/db/start/start.go
internal/utils/misc.go

- Ensure `db reset` command work properly on postgres v14
The root cause is that while in pg15+ `DATABASE DROP FORCE` kill all connections, it's not the case for pg14. Requiring to manually disconnect all connections before performing the reset.
Closes #2903

fix(reset): ensure _supabase connections disconnect before reset

---

internal/start/start.go
pkg/config/config.go
pkg/config/templates/config.toml

- Add sender_name and admin_email for inbucket service configuration
Related #2899

feat(config): allow custom admin and sendername for inbucket

---

pkg/config/auth_test.go
pkg/config/config.go
pkg/config/testdata/TestExternalDiff/local_enabled_and_disabled.diff
pkg/config/testdata/TestSmsDiff/local_disabled_remote_enabled.diff
pkg/config/testdata/TestSmsDiff/local_enabled_remote_disabled.diff
pkg/config/updater_test.go
pkg/config/utils.go

Bug fix
If user declares an empty `[sms.test_otp]` without any entries, auth config would show a diff with remote set to nil.
This causes unnecessary config update being enqueued on api.
Always initialise a non-nil map to avoid this problem.

fix: initialise test otp to an empty map

---

pkg/config/constants.go

fix: bump edge-runtime to 1.65.0

---

pkg/config/templates/config.toml

- Add url to the docs reference on top of config.toml template

chore(docs): add link to the config reference in toml template

---

pkg/config/constants.go

Bump edge-runtime to 1.65.1.
* move `markAsBackground` to `EdgeRuntime.waitUntil` ([#454](https://github.com/supabase/edge-runtime/issues/454)) ([954ab6d](https://github.com/supabase/edge-runtime/commit/954ab6d027736f0de499233f729f22917155f0c9))

fix: bump edge-runtime to 1.65.1

---

pkg/config/constants.go

Bump edge-runtime to 1.65.3
* polishing the worker bootstrap phase and ridding annoying cache adaptor errors emitted from `transformers.js` ([#453](https://github.com/supabase/edge-runtime/issues/453)) ([18d8f69](https://github.com/supabase/edge-runtime/commit/18d8f69b0d8456ac9108ee6c39447b3f244008df)) (@kallebysantos)
* `beforeunload` event didn't trigger on the early drop state ([#455](https://github.com/supabase/edge-runtime/issues/455)) ([5707665](https://github.com/supabase/edge-runtime/commit/5707665873fee6938a84c3a56007cdabaf75b9c8))

fix: bump edge-runtime to 1.65.3

---

docs/supabase/db/reset.md

closes https://github.com/supabase/cli/issues/2933
- Removes misleading comment about local reset behaviour.
- Briefly documents the remote reset behaviour

chore: update docs for remote db reset

---

pkg/config/constants.go

Bump edge-runtime to 1.65.4
* **base:** don't wrap `JsRuntime` with `ManuallyDrop` early ([#457](https://github.com/supabase/edge-runtime/issues/457)) ([4cbeee8](https://github.com/supabase/edge-runtime/commit/4cbeee8424398a06a8a1b97b166a273199d7013b))

fix: bump edge-runtime to 1.65.4

---

cmd/root.go
cmd/snippets.go
internal/services/services.go
internal/snippets/list/list.go
internal/start/start.go
pkg/config/config.go

feature
Supports `supabase snippets list --project-ref <ref>` flag.
Also refactors services command for consistent version check.

fix: optional project ref flag for snippets command

---

internal/db/reset/reset.go
internal/functions/deploy/deploy.go
internal/gen/types/types.go
internal/projects/list/list.go
internal/seed/buckets/buckets.go
internal/services/services.go
internal/start/start.go
internal/storage/cp/cp.go
internal/utils/flags/db_url.go
internal/utils/flags/project_ref.go
pkg/config/auth.go

Bug fix
Updates functions, storage, reset, and typegen to account for remote config.

fix: account for remote config when pushing

---

internal/start/start.go
pkg/config/auth.go
pkg/config/auth_test.go
pkg/config/config.go
pkg/config/templates/config.toml
pkg/config/testdata/TestEmailDiff/local_disabled_remote_enabled.diff
pkg/config/testdata/TestEmailDiff/local_enabled_remote_disabled.diff

Bug fix
If `[auth.email.smtp]` is not declared in config.toml, skip pushing the config to remote.
Also adds a `enabled` field to allow explicit disabling of smtp.

fix: optional smtp block should not override remote

---

pkg/config/config.go

follow up #2961 
Clone must handle pointer structs explicitly.

fix: handle pointers when cloning auth hooks

---

pkg/config/config.go

Bug fix https://github.com/supabase/cli/issues/2963
Update `content_path` to always be relative to supabase directory.

fix: rewrite content template path in nested directory

---

cmd/db.go

- Show the absolute path when dump commande is directed to a file

feat(dump): print complete filedist path for dump

---

pkg/config/constants.go

Upgrade Storage image to v1.14.5
Image update
Upgrade Storage base image to v1.14.5

fix: update storage image v1.14.5

---

pkg/config/constants.go

fix: bump realtime image to 2.33.70

---

pkg/config/constants.go

Bump edge-runtime to 1.66.0
* **base:** make able to trigger early drop with other resources ([#465](https://github.com/supabase/edge-runtime/issues/465)) ([667db65](https://github.com/supabase/edge-runtime/commit/667db65abdefaacfaa7e0427bb0aefa3be1aa34f))

fix: bump edge-runtime to 1.66.0

---

internal/start/start.go
internal/start/start_test.go

Rather than asking the user to run the command to get the values Run the command for him so start command always return the infos of the running stack.

feat(start): automatically run the status command if already started

---

pkg/config/constants.go

Bump edge-runtime to 1.66.1
* **ext/core:** missing `Supabase` namespace ([#467](https://github.com/supabase/edge-runtime/issues/467)) ([65c4e17](https://github.com/supabase/edge-runtime/commit/65c4e17736676e341e2fb32e82b8e3d7c737d6df))

fix: bump edge-runtime to 1.66.1

---

pkg/config/config.go

Bug fix
Custom sql_paths in remotes block is not resolved properly.
Refactor path resolution to be called for each remote.

fix: resolve file paths in remote config

---

pkg/config/constants.go

PR to update the version of gotrue. The change aligns with the existing version outlined in [line 27 of bump-gotrue-generic.yml](https://github.com/supabase/helper-scripts/blob/master/ansible/bump-gotrue-generic.yml#L27).

fix: bump gotrue to 2.167.0

---

pkg/config/constants.go

Bump edge-runtime to 1.66.2
* **ext/event_worker:** don't use `tracing` as the log backend if `cli/tracing` feature flag is not enabled ([#469](https://github.com/supabase/edge-runtime/issues/469)) ([6246a6f](https://github.com/supabase/edge-runtime/commit/6246a6f37d50368c3553621bf5fdeec3fab7c67d))
Fixes #3006

fix: bump edge-runtime to 1.66.2

---

pkg/config/auth.go
pkg/config/testdata/TestHookDiff/local_enabled_remote_disabled.diff

Bug fix
If local secret is unset, no need to diff with platform defaults.

fix: ignore hash if local secret is unset

---

internal/functions/deploy/bundle.go

This PR provides the option to set a custom NPM registry using the `NPM_CONFIG_REGISTRY` environment variable. This is used when deploying functions.

fix: pass NPM_CONFIG_REGISTRY env variable when bundling functions

---

pkg/config/constants.go

Bump edge-runtime to 1.66.3
* allow setting static patterns when creating a user worker ([#471](https://github.com/supabase/edge-runtime/issues/471)) ([d2c21c1](https://github.com/supabase/edge-runtime/commit/d2c21c16ca075eee86f677e451eb8388cdfb9fd3))

fix: bump edge-runtime to 1.66.3

---

internal/storage/cp/cp.go
pkg/storage/batch.go
pkg/storage/objects.go
pkg/storage/objects_test.go

Based on the filename extension on top of the content reading autodetect to have a behavior similar with what happen when uploading files via studio.
- Add content type detection for JavaScript (text/javascript)
- Add content type detection for CSS (text/css)
- Add content type detection for SQL (application/x-sql)
- Default to text/plain for unrecognized text files like .go
Add some unit testings for the ParseFileOptions function.

feat(storage): autodetect narrow down text/plain contentype

---

pkg/config/auth.go
pkg/config/config.go
pkg/config/secret.go

fix: skip hashing unloaded env reference

---

internal/db/dump/dump.go
internal/utils/misc.go
pkg/migration/drop.go

Bug fix https://github.com/supabase/cli/issues/2998
pgmq causes seg fault when running pg_dump. Steps to reproduce
1. Create `supabase/migrations/0_schema.sql`
```sql
CREATE EXTENSION pgmq;
SELECT pgmq.create('my_queue');
```
2. Run `supabase db dump --local`
```bash
Dumping schemas from local database...
--: line 47:     7 Segmentation fault      pg_dump --schema-only --quote-all-identifier --exclude-schema "${EXCLUDED_SCHEMAS:-}" ${EXTRA_FLAGS:-}
...
error running container: exit 139
```
Exclude `pgmq` schema to unblock db dump.
Schema diffing for pgmq queues wouldn't work anyway because it inserts into pgmq.meta table.
The workaround is to manage those queues manually with migration files like (1).

fix: exclude pgmq schema from db dump and pull

---

internal/init/templates/.gitignore

chore
Updated gitignore to follow [dotenv convention](https://github.com/bkeepers/dotenv?tab=readme-ov-file#customizing-rails) more closely.

fix: update gitignore file to exclude dotenvx files

---

internal/branches/get/get.go

This is a bug fix for the `branches get` command. Currently, it returns an incorrect host in the PostgreSQL URL.
The PostgreSQL URL contains a redundant db.***.supabase.co.
```sh
> supabase branches get --experimental --output json                                                                                         develop
{
"POSTGRES_URL": "postgresql://postgres:[password]@db.db.[project-id].supabase.co.supabase.co:5432/?connect_timeout=10"
}
```
```sh
> go run . branches get --experimental --output json
{
"POSTGRES_URL": "postgresql://postgres:[password]@db.[project-id].supabase.co:5432/?connect_timeout=10"
}
```

fix: use direct DbHost from response in `branches get`

---

cmd/postgres.go
internal/postgresConfig/delete/delete.go

Add a new `delete` subcommand to `posgres-config` allowing to restore override values back to default ones more easily.
```
supabase postgres-config delete --config max_connections
supabase postgres-config delete --config max_wal_size,effective_cache_size,shared_buffers
supabase postgres-config delete --config work_mem,maintenance_work_mem --no-restart
```
Closes DEVW-324

feat(postgrest-config): add delete command to cli for convenience

---

pkg/config/config.go

Bug fix
If user declares an empty value in .env like `MY_SECRET=`, we should treat them as uninitialised like we used to.

fix: ignore envs declared with empty value

---

pkg/migration/queries/drop.sql

Exclude realtime messages publication from publication dropping
Requires https://github.com/supabase/realtime/pull/1274 to be merged

fix: Exclude realtime messages publication from publication dropping

---

pkg/migration/history.go

Typo in error message
says the wrong table name

fix: typo in error message when creating seed table

---

internal/db/push/push.go
internal/db/reset/reset.go
internal/db/start/start.go
internal/migration/up/up.go
pkg/config/db.go
pkg/config/templates/config.toml
pkg/config/testdata/config.toml
pkg/vault/batch.go

feature
Updates vault secrets before migration.
- migration up
- db diff
- db push
- db reset
- db start
relates to https://github.com/supabase/cli/issues/1190

feat: update vault secrets from config

---

internal/db/diff/diff_test.go
internal/db/push/push_test.go
pkg/migration/file.go
pkg/migration/file_test.go
pkg/migration/history.go
pkg/pgxv5/connect.go

Bug fix
Improve migration debugging experience by logging notice messages and error details.
```
Applying migration 1_schema.sql...
ERROR: syntax error at or near "exist" (SQLSTATE 42601)
At statement 0:                                        
create table if not exist my_table (name text)         
^                           
```

fix: print notices from migration statements

---

pkg/config/constants.go

Bump edge-runtime to 1.66.7
* **ext/node:** set process.env as own property ([#485](https://github.com/supabase/edge-runtime/issues/485)) ([1b2ab71](https://github.com/supabase/edge-runtime/commit/1b2ab71ad2fc00257d9ab47a5a3edb20eabded2e))
* **ext/ai:** Invalid tensor length causing Segmentation Fault ([#483](https://github.com/supabase/edge-runtime/issues/483)) ([6a32308](https://github.com/supabase/edge-runtime/commit/6a32308f3295de988e9e235396c793165e6ec40c)) (@kallebysantos)

fix: bump edge-runtime to 1.66.7

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/decode_hooks.go

- Improve the functions parse config error to give more actionable error message for functions in common case of `Unknown field` or `functions[0] ... expected a map` error.

fix: improve function config parse error message

---

pkg/config/config.go
pkg/config/secret.go
pkg/config/storage.go

fix: skip hashing empty secret values

---

internal/db/branch/switch_/switch__test.go
internal/db/diff/diff_test.go
internal/db/pull/pull_test.go
internal/db/start/start_test.go
internal/functions/serve/serve_test.go
internal/start/start_test.go
internal/status/status_test.go
internal/stop/stop_test.go
internal/utils/flags/config_path.go
internal/utils/misc.go
pkg/config/config.go
pkg/config/config_test.go

feature
Use sane defaults when config file is not present.

feat: make config file optional

---

pkg/config/config.go

This fixes a bug that prevents users from setting a config value containing the external URL that the Supabase API will be deployed at.
As stated in #3118, although the `api.external_url` config field exists, its value is always overwritten in pkg/config/config.go. This prevents the user from setting the external URL that is used for things like Supabase Auth generating links.
Now, if there is a value supplied for `api.external_url`, it will be used as the API's external URL. If there is not a value supplied for `api.external_url`, it will still be set to a value derived from the hardcoded hostname, "127.0.0.1".

Fix: Don't overwrite `api.external_url` from config.toml

---

api/beta.yaml
pkg/api/client.gen.go
pkg/api/types.gen.go

chore: bump openapi spec for function deploy

---

pkg/config/constants.go

Bump edge-runtime to 1.67.1
* convert file path with special characters to url correctly ([#490](https://github.com/supabase/edge-runtime/issues/490)) ([3d93fb1](https://github.com/supabase/edge-runtime/commit/3d93fb16c55091d56dee44bb0bc97a888e230a36))

fix: bump edge-runtime to 1.67.1

---

internal/db/dump/templates/dump_schema.sh
internal/db/start/templates/restore.sh
internal/db/start/templates/schema.sql

Bug fix
1. remove hardcoded `pgsodium` schema
2. step down superuser only after restore
3. always assign default postgres password

fix: handle failure modes when restoring from backup

---

pkg/config/constants.go

Bump edge-runtime to 1.67.2
* unblock `Deno.realPathSync` ([#493](https://github.com/supabase/edge-runtime/issues/493)) ([bbd9dc6](https://github.com/supabase/edge-runtime/commit/bbd9dc61a032ef1ccab8913e82bb3722a20ec717))

fix: bump edge-runtime to 1.67.2

---

internal/start/start.go

This change ensures that when mounting unix sockets for enabling dind access, security opt `label=disable` is set for the container.
Ref: https://docs.podman.io/en/latest/markdown/podman-system-service.1.html#access-the-unix-socket-from-inside-a-container
See-also: https://github.com/supabase/supabase/pull/33603
Bug fix
At present when using rootless podman with SELinux enabled, `supbase start` command fails at health check step.
Relates-to: #3099
```console
2025-02-15T15:52:11.439823Z ERROR source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::sources::docker_logs: Listing currently running containers failed. error=error trying to connect: Permission denied (os error 13)
```
When executing `supabase start` using rootless …

fix: disable label separation when binding socket

---

cmd/functions.go
cmd/gen.go
internal/functions/deploy/deploy.go
internal/functions/deploy/deploy_test.go
internal/functions/deploy/upload.go
internal/functions/deploy/upload_test.go

feature
```bash
supabase functions deploy --use-api --jobs 3
```

feat: deploy functions in parallel over api

---

internal/db/diff/diff.go
internal/db/diff/diff_test.go
internal/db/diff/pgadmin.go
internal/db/pull/pull.go
internal/db/pull/pull_test.go
internal/db/remote/changes/changes.go
internal/db/remote/commit/commit.go
internal/functions/deploy/upload.go
internal/migration/squash/squash.go
internal/migration/squash/squash_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/db.go
pkg/config/templates/config.toml
pkg/config/testdata/config.toml
pkg/migration/seed.go
pkg/migration/seed_test.go

feature
Adds config option for ordering declarative schemas.
```toml
[db.migrations]
schema_paths = ["./schemas/*.sql"]
```

feat: config option for ordering declarative schemas

---

internal/db/dump/templates/dump_schema.sh

Bug fix https://github.com/supabase/cli/issues/3071#issuecomment-2673190191
Also ignore `supabase_realtime_messages_publication` when running db dump.

fix: skip realtime publications on schema dump

---

pkg/config/config.go
pkg/config/utils.go

Bug fix
Support customising edge runtime version, ie.
```bash
echo "v1.68.0-develop.1" > supabase/.temp/function-version
```

fix: load edge runtime version if exists

---

internal/db/dump/templates/dump_schema.sh

follow up https://github.com/supabase/cli/pull/3190
Alter publication is forbidden because `postgres` role is not the owner of `supabase_realtime_messages_publication`.

fix: skip altering supabase managed publication

---

pkg/config/config.go
pkg/config/utils.go

Change the name of override file from `function-version` to `edge-runtime-version` to make it match with Docker image name.

fix: rename the override file to edge-runtime-version

---

internal/functions/new/new.go
internal/functions/new/new_test.go
internal/functions/new/templates/config.toml
pkg/config/templates/config.toml

Bug fix
Make it easier to initialise new functions by appending to config.toml.

fix: append config.toml when creating new function

---

cmd/branches.go
cmd/gen.go
cmd/status.go
internal/branches/get/get.go
internal/branches/list/list.go
internal/projects/apiKeys/api_keys.go
internal/projects/apiKeys/api_keys_test.go
internal/projects/create/create.go
internal/projects/list/list.go
internal/sso/create/create.go
internal/sso/get/get.go
internal/sso/info/info.go
internal/sso/remove/remove.go
internal/sso/update/update.go
internal/utils/connect.go
internal/utils/output.go
pkg/function/batch.go
pkg/migration/list.go
pkg/storage/batch.go

feature
```
$ supabase --experimental branches get --output json
Selected branch ID: 709a7cc3-2cfd-417d-8828-76c8bbc58a1e
{
"POSTGRES_URL": "postgresql://...@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?connect_timeout=10",
"POSTGRES_URL_NON_POOLING": "postgresql://...@db.kpojrjxbvujjhamjpcux.supabase.co:5432/?connect_timeout=10",
"SUPABASE_ANON_KEY": "...",
"SUPABASE_SERVICE_ROLE_KEY": "...",
"SUPABASE_URL": "https://kpojrjxbvujjhamjpcux.supabase.co"
}
```

feat: output standard env vars from branches get

---

pkg/migration/queries/drop.sql

Fixes https://github.com/orgs/supabase/discussions/18937#discussioncomment-11823004
View in the `public` schema depending on a supabase specific schema like `storage` aren't dropped as part of the `DropUserSchemas` function, which makes the whole `drop.sql` fails as we then attempt to drop all the user-defined types in `public`. A view being represented by a composite type internally in Postgres, we hit the error `ERROR: cannot drop type objects because view objects requires it (SQLSTATE 2BP01)`.
I added an explicit step to drop all the views in `public` before dropping the tables.

fix: drop public views explicitly

---

internal/functions/new/new.go
internal/functions/serve/serve.go
internal/secrets/set/set.go
pkg/config/config.go
pkg/config/templates/config.toml
pkg/config/testdata/config.toml

feature https://github.com/orgs/supabase/discussions/18937#discussioncomment-12342719
```toml
[edge_runtime.secrets]
MY_SECRET = "env(some_key)"
```
TODO:

feat: support setting function secrets from config

---

pkg/config/auth.go
pkg/config/config.go
pkg/config/templates/config.toml

Adds Clerk as an officially supported Third-Party Auth provider in the CLI.

feat: add clerk third-party auth config

---

pkg/config/config.go
pkg/config/templates/config.toml

fix: clerk tpa domain pattern works for non-production mode domains

---

pkg/config/config.go
pkg/config/constants.go
pkg/config/templates/config.toml
pkg/config/testdata/config.toml

feature
Allows users to switch to deno 2 for experimentation.

feat: allow deno version in config

---

cmd/link.go

Bug fix https://github.com/supabase/cli/issues/3286
`--password` flag should take precedence over .env file.

fix: link password flag override

---

internal/functions/deploy/bundle.go
internal/functions/deploy/bundle_test.go
pkg/function/api.go
pkg/function/batch.go
pkg/function/batch_test.go
pkg/function/bundle.go
pkg/function/bundle_test.go
pkg/migration/list.go

Bug fix
Returns deploy metadata from docker and native bundle.

fix: return deploy metadata from bundle

---

internal/utils/flags/db_url.go

Bug fix https://github.com/supabase/cli/issues/3306
When parsing `--db-url` flag, docker id should be loaded with config file.

fix: update docker id before db pull

---

README.md

It says v1, but the latest releases are v2. It's confusing to find on npm with the wrong major version number.

chore(docs): Remove v1 from title

---

internal/start/start.go

This is to fix the email rate limit issue on local development.
Emails are being rate limited even without `auth.email.smtp` being enabled.
Emails are only rate limited if `auth.email.smtp` is enabled.
Related to https://github.com/supabase/cli/issues/3353

fix(config): rate limit emails only if custom smtp enabled

---

pkg/config/constants.go

Bump deno2 to 1.68.0-develop.13

fix: bump deno2 to 1.68.0-develop.13

---

pkg/function/deploy.go
pkg/function/deploy_test.go
pkg/function/testdata/nested/deno.json
pkg/function/testdata/nested/index.ts
pkg/function/testdata/writes_import_map.form

Bug fix
Import maps must be resolved relative to `deno.json` file.

fix: resolve legacy import map

---

internal/db/dump/dump.go
internal/utils/config.go
pkg/config/config.go
pkg/config/constants.go
pkg/config/templates/Dockerfile
tools/selfhost/main.go

- Introduce pg17 as a possible image for the local dev experience.

feat(cli): setup postgres17 for local development

---

pkg/function/deploy.go

Bug fix
```
failed to load import map: readfile /Users/qiao/work/cli/supabase/functions/deno.json: invalid argument
```
```
supabase functions deploy test --import-map supabase/functions/deno.json --use-api
```

fix: convert all paths to relative for deploy

---

internal/functions/deploy/bundle.go
internal/functions/deploy/bundle_test.go
internal/functions/deploy/deploy.go
internal/functions/deploy/deploy_test.go
internal/functions/serve/serve.go
internal/functions/serve/serve_test.go
internal/utils/deno.go
internal/utils/deno_test.go
pkg/function/deploy.go
pkg/function/deploy_test.go

Bug fix
When using `outside import` for local development, the bundler does not include relative imports in the Module graph,
Like the following [example](https://github.com/kallebysantos/testing.supabase.outside-imports)
<details>
<summary>Error</summary>
```
worker boot error: failed to create the graph: Module not found "file:///Users/kallebysantos/projects/testing/supa/outside-imports/my-lib/add.ts".
at file:///Users/kallebysantos/projects/testing/supa/outside-imports/my-lib/index.ts:1:21
worker boot error: failed to create the graph: Module not found "file:///Users/kallebysantos/projects/testing/supa/outside-imports/my-lib/add.ts".
at file:///Users/kallebysantos/projects/testing/supa/outside-imports/my-lib/index.ts:1:21
InvalidWorkerCreation: worker boot error: failed to create the …
```

fix: outside import with relative module graph

---

internal/functions/deploy/bundle.go
internal/utils/deno.go
internal/utils/deno_test.go
pkg/function/deno.go
pkg/function/deno_test.go
pkg/function/deploy.go
pkg/function/deploy_test.go

feature
Addresses https://github.com/supabase/cli/pull/3429

feat: load import map reference in deno config

---

cmd/root.go
internal/debug/http.go
internal/utils/api.go

chore
Replaces trace context with simplified debug output.
```bash
$ supabase start --debug
...
2025/02/24 14:33:21 HTTP HEAD: https://127.0.0.1:54321/rest-admin/v1/ready
2025/02/24 14:33:21 HTTP HEAD: https://127.0.0.1:54321/functions/v1/_internal/health
Started supabase local development setup.
```
TODO:

fix: log url only for debugging http requests

---

pkg/function/batch.go

Bug fix
If two jobs deploy at the same time, one job may see the function slug as new, while the other one sees it as exists.
Adds error handling for POST response so that the next retry will be using PATCH.

fix: race condition when deploying from concurrent jobs

---

internal/db/start/start.go
internal/link/link.go
internal/link/link_test.go
internal/start/start.go
internal/start/templates/kong.yml
pkg/config/config.go
pkg/config/storage.go
pkg/config/templates/Dockerfile

Bug fix https://github.com/supabase/cli/issues/3425
Pins storage by migration name instead of image tag.

fix: pin storage migration instead of version

---

internal/services/services.go

Bug fix https://github.com/supabase/cli/issues/2473
No need to show storage version since we are autoupdating MT services.

fix: skip storage version when linking

---

pkg/function/batch.go
pkg/function/batch_test.go

Bug fix
Retry on 5xx error listing functions.

fix: retry on error listing functions

---

pkg/function/batch.go
pkg/function/batch_test.go

Bug fix
Also retries bulk update endpoint.

fix: retry bulk update endpoint on error

---

internal/start/start.go

Bug fix
JWKs for storage are sent using `AUTH_JWT_JWKS` instead of just `JWT_JWKS` this causes users using 3rd party auth to be unable to upload files locally
Pass JWKs as `JWT_JWKS` so storage will allow them for verification
Resolves: https://github.com/supabase/cli/issues/3362

fix: use correct env var name to pass auth jwks to storage container

---

pkg/config/constants.go

Bump edge-runtime to 1.68.0-develop.14
* bring back decorator flag in bundle command ([#538](https://github.com/supabase/edge-runtime/issues/538)) ([a1625a9](https://github.com/supabase/edge-runtime/commit/a1625a9293639d4b939ad6d207425db882c6e064))

fix: bump edge-runtime to 1.68.0-develop.14

---

pkg/config/constants.go
pkg/migration/queries/drop.sql

Bug fix https://github.com/supabase/cli/issues/3551
`identity restart` requires privilege to drop sequence, which is no longer granted to the postgres role.
Most of the time, there's no need to reset any sequences in managed schemas.

fix: do not restart auth sequence on reset

---

pkg/config/auth.go

Bug fix https://github.com/supabase/cli/issues/3557
API uses hour as unit instead of seconds.

fix: session timeout uses hour unit

---

internal/db/start/start.go
pkg/config/config.go
pkg/config/config_test.go

Bug fix
Since adopting nix build, our default platform collation is now consistent with our docker image.

fix: do not override collation on pg 15.8

---

internal/postgresConfig/update/update.go

Bug fix
Auto convert timeout fields to string.

fix: convert timeout fields to string

---

internal/db/diff/diff_test.go
internal/db/push/push_test.go
pkg/migration/file.go
pkg/migration/file_test.go
pkg/migration/queries/drop.sql

Bug fix
Underscores in SQL strings must be escaped.

fix: escape underscore in sql like syntax

---

internal/branches/create/create.go

Bug fix
When branch name is provided, do not set the current git branch.

fix: unset git branch when name is provided

---

internal/start/start.go

When trying to run supabase locally on windows, It checks if the docker daemon is properly exposed on `:2375` instead of printing a warning. 
If it is not running, it directs the user to the relevant documentation and gives a more verbose hint on how to solve the problem
If it is not exposed, supabase continues trying to start, and crashes with an obscure error message.
https://github.com/supabase/cli/issues/2505
Performs a get request on the docker daemon, and checks if it is available before running the analytics

fix: early fail on non-exposed docker daemon

---

cmd/db.go
cmd/migration.go
internal/db/reset/reset.go
internal/db/reset/reset_test.go
internal/migration/down/down.go
internal/migration/down/down_test.go

relates to https://github.com/supabase/cli/issues/611
Adds an alias for `db reset` so that it's easier to revert the last n migrations without inputting the full version string.
```
$ supabase db start
Seeding globals from roles.sql...
Applying migration 20250510162534_table.sql...
Applying migration 20250510162754_index.sql...
NOTICE (42P06): schema "supabase_migrations" already exists, skipping
Seeding data from supabase/seed.sql...
A new version of Supabase CLI is available: v2.23.4 (currently installed v)
We recommend updating regularly for new features and bug fixes: https://supabase.com/docs/guides/cli/getting-started#updating-the-supabase-cli
$ supabase migrations down
Connecting to local database...
Resetting local database to version: 20250510162534
Recreating database...
``` …

feat: alias migration down command as reset

---

pkg/config/config.go

Bug fix
Allows external packages to hold references to config object but not instantiate.

fix: expose pointer to config struct

---

.github/workflows/api-sync.yml

In the same spirit than dependabot and to have regular based api codegen updates:
- Periodically update and create a PR if there is diff between current API and cli codegen (everyday midnight)
- Can be manually run to create a PR that update the codegen to latest version.

chore(ci): add api-sync codegen automation workflow

---

internal/functions/serve/serve.go
internal/functions/serve/serve_test.go
internal/functions/serve/templates/main.ts
internal/functions/serve/watcher.go
internal/functions/serve/watcher_test.go
internal/utils/container_output.go
internal/utils/container_output_test.go

chore: add watcher tests and main.ts

---

internal/functions/serve/serve.go
internal/functions/serve/serve_test.go
internal/functions/serve/streamer.go
internal/functions/serve/streamer_test.go
internal/functions/serve/templates/main.ts
internal/functions/serve/testdata/config.toml
internal/functions/serve/watcher.go
internal/functions/serve/watcher_test.go
internal/testing/apitest/docker.go
internal/utils/container_output.go
internal/utils/container_output_test.go
internal/utils/docker.go

feat: hot reload eszip bundle when function source changes

---

internal/db/diff/diff.go
internal/db/diff/diff_test.go

Bug fix https://github.com/supabase/cli/issues/3827
Ensure database is started before querying user defined schemas.

fix: allow diff to run with stopped db

---

internal/migration/down/down_test.go
pkg/migration/drop.go
pkg/migration/drop_test.go
pkg/migration/queries/drop.sql
pkg/migration/queries/list.sql

Bug fix
Escape special characters in schema name with format string, ie. `_`

fix: escape drop schema statements

---

cmd/branches.go

Bug fix
Optional flag to create a data branch.

fix: flag to create data branch

---

internal/status/status.go
internal/storage/client/api.go
internal/utils/tenant/client.go
internal/utils/tenant/client_test.go
pkg/fetcher/gateway.go

Bug fix
CLI should prefer new api key over legacy ones.

fix: handle new tenant api key

---

pkg/fetcher/gateway.go

Bug fix https://github.com/supabase/cli/issues/3930
Backwards compatibility with legacy keys.

fix: add mysterious apikey header

---

internal/utils/tenant/client.go

Bug fix https://github.com/supabase/cli/issues/3934
The new secret key is masked unless we set the reveal flag.

fix: reveal new keys when loading from api

---

internal/gen/types/types.go

Bug fix https://github.com/supabase/cli/issues/3847
Since our debug proxy cannot negotiate ssl, always disable ssl when connecting in debug mode.

fix: disable ssl when connecting in debug mode

---

pkg/migration/scripts/dump_data.sh
pkg/migration/scripts/dump_role.sh
pkg/migration/scripts/dump_schema.sh

Bug fix https://github.com/supabase/cli/issues/3957
Temporary role must be stepped up to `postgres` for the necessary privileges to run pg_dump.

fix: set postgres role for pg_dump

---

internal/link/link.go
internal/services/services.go
internal/utils/tenant/client.go

Bug fix
New publishable key can't be used to access PostgREST schema.

fix: use service key for version checks

---

cmd/db.go
internal/db/diff/diff.go
internal/db/diff/diff_test.go
internal/db/diff/migra.go
internal/db/diff/pgschema.go
internal/db/diff/templates/migra.ts

Bug fix
Using pgkit/migra solves a few issues:
1. Cross schema references now works properly when multiple schemas are excluded
2. Triggers and RLS policies in managed schemas are now captured automatically
3. Extensions in all schemas can be included (previously was just `extensions` schema)
Uses edge runtime to execute migra also reduces the number of container images needed.
closes https://github.com/supabase/cli/issues/3919
closes https://github.com/supabase/cli/issues/3993
closes https://github.com/supabase/cli/issues/3379
closes https://github.com/supabase/cli/issues/3342
closes https://github.com/supabase/cli/issues/3234
closes https://github.com/supabase/cli/issues/1113
closes https://github.com/supabase/cli/issues/1514
closes https://github.com/supabase/cli/issues/2620

fix: diff schemas using pgkit migra

---

.github/workflows/ci.yml

ci
Separate coverage reporting since it's unreliable and often blocks CI.

chore: separate coverage reporting step

---

pkg/config/constants.go

https://github.com/supabase/edge-runtime/compare/v1.68.0-develop.37...v1.68.0-develop.39

fix: bump edge-runtime to 1.68.0-develop.39

---

internal/utils/flags/project_ref.go

- This introduce debug logs over the project ref loading helping debug where it come from when having invalid project ref loaded
Related #2915

fix(logs): add debug to LoadProjectRef

---

cmd/gen.go

Bug fix
Gen keys command was never working as intended.

fix: deprecate gen keys command

---

internal/db/diff/diff_test.go
internal/db/pull/pull.go
internal/db/pull/pull_test.go

Bug fix https://github.com/supabase/cli/issues/4068
Using the pgkit/migra implementation, we can reliably pull triggers and policies from managed schemas.
Hence, we can start doing that automatically instead of printing a suggestion.
For user defined schemas, use original migra to avoid revoking permissions.

fix: pull changes from managed schemas separately

---

internal/db/start/start.go

Chore
Consistent upload expiry URL value with cloud version

fix: consistent exp url as cloud version

---

internal/start/start.go
pkg/config/auth.go
pkg/config/templates/Dockerfile
pkg/config/templates/config.toml
pkg/config/testdata/config.toml

Add support for new OAuth server environment variables in local development:
- GOTRUE_OAUTH_SERVER_ENABLED
- GOTRUE_OAUTH_SERVER_ALLOW_DYNAMIC_REGISTRATION
- GOTRUE_OAUTH_SERVER_AUTHORIZATION_PATH
The feature isn't in GA yet in the platform, so skipping updating the remote config for now.

feat(auth): add OAuth server configuration support

---

internal/start/templates/kong.yml

Routes `/.well-known/oauth-authorization-server` from the base URL to the auth service to support OAuth 2.0 Authorization Server Metadata discovery.

feat(kong): Add `.well-known/oauth-authorization-server` endpoint

---

internal/db/start/start.go
internal/start/start.go
internal/start/templates/kong.yml
pkg/config/config.go

Bug fix
Translate opaque key to jwt when calling realtime.

fix: pass down apikey as query param to realtime
