- internal/init/templates/init_config
- internal/start/start.go
- internal/start/templates/kong_config
- internal/utils/utils.go
- Removed `ports.pgMeta`
- Added `ports.studio` (required)
- Unexpose pg-meta
- Expose Supabase Studio
> feat(start): add Supabase Studio

- internal/db/remote/set/set.go
> fix: Error conn busy on subsequent db remote set

- internal/db/reset/reset.go
Some of the migrations might depend on certain extensions. Running extensions *after* migrations breaks such migrations.
This PR should fix the issue by applying `extensions.sql` before any migrations. This is also the current behaviour of [`start`](https://github.com/supabase/cli/blob/main/internal/start/start.go#L548-L581) command.
`extensions.sql` is executed after all migrations on `db reset`
`extensions.sql` is executed before any migrations on `db reset`
> fix: Apply extensions.sql before migrations

- internal/utils/utils.go
> fix: use localhost instead of 0.0.0.0

- internal/start/start.go
feature
These are the new Realtime RLS env vars.
> feat: update Realtime configs for RLS

- internal/db/changes/changes.go
- internal/db/commit/commit.go
- internal/db/remote/commit/commit.go
- internal/db/reset/reset.go
- internal/start/start.go
> fix: first migration edge case

- internal/utils/templates/initial_schemas/13.sql
- internal/utils/templates/initial_schemas/14.sql
- internal/utils/templates/initial_schemas/README.md
- internal/utils/utils.go
feature
upgrade realtime image to v0.21.0
addresses https://github.com/supabase/realtime/issues/224
> feat: upgrade Realtime image to v0.21.0

- internal/db/remote/set/set.go
- internal/utils/utils.go
> fix(db remote set): make url less conservative

- internal/db/changes/changes.go
- internal/db/commit/commit.go
- internal/db/remote/changes/changes.go
- internal/db/remote/commit/commit.go
- internal/db/reset/reset.go
Follow up to https://github.com/supabase/cli/pull/163
> fix: support no tty for other commands

- internal/init/templates/init_config.toml
- internal/start/start.go
- internal/utils/config.go
> fix(start): misconfigured extra_search_path

- internal/start/start.go
> fix(studio): add missing env vars

- internal/functions/deploy/deploy.go
allows the user to deploy from within the `supabase/` dir, and allows deploying functions from any pwd if present
> Feature: allow deploys from within supabase/ and pwd

- go.mod
- go.sum
- internal/functions/deploy/deploy.go
- internal/login/login.go
- internal/utils/misc.go
Fixes #226
More general path fixes (incl. those w/o `~`) coming later
> fix: windows path

- internal/start/templates/kong_config
Fixes issue 2. mentioned here: https://github.com/supabase/supabase/issues/6267#issuecomment-1087106600
> fix: cors issue with functions serve

- internal/start/templates/kong_config
Support pg_graphql
Fixes #233.
> feat(start): support pg_graphql

- internal/start/templates/kong_config
Bug fix
Kong container repeatedly crashes, resulting in function serving not working.
Kong container starts properly and the `supabase function serve` command works as expected.
Kong CORS Config: https://github.com/Kong/kong/blob/21cc6f895bcf8af22da233e929e36ac0e4963321/kong/plugins/cors/schema.lua#L40
Thanks @falsidge for helping me hunt this one down.
> kong container repeated crashed due to incorrect config

- internal/start/templates/kong_config
> fix: Modify GraphQL endpoints

- internal/start/start.go
> fix(start): proper cleanup on error

- cmd/status.go
- internal/db/push/push.go
- internal/start/start.go
- internal/status/status.go
- internal/stop/stop.go
- internal/utils/misc.go
This PR is add the `status` command, which shows current status of supabase local development setup.
This feature is requested in #149 
This `status` command will be added, and `start` and `stop` command will be improved.
N/A
> feat: add status command

- cmd/link.go
- go.mod
- go.sum
- internal/functions/delete/delete.go
- internal/functions/deploy/deploy.go
- internal/link/link.go
- internal/link/link_test.go
- internal/login/login.go
- internal/testing/apitest/auth.go
- internal/testing/apitest/project.go
- internal/utils/misc.go
unit test, bug fix
- uses `afero.Fs` in link command
- moves regex pattern to `misc.go`
- adds `LoadAccessTokenFS` for testing
- fixes a bug with `MkdirIfNotExistFS` #306 
> test: add link command unit test

- cmd/orgs.go
- internal/orgs/list/list.go
- internal/orgs/list/list_test.go
> test: list organizations command

- cmd/secrets.go
- internal/projects/create/create_test.go
- internal/secrets/list/list.go
- internal/secrets/set/set.go
- internal/secrets/set/set_test.go
- internal/secrets/unset/unset.go
- internal/secrets/unset/unset_test.go
unit test
- set: 87.5%
- unset: 87.5%
> test: secret set and unset commands

- cmd/db.go
- internal/db/push/push.go
- internal/db/remote/changes/changes.go
- internal/db/remote/commit/commit.go
- internal/db/remote/set/set.go
- internal/functions/deploy/deploy.go
- internal/functions/new/new.go
- internal/init/init.go
- internal/link/link.go
- internal/utils/config.go
- internal/utils/config_test.go
- internal/utils/misc.go
refactoring
- compile more regex patterns in `utils` package
- defaults to use `MkdirAll`
> chore: some refactoring in preparation for migration test

- .github/workflows/ci.yml
- README.md
- add upload coverage report to coveralls
> add step to upload coveralls report

- cmd/db.go
- internal/db/commit/migra.go
- internal/db/commit/migra_test.go
- internal/db/commit/templates/migra.sh
- internal/db/commit/templates/reset.sh
- internal/db/remote/set/set_test.go
- internal/db/switch_/switch_.go
- internal/start/start.go
- internal/testing/pgtest/mock.go
- internal/utils/misc.go
experimental feature
pgadmin diff is verbose and sometimes incorrect
migra diff is more succinct and mostly correct
> expt: use migra to perform schema diff

- cmd/db.go
- internal/db/branch/delete/delete.go
- internal/db/branch/delete/delete_test.go
unit test
delete requires current branch
allows deletion without setting current branch
> fix: allow branch deletion without current branch

- internal/utils/misc.go
Sanity-checked locally on Slack Clone & Todo List examples.
Fixes #324.
> fix: update image versions

- internal/migration/new/new.go
- internal/migration/new/new_test.go
> fix: new migration pipe handler

- internal/link/link.go
postgres version check requires config to be set
> fix: link command not loading config

- internal/db/diff/diff.go
- internal/db/remote/changes/changes.go
- internal/db/remote/commit/commit.go
- internal/db/reset/reset.go
- internal/start/start.go
> fix: reuse create shadow db function

- cmd/secrets.go
- internal/link/link.go
- internal/link/link_test.go
- internal/secrets/list/list.go
- internal/secrets/list/list_test.go
- internal/secrets/set/set.go
- internal/secrets/set/set_test.go
- internal/secrets/unset/unset.go
- internal/secrets/unset/unset_test.go
- internal/utils/misc.go
- pkg/api/client.gen.go
- pkg/api/types.gen.go
- test/link_test.go
- test/secrets_test.go
> chore: switch to generated api client

- internal/secrets/set/set.go
- internal/secrets/set/set_test.go
> fix: secret set status code check

- cmd/db.go
- internal/db/push/push.go
- internal/db/remote/changes/changes.go
- internal/db/remote/commit/commit.go
- internal/link/link.go
Bug fix
`db remote changes` is broken
- prompt for password when `db remote changes`
- context cancellation
> fix: db remote commands

- internal/db/remote/commit/commit.go
- internal/db/remote/commit/templates/dump_initial_migration.sh
fixes `must be owner of extension "foo"`, `must be a member of role "supabase_admin"`
> fix: perms issues w/ pg_dump output

- cmd/db.go
- cmd/functions.go
- cmd/gen.go
- cmd/init.go
- cmd/link.go
- cmd/migration.go
- cmd/orgs.go
- cmd/projects.go
- cmd/root.go
- cmd/secrets.go
- cmd/start.go
- cmd/status.go
- cmd/stop.go
> chore: update command help messages

- internal/utils/prompt.go
Bug fix
press `q` doesn't return error
press `q` should abort immediately
> fix: check for interactive user aborting

- README.md
- cmd/db.go
> Release CLI v1

- README.md
BREAKING CHANGE: bump major version to v1
> chore: update readme title

- cmd/gen.go
- internal/db/remote/set/set.go
- internal/gen/types/typescript/typescript.go
- internal/gen/types/typescript/typescript_test.go
- internal/utils/docker.go
- internal/utils/docker_test.go
- internal/utils/misc.go
- test/main_test.go
Bug fix: https://github.com/supabase/cli/issues/372
- db password is not escaped
- container name is fixed
- container removal is not auto
- fixes issues above and adds unit tests
> fix: escape db password from postgres url

- internal/db/branch/create/create_test.go
- internal/db/branch/delete/delete_test.go
- internal/db/diff/diff.go
- internal/db/diff/migra.go
- internal/db/remote/changes/changes.go
- internal/db/remote/commit/commit.go
- internal/functions/serve/serve.go
- internal/gen/types/typescript/typescript_test.go
- internal/link/link_test.go
- internal/orgs/list/list_test.go
- internal/projects/create/create_test.go
- internal/projects/list/list_test.go
- internal/secrets/list/list_test.go
- internal/secrets/set/set_test.go
- internal/secrets/unset/unset_test.go
- internal/start/start.go
- internal/testing/apitest/helper.go
- internal/utils/container_output.go
- internal/utils/docker.go
- internal/utils/docker_test.go
Bug fix
type gen requires network id
makes network id optional
> fix: makes network id optional

- internal/utils/misc.go
> fix: update deno relay version to 1.2.1

- .github/workflows/mirror.yml
- internal/db/diff/migra.go
- internal/utils/misc.go
- tools/listdep/main.go
allows syncing of external docker images to ecr
> chore: add workflow for mirroring external deps

- README.md
docs update:
fixes https://github.com/supabase/cli/issues/338
> chore: update readme with go install steps

- internal/utils/templates/initial_schemas/13.sql
- internal/utils/templates/initial_schemas/14.sql
- internal/utils/templates/initial_schemas/README.md
Forgot to update w/ new migrations when upgrading the image versions in https://github.com/supabase/cli/commit/2990b5729f73f687fc352fe5baf6d86f973028fa
> fix: initial schemas

- internal/utils/config.go
> chore: remove deprecated config handling

- scripts/preinstall.js
> fix: windows preinstall script

- internal/utils/misc.go
Fixes https://github.com/supabase/postgres-meta/issues/332, fixes https://github.com/supabase/cli/issues/413, fixes https://github.com/supabase/cli/issues/385
> feat(typegen): views

- internal/utils/misc.go
Fixes https://github.com/supabase/cli/issues/422, fixes https://github.com/supabase/cli/issues/388
Pending on https://github.com/supabase/postgres-meta/pull/339
> feat(typegen): enums & function overloading

- cmd/functions.go
- internal/functions/deploy/deploy.go
- internal/functions/deploy/deploy_test.go
- internal/utils/misc.go
tests
- refactored deno path to utils
- pass in cancellation context
- extracted string and regex constants
- switch to codegen api client
> chore: add tests for function deploy

- cmd/functions.go
- internal/functions/new/new.go
- internal/functions/new/new_test.go
- internal/functions/new/templates/index.ts
tests
- embed typescript template as string
- adds context and in-memory fs
> chore: refactor and test function new

- cmd/functions.go
- internal/functions/delete/delete.go
- internal/functions/delete/delete_test.go
tests
- use codegen client
- handle cancellation
> chore: test function delete

- internal/utils/misc.go
update postgres image
v66 -> v71
working locally
> fix: update postgres image version

- internal/utils/container_output.go
For pgadmin schema diff. Fixes https://github.com/supabase/cli/issues/151.
> fix: include `create extension` in generated migration

- internal/db/reset/reset.go
- internal/start/start.go
refactor
use health probe when starting database
> chore: poll container health on supabase start

- internal/start/start.go
Bug fix #488 
mass rename fail
> fix: broken image name

- internal/utils/misc.go
- update `supabase/postgres-meta` with typegen improvements
- update `supabase/deno-relay` with GET request support
> fix: update images

- cmd/stop.go
- internal/stop/stop.go
- internal/stop/stop_test.go
- internal/utils/docker.go
- internal/utils/misc.go
> chore: add tests for stop command

- internal/utils/misc.go
- internal/utils/templates/initial_schemas/README.md
> chore: update realtime to v0.25.1

- internal/db/diff/migra.go
debug feature
prints the postgres statement where error occurred
> chore: print offending statement on migration error

- cmd/root.go
supersedes #426 
- run error
```bash
$ supabase db remote commit
Enter your database password:
Error: failed to connect to `project`: failed SASL auth (FATAL: SASL authentication failed (SQLSTATE 08P01))
Try rerunning the command with --debug to troubleshoot the error.
exit status 1
```
- unknown flag
```bash
$ supabase db -f
Error: unknown shorthand flag: 'f' in -f
Usage:
supabase db [command]
...
```
- missing root command
```bash
$ supabase missing
Error: unknown command "missing" for "supabase"
Run 'supabase --help' for usage.
exit status 1
```
> chore: improve help text for command error

- cmd/db.go
- tools/docgen/main.go
> chore: update reference docgen to include group tags

- internal/db/diff/migra.go
- internal/db/diff/migra_test.go
Minor Fix: Typo on error message.
N/A
N/A
N/A
> fix: error message typo

- cmd/orgs.go
- cmd/projects.go
- internal/orgs/list/list.go
- internal/orgs/list/list_test.go
Bug fix
cancellation not propagated
- handle signals
- handle nil response
> fix: handle signals in organization list

- internal/functions/serve/serve.go
- internal/functions/serve/serve_test.go
- internal/gen/types/typescript/typescript.go
- internal/gen/types/typescript/typescript_test.go
- internal/start/start.go
- internal/start/start_test.go
tests
also allows typegen to work with db start
> chore: improve test coverage for start command

- .github/workflows/ci.yml
- .github/workflows/mirror.yml
- go.mod
- go.sum
- internal/start/start_test.go
- internal/utils/docker.go
Bug fix
Only pulls from ECR as anonymous
Allows pulling as authenticated user, such as docker login action
> fix: authenticate using stored docker credentials

- internal/utils/templates/initial_schemas/13.sql
- internal/utils/templates/initial_schemas/14.sql
Bug fix
Linux devs are unable to connect to the database so Realtime database changes breaks.
Linux devs are able to connect to the database so Realtime database changes works.
Issue: https://github.com/supabase/realtime/issues/354
> fix: update Realtime encrypted DB host to 172.17.0.1

- internal/db/diff/migra.go
Bug fix #650
regression from #642
> fix: create shadow container without explicit name

- internal/utils/misc.go
Fixes https://github.com/supabase/cli/issues/635
> fix(typegen): bump pg-meta

- api/beta.yaml
- internal/functions/delete/delete.go
- internal/functions/deploy/deploy.go
- pkg/api/client.gen.go
- pkg/api/types.gen.go
> chore: update api spec to match production

- .github/workflows/ci.yml
- internal/utils/docker.go
> fix: allow alternative mirror registries

- .github/workflows/release.yml
- .goreleaser.yml
- README.md
- scripts/preinstall.js
releaser
- uploads archlinux package
- supports chocolatey for windows
> chore: add archlinux and chocolatey to release packages

- api/beta.yaml
- pkg/api/client.gen.go
- pkg/api/types.gen.go
api client
match latest staging
> chore: update api spec to latest

- internal/utils/misc.go
Bug fix #683
regex wasn't strict enough
add starting and termination characters
> fix: regex pattern for migration file

- tools/docgen/main.go
docs update
inherited flags don't show up properly
assume max 3 levels of command, for eg. `supabase`, `migration`, `new`
flatten inherited flags to leaf commands
https://github.com/supabase/supabase/pull/10952
> chore: update docgen to flatten out inherited flags

- cmd/link.go
- internal/db/remote/commit/commit.go
- internal/link/link.go
- internal/link/link_test.go
- internal/testing/pgtest/mock.go
- internal/utils/config.go
- internal/utils/misc.go
Bug fix #553
postgrest config is not linked to local
linking pg15 project throws error
- fetches postgrest config from remote
- linking pg15 project succeeds with warning
> fix: fetch postgrest config on linking

- internal/db/start/start.go
- internal/utils/config.go
- internal/utils/misc.go
- internal/utils/templates/initial_schemas/15.sql
> fix: support PG15 projects

- internal/db/remote/commit/commit.go
> fix: support db remote commit on PG15

- internal/utils/misc.go
Fixes a bug on previous pre-release https://github.com/PostgREST/postgrest/issues/2588
> fix: upgrade postgrest to v10.1.1.20221215

- cmd/bans.go
- cmd/restrictions.go
- cmd/root.go
- cmd/vanitySubdomains.go
- tools/docgen/main.go
docs update
- reduce code duplication
- generate ref docs with exp flag
https://github.com/supabase/supabase/pull/11108
> chore: declare experimental commands in one place

- internal/utils/misc.go
- internal/utils/templates/initial_schemas/15.sql
Bug fix #602
table columns are not consistently ordered
latest pg-meta sorts table columns by alphabetical order
> fix: update pg-meta for column ordering

- cmd/db.go
Bug fix #742
default pgadmin doesn't work with schema flag
switch default to migra so it aligns with documentation
> fix: default diff tool to migra

- internal/db/branch/switch_/switch__test.go
- internal/functions/deploy/deploy_test.go
- internal/utils/misc.go
Bug fix #735
Use the same deno version for first time deply
> fix: deno upgrade version mismatch

- cmd/db.go
- internal/db/diff/migra.go
- internal/db/diff/migra_test.go
- internal/db/diff/templates/migra.sh
- internal/db/lint/lint.go
- internal/db/remote/changes/changes.go
- internal/db/remote/commit/commit.go
- internal/start/start.go
- internal/utils/connect.go
- internal/utils/misc.go
- internal/utils/tea.go
- internal/utils/templates/initial_schemas/14.sql
- internal/utils/templates/initial_schemas/15.sql
feature
fixes #745
schema diffs must be manually specified
diffs all schemas by default
> feat: diffs all schemas by default

- internal/start/start.go
- internal/utils/misc.go
- internal/utils/templates/initial_schemas/15.sql
Bug fix #766
update pg15 image to match platform
> fix: update pg15 image to match platform

- internal/utils/misc.go
- internal/utils/templates/initial_schemas/13.sql
- internal/utils/templates/initial_schemas/14.sql
- internal/utils/templates/initial_schemas/15.sql
deps update
update pg13-pg15 with latest auth and realtime schemas
tested locally with db reset
> fix: update gotrue to match platform

- internal/functions/deploy/deploy.go
- internal/functions/serve/serve.go
- internal/utils/config.go
- internal/utils/misc.go
feature
Add `import_map` function config, as per https://github.com/supabase/cli/pull/786#pullrequestreview-1245150608.
Not sure how to test this, since the flag is just passed to the deno binary.
> feat: import_map function config

- internal/utils/misc.go
Reverts supabase/cli#824
fixes #827
> Revert "fix: update pgmeta to latest version"

- internal/db/diff/diff.go
- internal/functions/serve/serve.go
- internal/utils/docker.go
> chore: support binds in run with stream

- cmd/functions.go
> fix: function arg parser length check

- internal/utils/misc.go
> fix: update edge-runtime to 1.0.9

- internal/functions/serve/serve.go
> fix: make mounted functions directory writable

- .github/workflows/release.yml
- .goreleaser.yml
- package.json
> fix: create draft release before go build completes

- internal/db/diff/migra_test.go
- internal/utils/misc.go
Bug fix #894 
Exclude schemas from other known extensions.
> fix: ignore more extension schemas

- go.mod
- internal/utils/api.go
- internal/utils/api_test.go
- internal/utils/connect.go
unit tests
- allow ip lookup with host name only
- improve test coverage
> chore: refactor dns resolver for better test coverage

- .github/workflows/install.yml
closes https://github.com/supabase/cli/issues/885
not urgent
> chore: add pnpm to install matrix

- internal/db/diff/migra_test.go
- internal/utils/misc.go
- internal/utils/templates/initial_schemas/15.sql
chore
update service image versions
> fix: bump pg15 release to 52

- internal/db/push/push_test.go
- internal/link/link_test.go
- internal/migration/list/list_test.go
- internal/migration/repair/repair_test.go
- internal/utils/connect.go
- internal/utils/connect_test.go
Bug fix https://github.com/supabase/cli/issues/767
> fix: null pointer exception when connecting to remote

- internal/utils/misc.go
> fix: revert studio to last good version

- internal/db/diff/diff.go
- internal/db/dump/dump.go
- internal/functions/serve/serve.go
- internal/gen/types/typescript/typescript.go
- internal/utils/docker.go
Bug fix https://github.com/supabase/cli/issues/903
- use `host` network mode so that localhost resolves properly
> fix: run typegen in host network when db url is specified

- internal/utils/misc.go
Bug fix #908 
revert studio again
> fix: revert studio to fix storage page

- cmd/functions.go
- docs/main.go
- docs/supabase/init.md
- docs/supabase/link.md
- docs/supabase/migration/list.md
- docs/supabase/migration/new.md
- docs/supabase/migration/repair.md
- docs/supabase/status.md
- docs/templates/examples.yaml
docs update
adds migration docs
> chore: update docs with more migration examples

- internal/db/diff/migra.go
- internal/db/start/start.go
> fix: skip all migrations on pg14

- internal/db/diff/migra.go
Bug fix https://github.com/supabase/cli/issues/921
> fix: load custom roles when creating shadow db

- internal/functions/deploy/deploy.go
> fix: update deployed function url to use slug

- internal/utils/templates/initial_schemas/14.sql
- internal/utils/templates/initial_schemas/15.sql
Bug fix
Some migrations from gotrue, storage, and realtime are not included in initial schema
Regenerated schema.
> fix: update auth schema for pg14

- internal/db/diff/migra.go
helps to debug https://github.com/supabase/cli/issues/928
bubble up docker error
> fix: log schema diff error

- api/beta.yaml
- internal/utils/api.go
- pkg/api/client.gen.go
- pkg/api/types.gen.go
> chore: update generated api spec

- cmd/link.go
- docs/templates/examples.yaml
- go.mod
- internal/link/link.go
> fix: update password prompt help text

- cmd/sso.go
- internal/sso/create/create.go
- internal/sso/info/info.go
- internal/sso/internal/render/render.go
- internal/sso/internal/saml/files.go
- internal/sso/internal/saml/files_test.go
* The value of the flag `--type saml` is not being passed down to the underlying API call
* Fix a bug with the metadata url scheme validation
* Fix staticcheck errors
> fix: sso add cmd

- internal/db/start/start.go
- internal/utils/misc.go
Bug fix
- removes excessive polling logs from realtime
- write postgres logs to stdout
> fix: update realtime to reduce polling logs

- .github/workflows/mirror.yml
- tools/listdep/main.go
logflare
mirror logflare image
> chore: list logflare image as dependency for mirror job

- internal/db/diff/migra.go
- internal/db/diff/migra_test.go
- internal/db/start/start.go
Bug fix https://github.com/supabase/cli/issues/980
fixes missing function error.
tested locally with a migration file
> fix: revert entrypoint when using initial schema

- internal/db/diff/migra.go
- internal/db/start/start.go
- internal/utils/misc.go
- internal/utils/templates/initial_schemas/13.sql
- internal/utils/templates/initial_schemas/14.sql
- internal/utils/templates/initial_schemas/15.sql
Bug fix https://github.com/supabase/cli/issues/995
> fix: update storage image and migrations

- internal/status/status.go
- test/status_test.go
Closes https://github.com/supabase/cli/issues/990
> chore: show graphql url

- internal/utils/misc.go
> Revert "feat(typegen): generate types for materialized views"

- internal/functions/serve/serve.go
Fixes https://github.com/supabase/cli/issues/1017
> fix(functions): use absolute path on fallback import map when using relay

- internal/db/start/start.go
- internal/utils/misc.go
- internal/utils/templates/initial_schemas/15.sql
Bug fix https://github.com/supabase/cli/issues/1015
> fix: bump pg image to include vault

- internal/utils/misc.go
- internal/utils/templates/initial_schemas/13.sql
- internal/utils/templates/initial_schemas/14.sql
- internal/utils/templates/initial_schemas/15.sql
- internal/utils/templates/initial_schemas/README.md
see title. Not sure if we should keep all the realtime schema changes - lmk
> feat: bump gotrue to v2.60.7

- internal/utils/misc.go
Bug fix https://github.com/supabase/supabase/issues/13729
Update studio image with logflare fix
> fix: bump studio image to handle logflare key

- internal/utils/templates/globals.sql
Bug fix https://github.com/supabase/cli/pull/1032
Apply grant only when role is present.
> fix: global roles for pg13

- internal/utils/misc.go
relates to https://github.com/supabase/cli/issues/1020
updates version to fix axios import
> fix: update edge runtime version to 1.2.18

- internal/utils/templates/initial_schemas/15.sql
- internal/utils/templates/initial_schemas/README.md
- tools/dump_initial_schema.sh
Reverts supabase/cli#1066
temporarily revert this because it broke db diff
> Revert "chore: remove auth and storage from initial schemas"

- internal/db/reset/reset.go
- internal/db/reset/reset_test.go
Bug fix https://github.com/supabase/cli/issues/1073
> fix: restart realtime after db reset

- internal/utils/misc.go
Bug fix #1079 
fixes public bucket url
> fix: bump studio again

- internal/utils/templates/init_config.toml
Fix the guide link for local logs setup
> docs: fix local logs guide link

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/improve-documentation.md
Mostly to include the CLI version in the bug report template
> chore: update issue templates

- internal/db/diff/migra.go
- internal/db/reset/reset.go
Bug fix https://github.com/supabase/cli/issues/1085
shows git branch for now since local branching is a wip
> fix: show git branch in diff and reset output

- cmd/root.go
- docs/README.md
- docs/main.go
chore
Include CLI version in debug logs
> chore: log version string when debug flag is set

- internal/utils/parser/state.go
- internal/utils/parser/state_test.go
- internal/utils/parser/token_test.go
Bug fix https://github.com/supabase/cli/issues/610
- Handles new function body syntax: https://dba.stackexchange.com/a/300512
- Handles multiple statements in create rule: https://www.postgresql.org/docs/15/sql-createrule.html
> fix: handle begin atomic function body state

- .github/workflows/release-beta.yml
- package.json
Bug fix https://github.com/supabase/cli/issues/1150
Support beta release channel on npm
```bash
npx supabase@beta -h
```
> fix: support beta release channel

- internal/gen/types/typescript/typescript.go
Follow up to https://github.com/supabase/cli/pull/1149
> fix(typegen): wrong pg-meta file on `--db-url`

- internal/utils/misc.go
relates to https://github.com/supabase/supabase/pull/14737
> fix: update studio to enable log explorer

- internal/db/remote/commit/commit.go
- internal/migration/repair/repair.go
Bug fix https://github.com/supabase/cli/issues/1196
> fix: update migration table on remote commit

- README.md
> chore: add beta install instructions for brew

- internal/db/test/templates/test.sh
- internal/db/test/test.go
- internal/utils/docker.go
Bug fix https://github.com/supabase/cli/issues/1206
> fix: pg_prove installation script for ubuntu

- api/beta.yaml
- cmd/postgres.go
- cmd/root.go
- internal/postgresConfig/get/get.go
- internal/postgresConfig/update/update.go
- pkg/api/types.gen.go
Docs at https://github.com/supabase/supabase/pull/14963
> feat: add experimental command to specify custom Postgres config

- internal/db/diff/diff.go
- internal/db/diff/migra.go
- internal/db/diff/migra_test.go
- internal/utils/templates/initial_schemas/15.sql
- internal/utils/templates/initial_schemas/README.md
- tools/dump_initial_schema.sh
Bug fix https://github.com/supabase/cli/pull/1066
- creates shadow database by running service migrations (this is the same sequence as supabase start)
> fix: stop creating shadow database from initial schema

- api/beta.yaml
- pkg/api/client.gen.go
- pkg/api/types.gen.go
codegen
Updates openapi client to match prod
> chore: generate openapi client

- .github/workflows/release.yml
- tools/changelog/main.go
- tools/publish/main.go
- tools/selfhost/main.go
- tools/shared/github.go
> chore(tools): generate changelog with each stable release

- .golangci.yml
- cmd/functions.go
- cmd/inspect.go
- go.mod
- internal/functions/deploy/deploy.go
- internal/functions/list/list.go
- internal/functions/list/list_test.go
- internal/inspect/index_usage/index_usage.go
- internal/inspect/replication_slots/replication_slots.go
- internal/migration/apply/apply_test.go
- internal/orgs/list/list.go
- internal/postgresConfig/get/get.go
- internal/postgresConfig/update/update.go
- internal/projects/apiKeys/api_keys.go
- internal/projects/list/list.go
- internal/secrets/list/list.go
- internal/sso/update/update_test.go
- internal/testing/apitest/project.go
- internal/utils/deno.go
- internal/utils/docker.go
- internal/utils/misc.go
- internal/utils/parser/state_test.go
- internal/utils/parser/token.go
- test/db_test.go
ci
inspired by https://github.com/google/go-github/blob/master/.golangci.yml
> chore: apply stricter linter config

- .github/workflows/release.yml
- cmd/sso.go
- docs/main.go
- docs/supabase/login.md
- docs/templates/examples.yaml
- internal/utils/api.go
- tools/bumpdoc/main.go
- tools/selfhost/main.go
- tools/shared/github.go
ci
Make a PR to docs repo when we release cli stable.
> chore: publish reference docs on stable release

- .github/workflows/release.yml
- go.mod
- go.sum
- tools/changelog/main.go
tools
Posts changelog via slack bot https://supabase.slack.com/apps/A05E67Y0ECC-cli-release-bot?settings=1&tab=settings
> chore(tools): announce changelog in slack channel

- internal/db/push/push_test.go
- internal/link/link_test.go
- internal/migration/apply/apply_test.go
- internal/migration/repair/repair.go
- internal/migration/repair/repair_test.go
- internal/migration/squash/squash.go
- internal/migration/squash/squash_test.go
- internal/utils/misc.go
feature
Update migration name for display on dashboard.
> feat(migration): add migration name to history table

- tools/changelog/main.go
- tools/shared/github.go
tools
https://github.com/supabase/cli/actions/runs/5384984053/jobs/9773519957
As committed
> chore(tools): misc fixes for release jobs

- cmd/orgs.go
- internal/orgs/create/create.go
- internal/orgs/create/create_test.go
- internal/orgs/list/list.go
feature
```bash
supabase orgs create <name>
```
> feat: implement command to create organization

- internal/db/reset/reset.go
- internal/db/reset/reset_test.go
Bug fix https://github.com/supabase/cli/issues/1255
> fix: db reset should apply initial schema before service restart

- tools/shared/github.go
> chore(tools): update pr error handling

- cmd/functions.go
- internal/functions/serve/serve.go
- internal/functions/serve/serve_test.go
- internal/start/start.go
- internal/start/start_test.go
- internal/start/templates/kong.yml
- internal/start/templates/vector.yaml
- internal/status/status.go
- internal/stop/stop_test.go
- internal/utils/config.go
- internal/utils/misc.go
Follow up to https://github.com/supabase/cli/pull/1171
> chore: remove deno relay code

- internal/utils/deno.go
- internal/utils/deno_darwin.go
- internal/utils/deno_generic.go
Fixes https://github.com/supabase/cli/issues/1266
> fix: deno binary arch

- cmd/db.go
Doesn't actually change the logic, but makes it clearer.
> fix(db diff): change `local` flag default value

- internal/utils/misc.go
> fix: update studio to v0.23.06

- internal/link/link.go
> fix: create temp directory before linking gotrue

- api/beta.yaml
- pkg/api/client.gen.go
follow up https://github.com/supabase/cli/pull/1313
staging route changed
> fix: update branch api route

- cmd/branches.go
- internal/branches/create/create.go
- internal/utils/api.go
follow up https://github.com/supabase/cli/pull/1313
It would be helpful to select the branch region closest to the developer.
> feat: support branch region flag

- internal/db/push/push.go
> fix: do not push seed and role when dry run

- internal/utils/misc.go
> fix(auth): update gotrue version to 2.82.4

- internal/db/remote/commit/commit.go
> fix: initial remote commit should include all schemas

- internal/functions/serve/serve.go
chore
Add a health check for edge runtime.
> chore: add health check for edge runtime

- cmd/db.go
- docs/supabase/db/pull.md
- docs/supabase/db/remote-commit.md
- internal/db/diff/migra_test.go
- internal/db/pull/pull.go
- internal/db/pull/pull_test.go
feature
- `db pull` with a prompt to update migration history table
- deprecate db remote commit
> feat: add db pull command

- internal/functions/serve/serve.go
> Revert "chore: add health check for edge runtime"

- internal/db/reset/reset.go
fixes https://github.com/supabase/cli/issues/1384
> fix: add required gotrue env to db reset

- internal/start/start.go
- internal/utils/config.go
- internal/utils/templates/init_config.test.toml
- internal/utils/templates/init_config.toml
closes https://github.com/supabase/cli/issues/1375
> feat(auth): support twilio verify in sms config

- internal/start/start.go
- internal/stop/stop.go
follow up https://github.com/supabase/cli/pull/1396
Misunderstood the desired behaviour.
Stops inbucket from creating excessive anonymous volumes.
> fix: avoid creating anonymous volumes for inbucket

- scripts/postinstall.js
> feat: add verifying checksums for downloaded binary

- internal/start/templates/vector.yaml
platform remaps log level to LOG instead of info, discrepancy results in issues with studio logs ui filtering
> fix: remap info level to log level for postgres logs

- internal/start/start.go
- internal/utils/config.go
- internal/utils/templates/init_config.test.toml
- internal/utils/templates/init_config.toml
closes https://github.com/supabase/cli/issues/1366
> feat(config): allow disabling services via config file

- internal/start/start.go
- internal/start/start_test.go
- internal/status/status.go
- internal/utils/config.go
Bug fix https://github.com/supabase/cli/issues/1413
Bug fix https://github.com/supabase/cli/issues/1412
> fix: pull docker images only when needed

- api/beta.yaml
- internal/branches/list/list.go
- internal/link/link.go
- internal/link/link_test.go
- pkg/api/client.gen.go
- pkg/api/types.gen.go
> chore: update codegen client

- internal/utils/misc.go
Bug fix
- https://github.com/supabase/supabase/pull/17136
- https://github.com/supabase/supabase/pull/16809
Tested locally
> fix(studio): bump studio image for offline support

- cmd/db.go
- cmd/inspect.go
- cmd/migration.go
- cmd/root.go
- cmd/test.go
- internal/db/diff/migra.go
- internal/db/diff/migra_test.go
- internal/utils/flags/db_url.go
feature
Every command that connects to database now supports `--linked`, `--local`, and `--db-url` flag.
> feat: support --local and --linked flags

- internal/projects/list/list.go
fixes https://github.com/supabase/cli/issues/1454
```
$ supabase projects list
LINKED │        ORG ID         │          ID          │      NAME       │           REGION           │  CREATED AT (UTC)
─────────┼───────────────────────┼──────────────────────┼─────────────────┼────────────────────────────┼──────────────────────
│ rational-plum-7caw0qf │ hogtqaeecjvfylegvotq │ test-aws        │ Southeast Asia (Singapore) │ 2023-08-21 05:54:47
●    │ rational-plum-7caw0qf │ nlhaskwsizylhnffaqkd │ preview-example │ sin                        │ 2023-07-14 05:59:16
```
> fix(api): show locally linked project when listing

- internal/db/diff/diff.go
- internal/db/lint/lint.go
- internal/db/lint/lint_test.go
- internal/db/reset/reset.go
- internal/db/reset/reset_test.go
follow up https://github.com/supabase/cli/pull/1438
> fix: incorrect check for localhost connection

- internal/utils/flags/db_url.go
> fix: db url flag should take precedence when set

- internal/utils/misc.go
> feat: bump gotrue version to v2.92.1

- internal/db/reset/templates/drop.sql
follow up https://github.com/supabase/cli/pull/1490
> fix: reset remote should drop all policies

- docs/main.go
- internal/utils/config.go
> chore: support link type when generating docs

- internal/db/diff/diff.go
- internal/db/diff/migra.go
- internal/db/diff/migra_test.go
> fix: 3x shadow database start timeout

- internal/db/diff/diff.go
- internal/db/diff/migra.go
- internal/db/start/start.go
- internal/utils/misc.go
Bug fix https://github.com/supabase/cli/issues/1415
>  fix: increase health timeout to 120s

- cmd/db.go
- cmd/migration.go
- cmd/test.go
Bug fix https://github.com/supabase/cli/issues/1497
> fix: flag parsing for default local commands

- internal/db/dump/templates/dump_schema.sh
> fix(db): use idempotent statements when dumping triggers

- internal/db/start/start.go
- internal/link/link.go
- internal/link/link_test.go
- internal/services/services.go
- internal/start/start.go
- internal/start/start_test.go
- internal/status/status.go
- internal/utils/config.go
- internal/utils/misc.go
- internal/utils/tenant/client.go
- internal/utils/tenant/storage.go
- internal/utils/tenant/storage_test.go
feature
sync remote storage api version to local
> feat(storage): link storage api version with remote

- internal/utils/misc.go
> feat: update gotrue version to 2.99.0

- .github/workflows/install.yml
> chore: add tests for bun and yarn berry installation

- README.md
docs https://github.com/supabase/cli/issues/1565
> chore: update readme for bun users

- internal/db/start/start.go
- internal/utils/config.go
relates to https://github.com/supabase/cli/issues/1576
Allows loading custom root key via `SUPABASE_DB_ROOT_KEY` env var.
> feat: support custom encryption root key for local dev

- internal/storage/client/buckets.go
- internal/storage/client/objects.go
- internal/utils/api.go
- internal/utils/deno.go
- internal/utils/http.go
- internal/utils/tenant/client.go
chore
Reduce code duplication.
> chore: unify json http client implementation

- internal/utils/misc.go
> fix(studio): update image version to 20231023

- internal/utils/http.go
> chore: add user agent for other http client

- cmd/root.go
> fix: mark storage command as experimental

- internal/utils/denos/extract.ts
> Revert "fix: no need to decompress buffer when downloading functions"

- internal/functions/list/list.go
> fix: reformat functions list output

- internal/start/start.go
- internal/start/start_test.go
- internal/start/templates/kong.yml
- internal/status/status.go
fixes https://github.com/supabase/cli/issues/1637
> fix: start postgrest admin endpoint for health check

- internal/start/start.go
- internal/utils/misc.go
Bug fix https://github.com/supabase/cli/issues/1590
> fix(studio): update studio api to proxy pgmeta query

- cmd/root.go
- internal/functions/new/new.go
- internal/functions/new/new_test.go
- internal/functions/new/templates/index.ts
- internal/utils/misc.go
supersedes https://github.com/supabase/cli/pull/1473
> fix: templatize index.ts for new functions

- internal/functions/new/templates/index.ts
feature
Make it easy for developers to invoke functions locally by including cli setup instruction `supabase start` in functions template comment.
> feat: add cli instructions to invoke functions locally

- internal/utils/misc.go
- internal/utils/templates/initial_schemas/14.sql
Bug fix https://github.com/supabase/cli/issues/1665
> fix(storage): update default storage version to 0.43.11

- internal/utils/config.go
Bug fix https://github.com/supabase/cli/issues/1676
> fix: experimental version comparison for orioledb

- internal/utils/misc.go
fixes https://github.com/supabase/cli/issues/1684
fixes https://github.com/supabase/cli/issues/1683
fixes https://github.com/supabase/cli/issues/1682
> fix: update studio to 20231123-64a766a

- internal/gen/types/typescript/typescript.go
- internal/utils/misc.go
https://github.com/supabase/postgres-meta/compare/v0.68.0...v0.75.0
Main changes are:
- detect one-to-one relationships
- deterministic sorting order for polymorphic functions and relationships
- better typing for function columns with a composite type
- generate Table & Enum helper types
> feat: pg-meta 0.75.0

- api/beta.yaml
- cmd/branches.go
- internal/branches/list/list.go
- internal/orgs/create/create_test.go
- internal/orgs/list/list_test.go
- pkg/api/client.gen.go
- pkg/api/types.gen.go
feature
```
supabase --experimental branches update <branch-id> --reset-on-push
supabase --experimental branches update <branch-id> --reset-on-push=false
```
> feat: allow preview branch to be reset on push

- cmd/init.go
- internal/db/start/start.go
- internal/utils/config.go
- internal/utils/templates/init_config.test.toml
- internal/utils/templates/init_config.toml
feature
Updates orioledb image with s3 support.
> feat: support s3 config for orioledb

- internal/db/diff/templates/migra.sh
Bug fix https://github.com/supabase/cli/issues/1716
> fix: always diff privileges using migra

- internal/utils/misc.go
bump gotrue version to v2.125.1 for parity with platform
> feat: bump gotrue to v125.1

- internal/utils/templates/initial_schemas/13.sql
- internal/utils/templates/initial_schemas/14.sql
Bug fix https://github.com/supabase/supabase/issues/19620
Forgot to update schema when auth was updated: https://github.com/supabase/cli/pull/1729
> fix(auth): update auth schema for pg14

- internal/utils/misc.go
> feat(db): update postgres image to 15.1.0.147

- cmd/db.go
related https://github.com/supabase/supabase/pull/19728
> chore: update help message for reset flags

- internal/utils/flags/project_ref.go
Bug fix https://supabase.sentry.io/issues/4757277602/?alert_rule_id=14867193&alert_type=issue&notification_uuid=18bd4475-2458-4a65-acf4-18d060c224b7&project=4506382322302976&referrer=issue_alert-slack
> fix: assign linked project ref to global variable

- package.json
follow up https://github.com/supabase/cli/pull/1791
> fix: disable http agent keep alive for postinstall

- .github/workflows/pg-prove.yml
- .github/workflows/publish-migra.yml
> chore: debug github output for publish job

- internal/utils/misc.go
> fix(studio): bump studio image to 20240101-8e4a094

- internal/utils/config.go
Bug fix https://github.com/supabase/cli/issues/1839
Ignore temp version files which don't match config.toml.
> fix: ensure major version matches temp file

- docs/supabase/link.md
- docs/supabase/migration/repair.md
- docs/templates/examples.yaml
- internal/db/pull/pull.go
- internal/migration/list/list.go
- internal/migration/list/list_test.go
- internal/migration/up/up.go
- internal/utils/docker.go
closes https://github.com/supabase/cli/issues/1623
Additional documentation for db pull.
> fix(db): improve suggestion on db pull failure

- internal/utils/config.go
Bug fix https://github.com/supabase/cli/issues/1877#issuecomment-1909695253
pg15 patch versions below 55 are not supported.
> fix(db): exclude unsupported pg15 patch versions from loading

- internal/start/start.go
Bug fix https://github.com/supabase/cli/issues/1872
> fix: ignore access token error when syncing image versions

- internal/utils/connect.go
Bug fix
Allow connecting to staging pooler for testing.
> fix(pooler): allow supabase.green domain in pooler url

- cmd/link.go
- cmd/projects.go
- internal/utils/prompt.go
- Support delete proejct using interactive mode
[1694](https://github.com/supabase/cli/issues/1694)
> feat: provide interactive support for project deletion

- go.mod
- go.sum
- internal/db/diff/migra.go
- internal/db/diff/migra_test.go
- internal/functions/deploy/deploy.go
Bug fix
`functions deploy` may fail sporadically due to api not handling concurrent updates.
Retry deploying the function 3 times with exponential backoff.
> fix(functions): retry with backoff on deploy failure

- cmd/storage.go
- internal/storage/client/objects.go
- internal/storage/cp/cp.go
feature
closes https://github.com/supabase/cli/issues/1895
- additional controls over upload headers, doesn't affect download behaviour
```bash
supabase --experimental storage cp log.txt ss:/// \
--cache-control 'max-age=3600' \
--content-type 'text/html; charset=utf-8'
```
> feat(storage): support custom file options for upload

- api/beta.yaml
- cmd/projects.go
- internal/branches/list/list.go
- internal/projects/create/create.go
- internal/projects/create/create_test.go
- internal/utils/flags/project_ref.go
- internal/utils/prompt.go
- pkg/api/client.gen.go
- pkg/api/types.gen.go
Bug fix
Since `plan` flag is deprecated in favour of org level billing, hide it from project creation command.
> feat: create project interactively by default

- internal/gen/types/typescript/typescript.go
- internal/utils/config.go
Bug fix https://github.com/supabase/cli/issues/1826
> fix(typegen): use default schemas only if flag is not specified

- internal/utils/connect.go
- internal/utils/connect_test.go
> fix(pooler): support reference field in url options

- internal/utils/config.go
- internal/utils/docker.go
> fix: handle spaces in version string

- internal/utils/connect.go
- internal/utils/connect_test.go
> fix: handle raw ipv6 address in --db-url flag

- cmd/link.go
- internal/link/link.go
- internal/link/link_test.go
Bug fix https://github.com/supabase/cli/issues/1967
regression from https://github.com/supabase/cli/pull/1961
> fix: load db config after fetching pooler url

- internal/db/dump/dump.go
- internal/db/dump/templates/dump_schema.sh
Bug fix https://github.com/supabase/cli/issues/1964
Regression due to https://dba.stackexchange.com/a/323380
> fix: dump extensions when schema flag is absent

- internal/utils/misc.go
As per title, deployment for last region is underway so please wait a while before merging
Upd: deployment is done
> feat: upgrade auth to v2.143

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/install.yml
- .github/workflows/release-beta.yml
> chore: update ci scripts to run against develop

- go.mod
- go.sum
- internal/utils/docker.go
- internal/utils/output.go
- tools/selfhost/main.go
> fix: use yaml v3 in tools

- cmd/login.go
- go.mod
- internal/login/login.go
- internal/utils/tea.go
Bug fix https://github.com/supabase/cli/issues/2040
Users can open the login link manually if browser fails to open automatically.
> fix: log and ignore error opening browser

- internal/utils/misc.go
Fixes some typegen-related issues https://github.com/supabase/postgres-meta/compare/v0.79.0...v0.79.5
- fixes https://github.com/supabase/cli/issues/1513
- fixes https://github.com/supabase/cli/issues/1329
> fix: pg-meta v0.79.5

- .github/workflows/ci.yml
- internal/start/start_test.go
- internal/utils/templates/init_config.toml
This reverts commit 43b07dbe7b7d86d78f0def5a2c5b7d45ac45b7b7.
> Revert "fix: enable analytics by default (#1919)"

- cmd/projects.go
> fix: ref string validation when deleting project

- internal/migration/up/up.go
- internal/migration/up/up_test.go
Bug fix https://github.com/supabase/cli/issues/2063
> fix: suggest reverting specific history on mismatch

- internal/utils/misc.go
Generates types for foreign tables: https://github.com/supabase/postgres-meta/pull/754
> feat: pg-meta v0.80.0

- cmd/bootstrap.go
- cmd/init.go
- internal/bootstrap/bootstrap.go
- internal/init/init.go
- internal/init/init_test.go
- internal/utils/config.go
feature
`supabase init --force` will now overwrite existing config.toml.
> feat: add option to bootstrap from scratch

- internal/bootstrap/bootstrap.go
- internal/bootstrap/bootstrap_test.go
> fix: add scheme to supabase url for bootstrap

- internal/bootstrap/bootstrap.go
> fix: seed database after bootstrap

- docs/templates/examples.yaml
- internal/db/pull/pull.go
- internal/db/remote/commit/commit.go
- internal/migration/repair/repair.go
> fix: add usage example for db pull

- internal/bootstrap/bootstrap.go
- internal/functions/deploy/deploy.go
> feat: deploy all functions after bootstrap

- internal/bootstrap/bootstrap.go
> fix: skip deploying functions in bootstrap

- internal/bootstrap/bootstrap.go
> fix: relative path from repo root directory

- README.md
> chore: prepare readme for GA announcement

- internal/functions/serve/templates/main.ts
Refactor
* Resolves a previously intermittent `Status is not defined` issue.
* Enhances Edge-Runtime specific error handling. (BootError, WorkerLimit, WorkerRequestCancelled)
* Make the decorator feature enabled on the user worker (tc39 proposal)
* Add the `onError` callback.
> ~~Note: This PR should be merged when the CLI bumps the edge-runtime image to v1.43.0 or higher.~~
cc @laktek
> fix(functions): realign main service script

- internal/migration/squash/squash.go
- internal/migration/squash/squash_test.go
Bug fix https://github.com/supabase/cli/issues/2071
Oversight when starting shadow db.
> fix: wait for healthy database on squash

- internal/status/status.go
- internal/status/status_test.go
- internal/utils/config.go
> chore: update variable names

- internal/start/start.go
- internal/status/status_test.go
- internal/utils/config.go
- internal/utils/templates/init_config.test.toml
- internal/utils/templates/init_config.toml
related https://github.com/supabase/cli/issues/1414
Allows disabling image transform locally via config.toml
> feat: support disabling image transformation from config

- internal/start/start.go
- internal/utils/config.go
- internal/utils/templates/init_config.test.toml
- internal/utils/templates/init_config.toml
closes https://github.com/supabase/cli/issues/1847
fixes https://github.com/supabase/cli/issues/1547
> feat: support skipping nonce check for google signin

- internal/utils/templates/init_config.test.toml
- internal/utils/templates/init_config.toml
> Revert "fix: expose inbucket smtp port by default"

- internal/start/start.go
relates to https://github.com/supabase/cli/issues/2177
regression from https://github.com/supabase/cli/pull/2169
https://github.com/supabase/setup-cli/actions/runs/8731193153
> fix: add realtime cmd for backwards compatibility

- cmd/bootstrap.go
- cmd/logout.go
- internal/bootstrap/bootstrap.go
- internal/db/pull/pull.go
- internal/db/push/push.go
- internal/db/push/push_test.go
- internal/db/reset/reset.go
- internal/init/init.go
- internal/link/link_test.go
- internal/logout/logout.go
- internal/logout/logout_test.go
- internal/migration/repair/repair.go
- internal/migration/repair/repair_test.go
- internal/migration/squash/squash.go
- internal/projects/create/create.go
- internal/projects/delete/delete.go
- internal/storage/rm/rm.go
- internal/testing/fstest/stdin.go
- internal/utils/console.go
- internal/utils/prompt.go
Bug fix
Enhanced support for piping input from stdin.
```bash
yes | supabase init
```
> fix: parse prompt answer from non-interactive stdin

- internal/db/reset/reset.go
- internal/db/reset/reset_test.go
- internal/db/reset/templates/drop.sql
- internal/projects/delete/delete.go
- internal/storage/rm/rm.go
- internal/storage/rm/rm_test.go
Bug fix: https://github.com/supabase/cli/issues/1875
> fix: defaults to no when confirming delete operations

- cmd/bootstrap.go
- cmd/branches.go
- internal/projects/create/create.go
- internal/utils/console.go
Bug fix
Also prints error only in debug mode.
https://unix.stackexchange.com/questions/380012/why-does-bash-interactive-shell-by-default-write-its-prompt-and-echoes-its-inter
> fix: stdin should be echoed to stderr by convention

- internal/utils/misc.go
> fix(db): bump postgres image to 15.1.1.41

- internal/utils/config.go
Bug fix https://github.com/supabase/cli/issues/1518
Precedence order: https://github.com/bkeepers/dotenv?tab=readme-ov-file#customizing-rails
> fix: load multiple env files by convention

- cmd/storage.go
- internal/storage/client/api.go
- internal/storage/client/scheme.go
- internal/storage/client/scheme_test.go
- internal/storage/cp/cp.go
- internal/storage/cp/cp_test.go
- internal/storage/ls/ls.go
- internal/storage/ls/ls_test.go
- internal/storage/mv/mv.go
- internal/storage/mv/mv_test.go
- internal/storage/rm/rm.go
- internal/storage/rm/rm_test.go
- pkg/fetcher/http.go
- pkg/storage/api.go
- pkg/storage/buckets.go
- pkg/storage/objects.go
feature
```bash
supabase --experimental storage cp --local --recursive /tmp/file ss:///tmp/file
```
> feat(storage): support copying files to local storage api

- internal/utils/misc.go
> fix: add realtime admin to reserved roles

- internal/functions/serve/serve.go
- internal/secrets/set/set.go
- internal/secrets/set/set_test.go
Bug fix https://github.com/supabase/cli/issues/1834
Warns and skips env names reserved by supabase.
> fix: warn env names with supabase prefix

- internal/migration/list/list.go
- internal/migration/up/up.go
- internal/migration/up/up_test.go
Bug fix https://github.com/supabase/cli/issues/2255
Added 2 unit tests for out of bounds error.
> fix: index out of bound when applying migrations

- internal/db/diff/pgadmin.go
- internal/db/remote/commit/commit.go
Bug fix https://github.com/supabase/cli/issues/2259
> fix: create migrations dir before saving diff

- internal/utils/misc.go
> fix: update auth version to 2.151.0

- internal/db/dump/dump.go
Bug fix
pg_dump ignores upper case table names by default. Always enclose in double quotes for case sensitive match.
> fix(db): escape upper case table names for dump

- go.mod
- go.sum
- internal/functions/download/download_test.go
> Revert "chore(deps): bump github.com/docker/cli from 26.1.2+incompatible to 26.1.3+incompatible"

- cmd/bootstrap.go
- cmd/branches.go
- cmd/init.go
- cmd/inspect.go
- cmd/projects.go
- internal/bootstrap/bootstrap.go
- internal/branches/create/create.go
- internal/db/pull/pull.go
- internal/db/push/push.go
- internal/db/reset/reset.go
- internal/init/init.go
- internal/init/init_test.go
- internal/logout/logout.go
- internal/logout/logout_test.go
- internal/migration/fetch/fetch.go
- internal/migration/repair/repair.go
- internal/migration/squash/squash.go
- internal/projects/create/create.go
- internal/projects/delete/delete.go
- internal/storage/rm/rm.go
- internal/utils/console.go
- internal/utils/console_test.go
- test/branch_test.go
- test/db_test.go
- test/init_test.go
- test/link_test.go
- test/login_test.go
- test/secrets_test.go
- test/status_test.go
Bug fix https://github.com/supabase/cli/issues/2238
- Adds timeout when waiting for input from stdin.
- Supports cancellation when input is interrupted. 
> fix: timeout waiting for input from non-interactive prompt

- internal/utils/console.go
regression https://github.com/supabase/cli/pull/2318
Close token channel after reading stdin.
> fix: regression on multiline console input

- api/beta.yaml
- internal/postgresConfig/get/get.go
- internal/postgresConfig/update/update.go
- internal/projects/list/list.go
- internal/utils/flags/project_ref.go
- internal/utils/tenant/database.go
- internal/vanity_subdomains/delete/delete.go
- pkg/api/client.gen.go
- pkg/api/types.gen.go
chore
Generate clients for `v1/projects/ref/config/database/pooler` route.
> chore: update openapi spec for pooler config

- internal/db/diff/diff_test.go
- internal/db/dump/dump.go
- internal/db/pull/pull_test.go
- internal/db/reset/reset_test.go
- internal/db/start/templates/schema.sql
- internal/services/services.go
- internal/start/start.go
- internal/start/templates/pooler.exs
- internal/utils/config.go
- internal/utils/misc.go
feature
Replaces deprecated pgbouncer with supavisor while maintaining the same config.
> feat: replace pgbouncer with supavisor

- internal/db/start/start.go
- internal/functions/deploy/deploy.go
- internal/functions/download/download.go
- internal/functions/serve/serve.go
- internal/login/login_linux.go
- internal/utils/docker.go
- internal/utils/docker_darwin.go
- internal/utils/docker_linux.go
- internal/utils/docker_windows.go
relates to https://github.com/supabase/cli/issues/265
Implement OS specific docker host config.
> fix: resolve host network consistently within containers

- internal/start/start.go
relates to https://github.com/supabase/supabase/pull/26858
> fix: pass jwt secret to studio container

- internal/utils/enum.go
- internal/utils/misc.go
https://supabase.slack.com/archives/C01KSDNKNCW/p1717078471476879
Make debugging easier.
>  fix: log workdir if different from cwd

- cmd/secrets.go
- internal/secrets/list/list.go
- internal/secrets/set/set.go
- internal/secrets/set/set_test.go
- internal/secrets/unset/unset.go
closes https://github.com/supabase/cli/issues/1235
closes https://github.com/supabase/cli/issues/1560
- Prompts to confirm unsetting secret.
- Unsets all user defined secrets by default.
- Sorts secrets by alphabetical order.
> feat: unset all secrets when no arg is supplied

- internal/migration/list/list.go
- internal/utils/deno.go
- internal/utils/deno_test.go
- internal/utils/render.go
Bug fix: https://github.com/supabase/cli/issues/1338
Directory path in import map must be suffixed with slash.
>  fix: suffix resolved import directory with slash

- internal/utils/deno.go
Bug fix https://github.com/supabase/cli/issues/2409
Resolve host import map path to absolute for docker bind mount.
> fix: resolve absolute import map path for bind mount

- docs/supabase/migration/squash.md
relates to https://github.com/supabase/cli/issues/1618
Document caveats of migration squash.
> chore: extended documentation for migration squash

- internal/utils/misc.go
Bug fix https://github.com/supabase/cli/issues/2224
> fix(db): bump postgres to 15.1.1.61

- internal/functions/new/templates/index.ts
Deno change the way to import global types. 
source here: https://github.com/denoland/vscode_deno/issues/1115
> chore: update edge functions template.

- internal/start/start.go
- internal/utils/config.go
- internal/utils/templates/init_config.test.toml
- internal/utils/templates/init_config.toml
Adds the Auth session timeouts configs to the CLI.
Same as #1632 but GH won't let me reopen it.
> feat(auth): support session timeout configs

- internal/utils/misc.go
> fix: bump PostgREST to 12.2.0

- internal/db/start/start.go
- internal/start/start.go
- internal/start/start_test.go
- internal/start/templates/vector.yaml
- internal/utils/templates/init_config.test.toml
- internal/utils/templates/init_config.toml
> fix: start analytics service by default

- internal/start/start.go
Bug fix https://github.com/supabase/cli/pull/2339#issuecomment-2201580014
Add jwt secret to the correct container.
> fix: add jwt secret env to studio instead of pgmeta

- cmd/seed.go
- internal/seed/buckets/buckets.go
- internal/start/start.go
- internal/start/start_test.go
- internal/storage/client/api.go
- internal/storage/cp/cp.go
- internal/utils/config.go
- internal/utils/misc.go
- internal/utils/templates/init_config.test.toml
- internal/utils/templates/init_config.toml
- pkg/storage/buckets.go
> feat(storage): seed buckets locally from config file

- internal/functions/serve/serve.go
relates https://github.com/supabase/cli/issues/2456
`nat.ParsePortSpecs` always returns an exposed port, which is unnecessary.
> fix: no need to expose edge runtime port

- internal/functions/serve/templates/main.ts
> fix: update edge runtime memory limit to match hosted

- internal/db/diff/diff.go
- internal/db/push/push.go
- internal/db/remote/commit/commit.go
- internal/migration/apply/apply.go
- internal/migration/apply/apply_test.go
- internal/migration/list/list.go
- internal/migration/squash/squash.go
- internal/migration/squash/squash_test.go
- internal/migration/up/up.go
- internal/migration/up/up_test.go
- internal/utils/misc.go
- pkg/config/config.go
- pkg/migration/apply.go
- pkg/migration/file.go
- pkg/migration/list.go
- pkg/migration/seed.go
Bug fix: https://github.com/supabase/cli/issues/2510
Further refactoring and clean up.
> fix: clean file path before validation

- cmd/gen.go
- docs/supabase/domains/activate.md
- pkg/config/testdata/config.toml
chore
Generated docs is missing flags https://github.com/supabase/supabase/pull/27868/files#r1674891932
> chore: update flagset order for gen types

- internal/functions/deploy/bundle.go
- internal/functions/deploy/bundle_test.go
- internal/functions/deploy/deploy.go
- internal/functions/deploy/deploy_test.go
- internal/functions/serve/serve.go
- internal/login/login.go
- internal/seed/buckets/buckets.go
- internal/status/status.go
- internal/storage/client/api.go
- internal/storage/cp/cp.go
- internal/utils/cloudflare/dns.go
- internal/utils/deno.go
- internal/utils/deno_test.go
- internal/utils/tenant/gotrue.go
- internal/utils/tenant/postgrest.go
- pkg/config/config.go
- pkg/config/utils.go
- pkg/fetcher/http.go
- pkg/function/api.go
- pkg/function/batch.go
- pkg/function/batch_test.go
- pkg/function/bundle.go
- pkg/function/bundle_test.go
- pkg/storage/batch.go
- pkg/storage/buckets.go
- pkg/storage/objects.go
feature
Exposes functions upsert api for reuse.
> feat: expose function upsert api

- internal/storage/cp/cp.go
- pkg/config/config.go
- pkg/storage/batch.go
- pkg/storage/buckets.go
> fix: allow nil for public bucket config

- internal/db/dump/dump_test.go
- internal/functions/deploy/bundle.go
- internal/functions/deploy/deploy_test.go
- internal/gen/types/types_test.go
- pkg/config/config.go
- pkg/function/batch.go
- pkg/function/bundle.go
- pkg/storage/batch.go
> fix: update config with default values

- internal/functions/new/templates/index.ts
https://supabase.com/blog/supabase-js-on-jsr
> fix: import edge runtime types from jsr

- internal/functions/new/templates/index.ts
- internal/functions/serve/serve.go
- pkg/config/config.go
> fix: bind functions without import map when serving

- pkg/config/constants.go
> fix(db): bump postgres version for new wrappers

- cmd/link.go
- internal/db/push/push_test.go
- internal/db/reset/reset_test.go
- internal/link/link.go
- internal/link/link_test.go
- internal/logout/logout_test.go
- internal/migration/repair/repair_test.go
- internal/start/start.go
- internal/storage/rm/rm_test.go
- internal/utils/console_test.go
- pkg/config/config.go
- pkg/config/utils.go
Bug fix https://github.com/supabase/cli/issues/2327
Bug fix https://github.com/supabase/cli/issues/2539
> fix: print config line diff for clarity

- pkg/config/constants.go
> fix: Bump studio to the latest image version

- api/beta.yaml
- pkg/api/client.gen.go
- pkg/api/types.gen.go
> chore: update openapi spec and codegen

- pkg/config/constants.go
> realtime: Bump image to 2.30.23

- internal/start/start.go
> chore: pass pooler id to Kong config

- internal/start/start.go
- internal/start/templates/kong.yml
Bug fix https://github.com/supabase/cli/issues/2474
> fix: expose supervisor websocket via Kong api

- go.mod
- go.sum
- internal/utils/docker.go
> fix: update docker dependencies to silence warning

- pkg/config/templates/config.toml
Add comments to clarify mfa config
> fix: add comment for mfa settings

- internal/utils/access_token.go
> fix: support oauth token for login

- internal/start/templates/kong.yml
> feat(realtime): add longpoll route to kong

- pkg/config/constants.go
Updates service studio new version to 20240923
> fix: Bump studio to the latest image version 20240923

- api/beta.yaml
- cmd/postgres.go
- internal/postgresConfig/update/update.go
- pkg/api/client.gen.go
- pkg/api/types.gen.go
feature
```
supabase postgres-config update --no-restart
```
> feat: support postgres config update without restart

- pkg/config/constants.go
Bumps Studio to the latest version.
> fix: Bump studio to the latest image version 20241014

- pkg/config/config.go
- pkg/config/config_test.go
> fix(config): use SUPABASE env prefix

- pkg/config/constants.go
Incorporates https://github.com/supabase/postgres-meta/pull/813
> fix: pg-meta v0.84.2

- internal/link/link.go
- internal/link/link_test.go
Bug fix
Allow linking branch projects for CI environments.
> fix: ignore project not found error on linking

- pkg/config/config.go
- pkg/config/updater.go
- pkg/config/updater_test.go
- Add a [experimental.webhooks] section to the config
- Add necessary changes for use with the updater
Related:
https://github.com/supabase/infrastructure/pull/20348
> feat(config): experimental config webhooks

- pkg/config/constants.go
Bump Studio to the latest image version.
> fix: Bump studio to the latest image version 20241029

- api/beta.yaml
- internal/seed/buckets/buckets.go
- pkg/api/client.gen.go
- pkg/api/types.gen.go
- pkg/config/config.go
- pkg/function/batch.go
Bug fix
For consistency, moves objects path resolution to config.Load.
> fix(config): resolve objects path when loading buckets config

- api/beta.yaml
- internal/functions/list/list.go
- internal/link/link.go
- pkg/api/types.gen.go
chore
Split out openapi update from https://github.com/supabase/cli/pull/2814
> chore: update generated v1 api client

- pkg/config/auth.go
- pkg/config/auth_test.go
- pkg/config/config.go
- pkg/config/templates/config.toml
- pkg/config/updater.go
- pkg/config/utils.go
part 2 of https://github.com/supabase/cli/pull/2814
Syncs local sms config to remote.
> feat(config): sync sms config to remote

- pkg/config/constants.go
relates to https://github.com/supabase/cli/issues/2834
Updates studio with the latest fixes.
> fix(studio): bump studio image to 20241106-fe0e32d

- internal/login/login.go
feature
Replace long polling with verification code for browser login.
> feat: login via browser with device code

- pkg/config/constants.go
feature
Upgrade postgres locally to 15.6 by default.
> fix: bump default postgres version to 15.6

- pkg/config/constants.go
> fix: increment auth version to v2.164.0

- .github/workflows/deploy-check.yml
- .github/workflows/mirror.yml
- .github/workflows/release.yml
- .github/workflows/tag-npm.yml
- cmd/config.go
> fix: remove unnecessary cancel context

- internal/db/start/start.go
- internal/start/start.go
- pkg/config/constants.go
Bumps up Realtime version and also enables Janitor as it is required to keep tables organized
> fix(realtime): Bump up realtime version

- pkg/config/templates/config.toml
> chore: document function config in toml

- cmd/branches.go
- internal/utils/api.go
Bump cli to v2
Technically a breaking change but it's ok because branches are under experimental flag.
> BREAKING CHANGE: deprecate fly regions for branches

- pkg/config/templates/config.toml
> chore: update config comments

- pkg/config/constants.go
Bug fix
Bumps postgres for pgmq support.
> fix: bump default postgres for pgmq support

- pkg/config/storage.go
> fix: copy image transform by value

- pkg/config/constants.go
upgrade pg15 to latest version
Fixes: https://github.com/supabase/cli/issues/2902
> fix(db): upgrade pg15 to 15.8.1.020

- pkg/config/auth.go
- pkg/config/templates/config.toml
- pkg/config/testdata/config.toml
Bug fix
API hangs if we send an empty string as secret.
> fix: assume platform defaults when local sms keys are unset

- pkg/config/auth.go
- pkg/config/config.go
> fix: initialise empty map for email template

- pkg/config/config.go
- pkg/config/secret.go
- Also search for `.env` file within `supabase` folder so you can have dedicated .env for supabase deployments.
- Seach for `.env.keys` for local dotenvx development
- Try all keys matching the prefix `DOTENV_PRIVATE_KEY` so you can have `DOTENV_PRIVATE_KEY_PRODUCTION/LOCAL/PREVIEW`
> fix(config): dotenvx loading

- internal/start/start.go
Improvement
Enhance imgproxy limits to match production
> fix(storage): enhance imgproxy limits

- pkg/config/constants.go
> fix: Bump realtime image

- pkg/migration/queries/drop.sql
closes https://github.com/supabase/cli/issues/3070
> fix: ignore deprecated realtime publication

- pkg/migration/queries/drop.sql
> fix: clean up storage schema on db reset

- internal/start/start.go
- pkg/config/auth.go
- pkg/config/auth_test.go
- pkg/config/config.go
- pkg/config/templates/config.toml
- pkg/config/testdata/TestCaptchaDiff/local_disabled_remote_enabled.diff
- pkg/config/testdata/TestCaptchaDiff/local_enabled_remote_disabled.diff
- pkg/config/testdata/config.toml
feature https://github.com/orgs/supabase/discussions/28276
Closes DEVWF-334
> feat: support captcha config locally

- pkg/config/auth.go
- pkg/config/config.go
- pkg/config/db.go
> chore: validate enum when unmarshalling

- internal/start/start.go
- pkg/config/constants.go
> Revert "fix(studio): Bump studio version to 20250130-b048539"

- internal/functions/deploy/testdata/shared/whatever.ts
- internal/functions/deploy/upload.go
- internal/functions/deploy/upload_test.go
relates to https://github.com/supabase/cli/issues/3117#issuecomment-2654780428
Also include exported modules when uploading.
> fix: include export statements when resolving imports

- internal/functions/deploy/upload.go
> fix: convert deploy metadata to unix path

- api/beta.yaml
- pkg/api/types.gen.go
Bug fix https://github.com/supabase/cli/issues/3148
Wrong api spec committed.
> fix: wrong spec for password requirement

- internal/start/start.go
- pkg/config/constants.go
fixes:  
https://github.com/supabase/supabase/pull/33422
https://github.com/supabase/supabase/issues/33493
https://github.com/supabase/supabase/issues/32822
https://github.com/supabase/supabase/issues/33572
> fix: bump studio to 20250219-7101314

- internal/start/start.go
Bug fix
Regression on docker desktop from https://github.com/supabase/cli/pull/3139
> fix: block root-less socket mount for docker engine

- .github/dependabot.yml
- pkg/config/templates/Dockerfile
ci
See if dependabot can auto bump these.
> chore: let dependabot bump service images

- internal/db/diff/diff_test.go
- internal/db/diff/migra.go
- internal/db/diff/pgadmin.go
- internal/db/dump/dump.go
- internal/db/test/test.go
- internal/db/test/test_test.go
- internal/start/start.go
- internal/start/start_test.go
- pkg/config/config.go
- pkg/config/constants.go
- pkg/config/constants_test.go
- pkg/config/templates/Dockerfile
- tools/listdep/main.go
- tools/selfhost/main.go
> chore: parse image version from dockerfile

- internal/db/dump/templates/dump_schema.sh
fixes https://github.com/supabase/cli/issues/3071#issuecomment-2674515154
Comment out any statement that tries to reassign owner to supabase_admin.
> fix: do not alter publication owner to supabase_admin

- .github/workflows/ci.yml
- pkg/config/templates/Dockerfile
> fix: add pooler to start test

- pkg/config/auth_test.go
- pkg/config/testdata/TestCaptchaDiff/local_disabled_remote_enabled.diff
- pkg/config/testdata/TestCaptchaDiff/local_enabled_remote_disabled.diff
- pkg/config/testdata/TestEmailDiff/local_disabled_remote_enabled.diff
- pkg/config/testdata/TestEmailDiff/local_enabled_remote_disabled.diff
- pkg/config/testdata/TestExternalDiff/local_enabled_and_disabled.diff
- pkg/config/testdata/TestHookDiff/local_disabled_remote_enabled.diff
- pkg/config/testdata/TestHookDiff/local_enabled_remote_disabled.diff
- pkg/config/testdata/TestMfaDiff/local_enabled_and_disabled.diff
- pkg/config/testdata/TestSmsDiff/enable_sign_up_without_provider.diff
- pkg/config/testdata/TestSmsDiff/local_disabled_remote_enabled.diff
- pkg/config/testdata/TestSmsDiff/local_enabled_remote_disabled.diff
- pkg/config/updater_test.go
- pkg/config/utils.go
Bug fix
https://github.com/supabase/cli/issues/2539#issuecomment-2679220172
> fix: eliminate link warning on additional url

- internal/start/start.go
- pkg/config/config.go
- pkg/config/secret.go
- pkg/config/secret_test.go
Bug fix https://github.com/orgs/supabase/discussions/18937#discussioncomment-12327922
- Do not rely on global viper state in shared package.
- Fixes plaintext secrets in `.env.local` not loading.
> fix: remove dependency on global viper

- cmd/root.go
- internal/functions/serve/serve.go
- internal/secrets/set/set.go
Bug fix https://github.com/supabase/cli/issues/3285#issuecomment-2718366751
Also fixes https://github.com/supabase/cli/issues/3287
Regression from https://github.com/supabase/cli/pull/3246
> fix: remove current dir prefix from default env

- internal/secrets/set/set.go
- internal/secrets/set/set_test.go
Bug fix https://github.com/supabase/cli/issues/3293
> fix: check for empty path when setting secret

- pkg/config/templates/Dockerfile
Bug fix https://github.com/supabase/cli/issues/3296
> fix: revert logflare to 1.12.0

- internal/db/diff/diff.go
Bug fix https://github.com/supabase/cli/issues/3351
Lists the declared schemas in order.
```
Creating local database from declarative schemas:
• supabase/schema/1_schema.sql
Initialising schema...
```
> fix: account for declared schemas in config file

- pkg/config/config.go
Bug fix
If a static value is declared in remotes block, use that instead of integration env.
> fix: remote block should override env

- internal/branches/get/get.go
- internal/branches/list/list.go
- internal/migration/list/list.go
Bug fix
Renders json output when global `-o json` flag is specified.
Also addresses https://github.com/orgs/supabase/discussions/18937#discussioncomment-12473951
> fix: format output for branches list

- internal/start/start.go
- pkg/config/templates/Dockerfile
Bug fix
Updates studio image tag to version release.
> fix: bump studio version and add version flag

- internal/bans/update/update.go
- internal/bans/update/update_test.go
feature
Allows unbanning IPv6 address.
```bash
supabase --experimental network-bans remove --db-unban-ip=::0
```
> feat: unban ipv6 address

- pkg/config/templates/config.toml
- pkg/config/testdata/config.toml
Bug fix
Bump default postgres version to 17.
> fix: update default postgres major version to 17

- .github/workflows/api-sync.yml
> chore(ci): add pr automerge on approval

- internal/link/link.go
- pkg/pgxv5/connect.go
Bug fix
Full diff is available when running `config push` if user is interested.
> fix: skip config diff to reduce output noise

- pkg/config/templates/Dockerfile
https://github.com/supabase/postgres-meta/compare/v0.91.5...v0.91.6
Fixes PGMETA-73
> chore(deps): bump pg-meta to v0.91.6

- cmd/bans.go
- internal/bans/update/update.go
- internal/bans/update/update_test.go
- internal/utils/flags/db_url.go
- internal/utils/retry.go
Bug fix
Due to stale pooler cache, user might end up accidentally IP banned using temp login role.
> fix: auto unban on login password error

- pkg/function/bundle.go
Bug fix
Timeout commands to avoid being stuck forever.
> fix: support custom timeout when bundling functions

- go.mod
- internal/utils/connect.go
- internal/utils/connect_test.go
Bug fix https://github.com/supabase/setup-cli/issues/354
Regression
> fix: check pooler domain belongs to current profile

- api/overlay.yaml
- cmd/branches.go
- internal/branches/create/create.go
- internal/branches/delete/delete.go
- internal/branches/get/get.go
- internal/branches/list/list.go
- internal/branches/pause/pause.go
- internal/branches/update/update.go
- pkg/api/client.cfg.yaml
- pkg/api/client.gen.go
- pkg/api/types.gen.go
Bug fix
Switch from uuid to branch project ref.
> feat: use branch ref in all commands

- pkg/config/auth.go
Adds support for enabling the Ethereum Auth provider.
> feat: add support for enabling ethereum provider

- internal/branches/list/list.go
- internal/link/link.go
Bug fix
Display more info about branches.
> fix: show whether a branch is created with data

- internal/start/start.go
- internal/start/templates/kong.yml
> fix: replace auth header for backwards compatibility

- internal/debug/postgres.go
> fix: ignore closed pipe error debug flag

- cmd/login.go
- cmd/root.go
- internal/utils/misc.go
- internal/utils/profile.go
Bug fix
Remember the profile flag used for login for convenience.
> fix(DEVWF-755): remember profile after login
